### ISSUE TITLE
[Bug]: Page not found 404

### ISSUE THREAD

**Issue by Adrean-Danilo** [coder/code-server#4935] opened 2022-03-02 14:31 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome Android
- Local OS: Android Termux
- Local Architecture: armhf
- `code-server --version`: 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd

### Steps to Reproduce

1. Open code-server
2. Enter the local port that the code-server is on
3. Enter the password and click submit

### Expected

A 404 error should appear on the screen.

### Actual

The 404 error occurs in the browser and in the terminal this appears...
![Screenshot_20220302-110339_Termux](https://user-images.githubusercontent.com/92446796/156376604-1abd277a-ae54-459c-b0ee-105664cfdd95.jpg)

### Logs

Logs:
------------------------------------
yarn global add code-server :
```
yarn global v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...                                                              [3/4] Linking dependencies...
warning "code-server > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...                                                        success Installed "code-server@4.0.2" with binaries:                                          - code-server
Done in 819.69s.
```
------------------------------------
code-server --verbose:
```
[2022-03-02T14:23:26.460Z] trace child:2149 got message {"message":{"type":"handshake","args":{"bind-addr":"127.0.0.1:8800","auth":"password","password":"adrean","config":"/root/.config/code-server/config.yaml","verbose":true,"user-data-dir":"/root/.local/share/code-server","extensions-dir":"/root/.local/share/code-server/extensions","log":"trace","host":"127.0.0.1","port":8800,"proxy-domain":[],"_":[],"usingEnvPassword":false,"usingEnvHashedPassword":false}}}
[2022-03-02T14:23:26.475Z] info  code-server 4.0.2 5cdfe74686aa73e023f8354a9a6014eb30caa7dd
[2022-03-02T14:23:26.476Z] info  Using user-data-dir ~/.local/share/code-server
[2022-03-02T14:23:26.476Z] trace Using extensions-dir ~/.local/share/code-server/extensions                                                                                     [2022-03-02T14:23:26.540Z] info  Using config file ~/.config/code-server/config.yaml
[2022-03-02T14:23:26.540Z] info  HTTP server listening on http://127.0.0.1:8800/
[2022-03-02T14:23:26.541Z] info    - Authentication is enabled
[2022-03-02T14:23:26.541Z] info      - Using password from ~/.config/code-server/config.yaml
[2022-03-02T14:23:26.541Z] info    - Not serving HTTPS
```

### Screenshot/Video

![Screenshot_20220302-104957_Chrome](https://user-images.githubusercontent.com/92446796/156375173-dae01490-cac3-4bca-ab2a-280d0fe5edb4.jpg)

### Does this issue happen in VS Code?

- [x] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

**Comment by jsjoeio** [comment] 2022-03-02 20:06
Duplicate of https://github.com/coder/code-server/issues/4900 - this will be resolved in the next release!

**Closed by jsjoeio** 2022-03-02 20:06 UTC
Labels: bug, triage

**Comment by Adrean-Danilo** [comment] 2022-03-03 18:07
Thanks, I already solved using the folder tar gz for ARMv7

**Comment by Yusuf-Uluc** [comment] 2022-03-04 00:09
> Duplicate of #4900 - this will be resolved in the next release!

Can you already give an estimate when that will come out? :)
