### ISSUE TITLE
Jupyter Notebook in Integrated Terminal is not persistent on refresh

### ISSUE THREAD

**Issue by kobster2000** [coder/code-server#6966] opened 2024-08-28 14:29 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Google Chrome Version 127.0.6533.119
- Local OS: MacOS M1 ARM
- Remote OS:
- Remote Architecture:
- `code-server --version`: v1.92.2

### Steps to Reproduce

1. Open code-server in browser
2. Open Jupyter Notebook in 
3. Execute a long-running Python script
4. Close the code-server tab
5. Open the code-server tab

### Expected

The terminal session should persist on reload: the state of the long-running Python script should be maintained (I should see the exact updated status of the running script) 

### Actual

There was no session persistence of the code running in Jupyter Notebook. Closing and reopening the code-server tab did not retain the state of the long-running Python script.

### Screenshot/Video

https://github.com/user-attachments/assets/bd92035f-514b-4978-a0e7-afa676d0b047

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment] 2024-08-28 20:31
I might not be quite understanding, the issue seems to say that the script is not persisting, but it looks like it does persist?

I will say though, that although VS Code web does have terminal persistence, it does not have extension persistence.  Reloading the tab kills the extension host, so sometimes things can get disconnected, like if you are debugging for example, and probably the Jupyter extension is also affected.  Not something we can fix unfortunately, it requires a rewrite of their entire architecture.

**Comment by kobster2000** [comment] 2024-08-29 09:44
Here is the relevant capture

https://github.com/user-attachments/assets/dd8dea4d-24b3-4c80-8ce7-b6c5db2ad630

**Comment by code-asher** [comment] 2024-08-29 22:35
Ahhh OK perfect yeah this is that extension host thing I mentioned.  Either VS Code will have to be rewritten to persist the extension host on reload, or the Jupyter extension will need to somehow preserve its own state.  The issue mentions you reproduced in Codespaces, is that right?  Maybe we could use that to open an issue upstream in https://github.com/microsoft/vscode but I will close this issue because trying to change VS Code's architecture here in code-server would be out of scope (and probably quite difficult).

**Closed by code-asher** 2024-08-29 22:35 UTC
Labels: bug, triage

**Comment by code-asher** [comment] 2024-08-29 22:40
I think this is related: https://github.com/microsoft/vscode-jupyter/issues/3998

**Comment by antecede** [comment] 2025-02-18 05:59
This question is a real headache! If this problem can be solved, it will be possible to completely move from jupyter to codeserver!
Besides, it would be perfect if the codeserver could support the JupyterLab plugin.
