### ISSUE TITLE
[Bug]: Missing files after extension upgrades? Can no longer connect to workspace. MaxListenersExceededWarning

### ISSUE THREAD

**Issue by tmikaeld** [coder/code-server#6038] opened 2023-03-01 10:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Any
- Local OS: MacOS
- Remote OS: Debian 11
- Remote Architecture: amd64
- `code-server --version`: 4.10

### Steps to Reproduce

1. Start code server
2. use code server
3. randomly failed..

![image](https://user-images.githubusercontent.com/907195/222116795-0a2daaa8-98d3-42cc-9615-1dde60e1c0f0.png)

### Expected

Code server should work

### Actual

404 on these files:

![image](https://user-images.githubusercontent.com/907195/222117148-416c6cd8-76db-4105-bb3e-8f71c49235d0.png)

/static/extensions/git-base/dist/browser/extension.js
/static/extensions/emmet/dist/browser/emmetBrowserMain.js
/static/extensions/merge-conflict/dist/browser/mergeConflictMain.js

### Logs

(node:189) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
(node:189) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:189) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGPIPE listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:189) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 unhandledRejection listeners added to [process]. Use emitter.setMaxListeners() to increase limit
(node:189) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 rejectionHandled listeners added to [process]. Use emitter.setMaxListeners() to increase limit
File not found: /usr/lib/code-server/lib/vscode/extensions/emmet/dist/browser/emmetBrowserMain.js
File not found: /usr/lib/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
File not found: /usr/lib/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment] 2023-03-03 22:55
The missing files might be something we need to look into (looks 
like it is trying to load the browser versions for some reason 
which are not packaged) but I think the cause of the connection 
issue is the 1006 on the web sockets.  Usually this means web 
sockets are not being handled properly.  Can you tell us more 
about your setup?  Are you behind a reverse proxy?  If so what 
does the configuration look like?

You mentioned an upgrade, was it working prior to 4.10.0?

**Comment by xolom** [comment] 2023-11-17 19:12
Same issue here. Running `code-server 4.18.0`

**Comment by liusky0212** [comment] 2023-12-07 07:31
code-server 4.9--->4.18 have same issue , code server behind nginx

see most log
`debug host "x.com" does not match origin "x.com:3000"; blocking request to /stable-d7a2b4936af1bfd80cb96f2567af68badc2325e3?reconnectionToken=e8438e74-92d4-4247-aae8-d927c61e72b6&reconnection=false&skipWebSocketFrames=false `

it has Cross-Origin Issues!
The issue has been successfully resolved by using --trusted-origins 

you can give it a try

**Comment by xuefei6000** [comment] 2024-07-04 06:38
codercom/code-server:4.90.3

$docker logs cde3e235e2da
[2024-07-04T03:26:31.597Z] info  code-server 4.90.3 26c763485b9101fcae2ce56fc0903f0e2d48abe3
[2024-07-04T03:26:31.600Z] info  Using user-data-dir /home/coder/.local/share/code-server
[2024-07-04T03:26:31.615Z] info  Using config file /home/coder/.config/code-server/config.yaml
[2024-07-04T03:26:31.615Z] info  HTTP server listening on http://0.0.0.0:8080/
[2024-07-04T03:26:31.615Z] info    - Authentication is enabled
[2024-07-04T03:26:31.615Z] info      - Using password from $PASSWORD
[2024-07-04T03:26:31.615Z] info    - Not serving HTTPS
[2024-07-04T03:26:31.615Z] info  Session server listening on /home/coder/.local/share/code-server/code-server-ipc.sock
[03:26:55]

[03:26:55] Extension host agent started.
[03:26:55] Started initializing default profile extensions in extensions installation folder. file:///home/coder/.local/share/code-server/extensions
[03:26:55] Completed initializing default profile extensions in extensions installation folder. file:///home/coder/.local/share/code-server/extensions
File not found: /usr/lib/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
File not found: /usr/lib/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js
File not found: /usr/lib/code-server/lib/vscode/extensions/git-base/dist/browser/extension.js
File not found: /usr/lib/code-server/lib/vscode/extensions/merge-conflict/dist/browser/mergeConflictMain.js


Same issue here, who can help me

**Comment by code-asher** [comment] 2024-07-12 00:55
Closing as stale but feel free to comment if you come back to this.

**Closed by code-asher** 2024-07-12 00:55 UTC
Labels: bug, triage
