### ISSUE TITLE
[Bug]: Hover feature does not work in Jupyter notebooks

### ISSUE THREAD

**Issue by cgebbe** [coder/code-server#6323] opened 2023-07-12 09:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1. open code-server
2. create a new jupyter notebook
3. install python and jupyter extensions

### Expected

- Given a jupyter notebook 
- When writing e.g. `import numpy` and `np.ones(`
- Then a nice hover window pops up

### Actual

- No hover window pops up

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

- This works in VS Code
- This works in Github Codespaces (even with JEDI language server)
- Given a plain python file in code-server, the same steps DO lead to a hover window.
- //EDIT: Also just realized that functions such as `peek definition` also do not work in a jupyter notebook in code-server?

**Comment by benz0li** [comment] 2023-07-12 16:14
I can confirm that this works with the current versions of

- VS Code/Codespaces: 1.80.0
- Python extension: 2023.12.0
- Jupyter extension: 2023.6.1101941928

Please be aware that code-sever (current version: 4.14.1, aka Code 1.79.2) relies on the [Open VSX Registry](https://open-vsx.org), which currently provides

- Python extension: 2023.10.1
- Jupyter extension: 2023.3.100

for code-server v4.14.1.

---

Let us re-evaluate after @code-asher has updated code-server so it is based on Code 1.80.

**Comment by benz0li** [comment] 2023-07-12 16:37
Most probably due to [Pylance](https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance) only being published to the VS Code marketplace.  
ℹ️ Pylance only runs with the official VS Code build.

Cross reference: https://github.com/microsoft/pylance-release/issues/746

**Comment by benz0li** [comment] 2023-08-09 05:15
@cgebbe The situation regarding Pylance is not going to change.

Please close this issue.

**Comment by OceanTrader1** [comment] 2023-11-11 20:33
As @benz0li mentioned, `Pylance` is only published to the VS Code marketplace; however, `Jedi` can be used instead of Pylance.

https://github.com/coder/code-server/assets/69881238/3dd1e13d-cad1-4d47-9bee-9a6a98379a28

Configure settings.json
```json
{
    "python.languageServer": "Jedi",
}
```

Python extension details
```
Name: Python
Id: ms-python.python
Description: IntelliSense (Pylance), Linting, Debugging (multi-threaded, remote), code formatting, refactoring, unit tests, and more.
Version: 2023.21.13141007
Publisher: ms-python
VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=ms-python.python
```

Jupyter extension details
```
Name: Jupyter
Id: ms-toolsai.jupyter
Description: Jupyter notebook support, interactive programming and computing that supports Intellisense, debugging and more.
Version: 2023.9.100
Publisher: ms-toolsai
VS Marketplace Link: https://open-vsx.org/vscode/item?itemName=ms-toolsai.jupyter
```

Code-server
```
code-server: v4.18.0
Code: 1.83.1
Commit: d7a2b4936af1bfd80cb96f2567af68badc2325e3
Date: 2023-10-19T00:53:43.414Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
```

**Comment by rohit901** [comment] 2024-01-04 12:11
@OceanTrader1 thanks for this, I wanted to ask what is the difference between using Pylance vs Jedi? is there any tradeoff for making this change?

**Comment by code-asher** [comment] 2024-04-09 17:56
Closing since it looks like there is nothing we can do.

**Closed by code-asher** 2024-04-09 17:56 UTC
Labels: bug, triage
