### ISSUE TITLE
Download of multiple files at once fails

### ISSUE THREAD

**Issue by ldcorentin** [coder/code-server#6855] opened 2024-06-21 14:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Debian
- Remote Architecture: x86_64
- `code-server --version`: 4.89.0

### Steps to Reproduce

1. Open coder-server in chrome
2. Upload 20 files. (The total amount on my side is 76K) 
3. Download them all at once

### Expected

I expect to have all 20 files in my download folder.

### Actual

Sometimes I have 13, sometimes 15 files but never 20 files. No errors have been raised.

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment] 2024-06-21 18:08
Interesting.  This code is all in VS Code so if we can reproduce in Codespaces we should try raising the issue upstream at https://github.com/microsoft/vscode.

**Comment by ldcorentin** [comment] 2024-06-24 06:58
Thanks @code-asher, I just tried from Codespaces and I had no issues, I have all 20 files downloaded

**Comment by ldcorentin** [comment] 2024-06-27 13:38
I don't see any error logs in my browser

**Comment by code-asher** [comment] 2024-06-27 19:40
Maybe there will be more logs if you run with `--verbose` but I am not sure.

Another thing you could try is running VS Code's web version directly without our `code-server` wrapper and patches (you can run it by installing VS Code and running `code serve-web`) and see if that exhibits the same behavior.

**Comment by code-asher** [comment] 2024-07-11 23:57
Closing for now since we lack a reproduction, but if something changes I am happy to try again.

**Closed by code-asher** 2024-07-11 23:57 UTC
Labels: bug
