### ISSUE TITLE
PlatformIO IDE extension does not work on code-server v3.0.1 from Docker Hub

### ISSUE THREAD

**Issue by r0zzy5** [coder/code-server#1448] opened 2020-03-23 19:33 UTC
I am trying to install the PlatformIO IDE extension on a code-server v3.0.1 instance hosted in a docker container. I am running Docker Desktop on Windows 10 Pro and accessing code-server using Chrome 80. The extension seems to install fine using the extension manager in code-server, but when I try to open the PlatformIO Home tab, Chrome reports that 127.0.0.1:8010 did not send any data and therefore the PlatformIO Home page is not shown:

![PlatformIO error](https://user-images.githubusercontent.com/5203904/76127853-b61c6b80-5ffa-11ea-8cf1-9d832977c8a1.png)

I am using the following Dockerfile:

    FROM codercom/code-server:3.0.1
    
    USER root
    
    RUN apt-get update && apt-get install -y python3 python3-distutils \
    	&& rm -rf /var/lib/apt/lists/*
    
    USER coder
    
    EXPOSE 8010
    
    ENTRYPOINT ["dumb-init", "fixuid", "-q", "/usr/local/bin/code-server", "--host", "0.0.0.0", "--auth", "none", "."]

And the following docker-compose.yml:

    version: '3.3'
    services:
        code-server-platformio:
            image: r0zzy5/code-server-platformio
            ports:
                - '8080:8080'
                - '8010:8010'
            volumes:
                - './src:/home/coder/project'

**Comment by x-cubed** [comment] 2020-04-04 10:39
I've had a quick look at this.

platformio starts a server listening on 127.0.0.1:8010. This is because it usually only needs to be accessible on the same machine when running on the desktop. The catch is that this can't be exposed by Docker, as Docker only maps through to non-loopback addresses.

platformio home supports a *--host* argument to get it to listen on another interface, so it can be started with *--host=0.0.0.0* so that it can be exposed by Docker.

Not sure what the right fix is though. Should platformio know that it's running in a server environment, or should there be some special logic in code-server to handle it?

It'd be nice to get it working out of the box without any custom Dockerfiles involved.

**Comment by r0zzy5** [comment] 2020-04-07 07:17
@x-cubed, I agree it would be best if this could "just work" without any custom Dockerfiles.

However for the time being, where would I configure my platformio home to launch using the --host argument?

**Comment by kylecarbs** [comment] 2020-04-07 15:27
We could fix this with the addition of our #1453 feature.

Thoughts @code-asher ?

**Comment by code-asher** [comment] 2020-04-07 17:32
Yeah, seems like we could just access it at `<domain>/proxy/8010`. I didn't see an option for changing the URL it tries to open though so I'm not sure how we'd make that work. Maybe it's possible to detect a webview opening on `127.0.0.1:port` and change it to the proxy domain instead.

**Comment by justurn** [comment] 2020-05-27 09:18
Just got this to run on my system will leave this for anyone it may help...

In the PIO terminal on code-server use the command pio home --host x.x.x.x --port 8010 where x.x.x.x is the IP of the docker then bridge the docker port to the host like @r0zzy5 showed. You should then have access to the PIO webgui through http://y.y.y.y:8010 where y.y.y.y is the docker host IP

**Comment by ricreis394** [comment] 2021-03-18 21:45
Any update on this?

**Comment by jsjoeio** [comment] 2021-03-19 16:07
@ricreis394 do the solutions above not work for you? If not, we can take a look into this again.

**Comment by ricreis394** [comment] 2021-03-19 16:30
@jsjoeio when I click to open PlatformIO Home Page, the UI tries to load a frame which is pointer to 127.0.0.1:<port>, which obviously cannot load.

The commands used in command line are as follows:
`pio home --host <internal_docker_ip> --port 8010`
`pio home --host localhost --port 8010`

These 2 above loads something, but not completely, using the subsubdomain port like: `8010.code.example.com`

**Comment by jsjoeio** [comment] 2021-03-19 17:45
Ah okay! Hmm..I am not familiar with PlatformIO.

Would it be possible for you to provide reproduction steps using the latest version of code-server? If you need an example, look at our [bug report template](https://github.com/cdr/code-server/issues/new?assignees=&labels=&template=bug-report.md&title=).

With that, I'd be happy to take a closer look for you.

**Comment by ricreis394** [comment] 2021-03-19 23:10
## OS/Web Information

- Web Browser: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)
- Local OS: Windows 10
- Remote OS: linuxserver (maybe alpine?)
- Remote Architecture: x86-64
- `code-server --version`: 3.9.1 e0203f2a36c9b7036fefa50eec6cf8fa36c5c015

## Steps to Reproduce

1. Install PlatformIO extension
2. Go to PlatformIO sidebar section, click PIO Home -> Open

## Expected


It should appear the PIO Home webpage

## Actual


Appears `127.0.0.1 refused to connect.`

## Screenshot


![platformio](https://user-images.githubusercontent.com/11768109/111850377-087bb200-8908-11eb-94a3-8952f4be6112.gif)


## Notes

when I click to open PlatformIO Home Page, the UI tries to load a frame which is pointer to `127.0.0.1`:, which obviously cannot load.

The commands used in command line are as follows:
`pio home --host <internal_docker_ip> --port 8010`
`pio home --host localhost --port 8010`

These 2 above loads something, but not completely, using the subsubdomain port like: `8010.code.example.com`



This issue can be reproduced in VS Code: No

**Comment by jsjoeio** [comment] 2021-03-22 17:23
Awesome! Thanks so much for the detailed repro steps @r0zzy5 - we'll take a look at this in the next milestone/sprint!

**Comment by tbhova** [comment] 2021-03-23 01:37
+1 to this issue.

The bug mentions a reverse proxy, but I don't think is necessary to repro. I can repro this behind my Traefik reverse proxy or at <server_local_ip>:port. I did not test whether localhost works because my server is headless.

I have a [Dockerfile here](https://github.com/tbhova/home-server/blob/master/vscode/Dockerfile) that installs PlatformIO automatically and reproduces the issue.

**Comment by RoboMagus** [comment] 2021-03-25 10:20
I've been struggling with the same issue for a while as well. What worked for me is quite a blunt method, but I've done a global replace for all occurrences of '127.0.0.1' in the platformio-core directory (/config/.platformio) with '0.0.0.0'.
This together with the exposed 8010 port as in @tbhova's Dockerfile and fixing this port to that value in the platformio-ide settings (Platformio-ide: Pio Home Server Http Port) solved it for me.

Well, I wouldn't like say solved as it's a nuisance that there's no easy interface for setting the ip address to be used for communicating with the pio-core as part of the platformio extension...

**Comment by yqboy** [comment] 2021-04-23 16:31
There is such a setting option in platformio.platformio-ide-2.3.2/package.json 
![image](https://user-images.githubusercontent.com/19944861/115901641-07ecb300-a494-11eb-8737-d5729eb6bedc.png)

I tried it in docker and it worked

**Comment by jsjoeio** [comment] 2021-04-23 17:12
That's awesome to hear - thanks for sharing @yqboy! 

@RoboMagus let us know if you get a chance to try using that setting option and see if it fixes your issue

**Comment by RoboMagus** [comment] 2021-04-23 19:38
That setting @yqboy mentions is actually a fix of mine that got merged ;)
I'm working on getting it working behind a reverse proxy as well though...

**Comment by jsjoeio** [comment] 2021-04-23 20:56
Oh HA! Totally missed it. Nice :D 

Okay well keep us posted.

**Comment by utya** [comment] 2021-06-08 07:58
Please explain me, What should i do to config code server with working platformIO. Now i use caddy, and don't know how to configure

**Comment by RoboMagus** [comment] 2021-06-08 09:15
I currently use a Dockerfile as below to ensure the prerequisites are met for installing the PlatformIO plugin.

```Dockerfile
FROM ghcr.io/linuxserver/code-server

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-distutils python3-dev python3-pip curl make && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

Then ensure that the PlatformIO settings in VScode are set correctly. I.e. set the IP to 0.0.0.0 instead of 127.0.0.1, and make the port static. I have it set to 8010. Then make sure this port is exported when starting the docker container.

Do note though that only one instance can be opened and linked to PIO at any given time, as only one port can be set to static and each new session requires it's own port.

**Comment by utya** [comment] 2021-06-08 12:04
@RoboMagus 
make like this
docker run -d \
  --name=code-server \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/London \
  -e PASSWORD=pass `#optional` \
  -e HASHED_PASSWORD= `#optional` \
  -e SUDO_PASSWORD=password `#optional` \
  -e SUDO_PASSWORD_HASH= `#optional` \
  -e PROXY_DOMAIN=domain `#optional` \
  -p 8443:8443 \
  -p 8010:8010 \
  -e DOCKER_MODS=linuxserver/mods:code-server-python3 \
  -v /home/utya:/config \
  --restart unless-stopped \
  ghcr.io/linuxserver/code-server
  
  change to 0.0.0.0, and doesn't work

**Comment by rdotts** [comment] 2021-06-25 05:41
I'm was experiencing the same issues with effectively the same setup as @utya, except with a compose file.  I also tried installing code-server without docker and had similar issues - with enough tinkering I was eventually able to access PIO directly at $LOCAL_IP:8010, but code-server refused to show anything in the extension window.

Just to be clear, my exact symptoms are:
 - Error message "127.0.0.1 refused to connect" when host was set to 127.0.0.1. 
 - Black (blank?) frame when set to either $LOCAL_IP or 0.0.0.0
 - Occasionally seeing "Loading..." for a few seconds before the black frame - couldn't pin down what was changing to make that happen.
 - Setting the port to static or dynamic didn't seem to make a difference.
 - I had https enabled and working, and the strict SSL option was set to false.

**Comment by chrishdx** [comment] 2021-11-20 16:37
hi, ich habe eine Lösung gefunden allerdings nutze ich keinen Docker sondern direkt Ubuntu sollte aber auf einen Docker Container anwendbar sein. Da Platformio in einen Iframe sitzt funktioniert es nicht richtig wenn es nicht auf 127.0.0.1 verweist ich habe einen Caddyserver als Proxy genutzt und in der visx startet der pio Home Server auf 0.0.0.0 aber im Iframe wird er eintrag aus der Package json genommen und auf https verwiesen jedoch immer +50 d.h. der Pio Server startet auf Port 8010 aber im Iframe steht dann https://IP:8060/session/ so kann man dann über die Caddyfile von 8060 auf 8010 verweisen und es ist kein gemischter Inhalt.

![Bildschirmfoto](https://user-images.githubusercontent.com/50511550/142734067-87f09013-8e08-4687-aa1b-7dbd70889afe.png)

**Comment by tbhova** [comment] 2022-04-10 18:59
My [dockerfile posted above](https://github.com/coder/code-server/issues/1448#issuecomment-804518335) has stopped working.

If I connect a terminal to the code-server container and run
```
cd /usr/lib/code-server
code-server --install-extension platformio.platformio-ide --force
```

I get the error logs:
```
Installing extensions...
Extension 'platformio.platformio-ide' not found.
Make sure you use the full extension ID, including the publisher, e.g.: ms-dotnettools.csharp
Failed Installing Extensions: platformio.platformio-ide
```

It looks like [these code-server docs](https://github.com/coder/code-server/blob/10f57bac65f9aa5938df4e495da39c608fbf7798/docs/FAQ.md#why-cant-code-server-use-microsofts-extension-marketplace) explain why MS' extension marketplace isn't used and suggest Open VSX.

PlatformIO has [this tracking issue](https://github.com/platformio/platformio-vscode-ide/issues/1802) to add itself to Open VSX.

I'm going to continue following these issues, but I'm likely going to switch to a VSCode VM.

**Comment by melwinek** [comment] 2023-05-24 06:43
Has anyone been able to get PlatformIO running in docker in code-server?

**Comment by code-asher** [comment] 2024-07-11 23:07
Closing this out since from what I can tell, this is an extension issue?  Instead of using 127.0.0.1 I think they need to use `asExternalUri` or something like that.  But if there is something we need to change in code-server let me know and we can reopen.

**Closed by code-asher** 2024-07-11 23:07 UTC
Labels: bug, extension, needs-investigation
