### ISSUE TITLE
When I change computers I lose my extensions and github configuration.

### ISSUE THREAD

**Issue by Kriihz77** [coder/code-server#6935] opened 2024-08-06 23:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Win
- Remote OS: Debian - Docker
- Remote Architecture: amd64
- `code-server --version`: v4.91.1

### Steps to Reproduce

1. On a computer I configure everything I need
2. From another authentic computer
3. All the Extensions configuration and access to Github is lost.
4. The extensions.json file is validated and found empty.

### Expected

As it is accessed from a web, for all computers should keep the same configuration, since this is on the server, the extensions.json file should be kept as initially configured.

### Actual

All extensions and settings are deleted between browser changes.

### Logs

```shell
services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
      - PASSWORD=123456789 #optional
      - SUDO_PASSWORD=987654321 #optional
      - PROXY_DOMAIN=code-server.kriihz.com #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./config:/config
    ports:
      - 17080:8443
    restart: unless-stopped
```

### Does this bug reproduce in native VS Code?

This cannot be tested in native VS Code

### Does this bug reproduce in GitHub Codespaces?

This cannot be tested in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment] 2024-08-07 19:42
Looks like a duplicate of https://github.com/coder/code-server/issues/4212

Unfortunately, VS Code stores the state in the browser so switching computers or even browsers loses everything.

**Closed by code-asher** 2024-08-07 19:42 UTC
Labels: bug, triage

**Comment by code-asher** [comment] 2024-08-07 19:44
Wait but are you saying you lose the extensions themselves?  Or just their configuration?  Extensions themselves should not be lost, unless they are browser extensions.  I am not familiar with the `linuxserver` image, but you probably need to mount `~/.local/share/code-server/extensions`.

**Comment by Kriihz77** [comment] 2024-08-08 01:54
What a pity with you Asher, you are right, what is lost are the code-server extensions, not the browser ones hahahaha, but when validating the directory on the server these have them, but the extension.json file has nothing, I want to share with you some screenshots so you can see a little more the problem.

![Evidencia3](https://github.com/user-attachments/assets/7ee2f104-af62-42a6-805c-27f6b0e081b8)
![Evidencia2](https://github.com/user-attachments/assets/4822d474-16d7-405f-9fc2-42a43895287d)
![Evidencia1](https://github.com/user-attachments/assets/c404a1cd-5896-458c-9a50-50e24bdcd353)

As you can see I have the extensions installed, but when I change browser they do not appear installed.

**Comment by code-asher** [comment] 2024-08-08 18:27
Interesting!  Does the `linuxserver` image set the extension directory to `/config/extensions`?  I thought the default was `~/.local/share/code-server/extensions`.

Maybe there was a recent change that made this browser-dependent.  I will try to reproduce later.

**Comment by Kriihz77** [comment] 2024-08-08 23:50
![image](https://github.com/user-attachments/assets/815437ba-c09a-4a8f-91ee-1389f9000180)

I was left with the doubt and came to check hahahaha

**Comment by code-asher** [comment] 2024-08-09 21:36
Ahhh yup they override it to `/config/extensions`: https://github.com/linuxserver/docker-code-server/blob/e4b105a61adb82b359e3c2f89468c02220654fb7/root/etc/s6-overlay/s6-rc.d/svc-code-server/run#L22

**Comment by code-asher** [comment] 2024-08-09 22:07
I do not have a second computer to try right now but I experimented with two different browsers, which should be equivalent:

1. Run `docker run -p 8080:8443 --rm linuxserver/code-server`
2. Open localhost:8080 in a browser.
3. Install the Python extension from the UI.
4. Open localhost:8080 in a different browser
5. The Python extension is still installed.
 
Maybe there is something else causing that `extensions.json` to reset but I am not sure what it could be.
