### ISSUE TITLE
[Bug]: code-server on Termux:Unable to write file 'vscode-remote:/....../User/settings.json' (Canceled: Canceled)

### ISSUE THREAD

**Issue by blackpancake** [coder/code-server#4805] opened 2022-01-28 14:12 UTC
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### OS/Web Information

- Web Browser: The latest version of the Edge browser
- Local OS: Windows
- Remote OS: Termux on Android
- Remote Architecture: aarch64
- `code-server --version`: v4.0.1

### Steps to Reproduce

1. install Termux on your Android phone
2. use`yarn global add code-server`to install code-server      (The process of installing dependencies has been omitted)
3. run code-server

### Expected

Can read and write `settings.json` and other files normally

### Actual

![image](https://user-images.githubusercontent.com/62934143/151559700-62b4303d-46b5-451e-854b-0eaa18044f0b.png)
when i tried to edit `settings.json` to change the theme:
```
Unable to write file 'vscode-remote:/data/data/com.termux/files/home/.local/share/code-server/User/settings.json' (Canceled: Canceled)
```
and the `settings.json` has not been altered.

### Logs

I uploaded the output from the browser console to [here](https://pastebin.com/mSLqcaBb)
it records my operation

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

![image](https://user-images.githubusercontent.com/62934143/151561330-9949fec7-eb20-4969-9726-c61bdbf8e424.png)
tips: i am not using HTTPS
but if i do not check this
i cannot submit my issue XD

**Comment by jsjoeio** [comment] 2022-01-28 21:59
> tips: i am not using HTTPS

Lol no worries. This issue doesn't seem to be related to that. I'll have to see if I can reproduce locally on my Android phone.

**Comment by blackpancake** [comment] 2022-01-29 01:28
this is my script that i used to install code-server.
```
pkg install vim git wget proot yarn
pkg install ripgrep
ln -s $PREFIX/bin/rg ./lib/vscode/node_modules/vscode-ripgrep/bin/rg
pkg install binutils
v=$(node -v); v=${v#v}; v=${v%%.*}
FORCE_NODE_VERSION="$v" yarn global add code-server --ignore-engines
yarn global add semver-umd applicationinsights @coder/node-browser yauzl yazl spdlog
npm install -g yauzl
npm install -g yazl
npm install -g minimist
code-server
```

**Comment by jsjoeio** [comment] 2022-01-31 20:23
@blackpancake what version of Node are you using? And was it working before with any previous versions of code-server?

**Comment by blackpancake** [comment] 2022-02-01 03:21
> @blackpancake what version of Node are you using? And was it working before with any previous versions of code-server?

i am using v17.4.0 and i enabled FORCE_NODE_VERSION to force the code-server that should be installed in v14 to be installed in v17

**Comment by code-asher** [comment] 2024-07-11 23:52
Closing this out due to age, and permission issues do not seem to be something we can fix in code-server, the permission issue just has to be resolved.  If it is still a problem maybe changing the data directory to somewhere Termux can write will help?

**Closed by code-asher** 2024-07-11 23:52 UTC
