### ISSUE TITLE
[Bug]: The terminal cannot display normally with `"terminal.integrated.gpuAcceleration": "on"` (the default setting)

### ISSUE THREAD

**Issue by xiebiao360** [coder/code-server#6027] opened 2023-02-19 15:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari, Chrome
- Local OS: IPadOS15.6.1
- Remote OS: Ubuntu22.04
- Remote Architecture: amd64
- `code-server --version`:4.9.1

### Steps to Reproduce

Open Code-Server terminal on Safari and Chrome on iPad

### Expected

The terminal can display normally, the cursor can display, and the input characters can be seen. When the Enter key is pressed, the command can be executed

### Actual

1. Open it on the PC browser, the terminal displays normally, and the input command can be seen
2. But open it on Safari and Chrome on iPad, the terminal display is abnormal, the input character cannot be seen, and the cursor cannot be displayed

### Screenshot/Video

![微信图片_20230219231853](https://user-images.githubusercontent.com/26644068/219958186-194b3807-ab2d-4c9a-b236-02c99306889c.jpg)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by benz0li** [comment] 2023-02-22 07:31
@xiebiao360 Please try the workaround described at https://github.com/coder/code-server/pull/6004#issuecomment-1424455048:

> Workaround: `"terminal.integrated.gpuAcceleration": "off"`

**Comment by bpmct** [comment] 2023-08-14 23:36
We have some [Coder](https://github.com/coder/coder) users who are reporting this that are unlikely to be on an iPad, most likely a Windows client. They are seeing lag or missing characters until they turn terminal acceleration off. We'll look into the root cause for this!

**Comment by Kira-Pilot** [comment] 2024-07-01 18:31
Closing as this is really old - @bpmct if this is still a problem, please feel free to reopen.

**Closed by Kira-Pilot** 2024-07-01 18:31 UTC
Labels: bug, triage
