### ISSUE TITLE
[Bug]: Firefox not showing Jupyter file

### ISSUE THREAD

**Issue by Emporea** [coder/code-server#5334] opened 2022-07-12 18:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox 102
- Local OS: Win10
- Remote OS: Ubuntu Focal
- Remote Architecture: 86
- `code-server --version`: 4.5.0 (About shows 4.4.0)

### Steps to Reproduce

1. Setup new docker instance
2. Create test.ipynb file (doesnt matter if vscode-jupyter is installed or not)
3. Open file with Firefox

### Expected

Should show cells and Html Rendering

### Actual

Endless Loading

### Logs
Firefox Console (other browsers do not show this)
```

Uncaught (in promise) Error: Unable to write file 'vscode-log:/20220712T210007/window.log' (Error: IndexedDB database 'vscode-web-db' is closed.)
    h https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:9
    L https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:593
    writeFile https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:597
    _log https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:598
    consume https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:71
    queue https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:71
    queue https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:71
    _log https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:597
    error https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:597
    error https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:597
    _log https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:597
    error https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:597
    handleUnexpectedError https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:3072
    registerErrorHandler https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:3072
    onUnexpectedError https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:8
    R https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:8
    registerErrorHandler https://example.tld/stable-30d9c6cd9483b2cc586687151bcbcd635f373630/static/out/vs/workbench/workbench.web.main.js:3072
3 errors.ts:235
This page uses the non standard property “zoom”. Consider using calc() in the relevant property values, or using “transform” along with “transform-origin: 0 0”. example.tld
The web worker extension host is started in a same-origin iframe! webWorkerExtensionHost.ts:111:11
 INFO [Service Worker] registered log.ts:301:11
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. example.tld
The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it. webWorkerExtensionHostIframe.html
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. example.tld

```

### Screenshot/Video

Firefox ( also tested with new installation / different machine / vm etc.):
![Screenshot 2022-07-12 204315](https://user-images.githubusercontent.com/21969523/178570484-03fdc96f-2d9d-42b8-8e9c-ab91563dca53.png)

Other Browsers I tested (Opera, Chrome, Vivaldi, in this screenshot Edge)
![Screenshot 2022-07-12 204122](https://user-images.githubusercontent.com/21969523/178570667-e036e472-03a1-4862-8662-d945d719355a.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by mathematicalmichael** [comment] 2022-07-12 20:36
yeah this is happening with `4.5.0` but not `4.4.0`. I just tried both side-by-side with fresh docker-based installs. 
for what it's worth the `4.5.0` version also carries with it newer versions of the Jupyter extension. I tried downgrading to `v2022.3.1000901801` with `4.5.0` but it didn't fix the problem. The Terminal also didn't work with `4.5.0`.

**Comment by Emporea** [comment] 2022-07-12 21:11
Can confirm that this bug doesn't occur on 4.4.0

**Comment by jsjoeio** [comment] 2022-07-18 22:15
Is this a duplicate of https://github.com/coder/code-server/issues/5335? Or are they somehow related?

**Comment by Emporea** [comment] 2022-07-18 22:44
@jsjoeio 
I don't know how they are related (atleast they share downgrading to 4.4.0 as a workaround), but this is definitly not a duplicate.

**Comment by jsjoeio** [comment] 2022-07-18 22:55
Ah got it. Okay We'll investigate!

**Comment by mathematicalmichael** [comment] 2022-07-20 03:23
@Emporea for me it is impacting all browsers I have installed.
@jsjoeio thank you very much for investigating! `4.4.0` is the first version where Jupyter notebooks actually work and it makes me so happy to finally be able to use code-server exclusively for my work.

**Comment by benz0li** [comment] 2022-07-20 06:33
> Is this a duplicate of #5335?

No.

> Or are they somehow related?

No, they are not.

**Comment by jsjoeio** [comment] 2022-07-20 16:19
@mathematicalmichael hooray! that's great to hear.

We really need to add some e2e tests for Jupyter. I'm going to add this to the next sprint.

**Comment by benz0li** [comment] 2022-07-21 08:20
FYI `code-server` `4.5.1` is working fine with `ms-toolsai.jupyter@2022.5.1001610507` and `ms-python.python@2022.10.1`.

**Comment by benz0li** [comment] 2022-07-21 08:28
@Emporea @mathematicalmichael Please test again with `code-server` `4.5.1`.

Most probably related to https://github.com/coder/code-server/issues/5321.

**Comment by jsjoeio** [comment] 2022-07-21 16:19
Hooray! Thank you @benz0li for testing and confirming!

**Comment by Emporea** [comment] 2022-07-21 16:30
Its working with 4.5.1. Thanks.

**Comment by Emporea** [comment] 2022-07-21 16:35
Wait. Its not. huh.. It opened one time, but had the same bug after that again.

**Comment by benz0li** [comment] 2022-07-21 16:41
@Emporea Use Firefox to log into https://demo.jupyter.b-data.ch.

If it does not work, it might be a problem with your Firefox settings or extensions.

**Comment by Emporea** [comment] 2022-07-21 16:53
I removed the docker container and recreated it and now its working so far. I hope it stays that way, cause i did that already several times, so it seems inconsistent for me. But thanks for solving it in theory.

**Comment by benz0li** [comment] 2022-07-21 16:56
> But thanks for solving it in theory.

It runs just smoothly [also in practice] at https://demo.jupyter.b-data.ch 😉.

**Comment by Emporea** [comment] 2022-07-21 17:11
Sometimes its working. Sometimes not.
With 4.4.0 its working everytime.

**Comment by jsjoeio** [comment] 2022-07-21 17:40
> Use Firefox to log into https://demo.jupyter.b-data.ch/.

@Emporea are you seeing the same results here?

**Comment by Emporea** [comment] 2022-07-21 18:01
The demo is also not working.

**Comment by benz0li** [comment] 2022-07-21 18:02
> The demo is also not working.

@Emporea It is a problem with your Firefox settings or extensions, then.

**Comment by Emporea** [comment] 2022-07-21 18:02
Whatever. The inconsistency makes it super hard to understand and to describe. You probably think i am a noob.
Well I stay on 4.4.0 for a while and see if the inconsistencies also occur there.

**Comment by benz0li** [comment] 2022-07-22 06:40
See also https://github.com/coder/code-server/issues/4777#issuecomment-1023511535 about private/incognito mode [and possibly opening a folder (File > Open Folder...) before opening a Jupyter notebook].

**Comment by jsjoeio** [comment] 2022-07-22 17:15
@Emporea not a noob! Just trying to help. Any other information you can share is helpful, otherwise I will try reproducing

**Comment by mathematicalmichael** [comment] 2022-07-22 17:56
I have a containerized environment that launches in the cloud (free) via binder here: https://mybinder.org/v2/gh/ml-starter-packs/microservice-workshop/main?urlpath=vscode/ ([Dockerfile](https://github.com/ml-starter-packs/microservice-workshop/blob/main/Dockerfile)). 

latest commit pins codeserver to 4.5.1, and I found 
- [ ] terminal functioning as expected
- [ ] notebooks working

**Comment by mathematicalmichael** [comment] 2022-07-22 18:07
hm... unfortunately I got a weird error trying to even install extensions in the first place 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/40366263/180498073-e2fe4016-d865-4215-ba75-88e6bcf50249.png">

don't know if it's related... but I tried `4.4.0` yesterday and it was fine. I'll try rolling back the commit and seeing if the behavior occurs again (is it MS-extensions related or code-server related?)

**Comment by jsjoeio** [comment] 2022-07-22 18:09
<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/180498396-e10982c7-a0a1-4c90-bc1e-0e3a8c977be4.png">

Weird, I'm seeing the same 🤔 open-vsx was down yesterday. maybe related? 

Yeah, when i search for any extension i see the same error:

<img width="372" alt="image" src="https://user-images.githubusercontent.com/3806031/180498473-78adc44d-719e-474f-acb8-8795299f996d.png">

Looking at the network requests, it appears to be returning a 503

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/180498599-1dcf8b7f-9436-47b2-b541-e75f280d12f4.png">

**Comment by mathematicalmichael** [comment] 2022-07-22 18:11
oh okay, so not related to `code-server`?


sidenote: i love that you can reproduce the errors on your own thanks to binder... what an age we live in.

thank you so much for looking into it!

**Comment by jsjoeio** [comment] 2022-07-22 19:00
> oh okay, so not related to code-server?

correct! @benz0li opened an issue upstream: https://github.com/eclipse/openvsx/issues/497

> sidenote: i love that you can reproduce the errors on your own thanks to binder... what an age we live in.

right?! crazy! though props to you for giving me the binder link to be able to reproduce so easily 🙌🏼

**Comment by Emporea** [comment] 2022-07-22 19:15
4.5.1 still only works occasionally regarding the "jupyterlab notebook not rendering"
4.4.0 works everytime.

It cant be my firefox alone.

**Comment by jsjoeio** [comment] 2022-07-22 20:27
I'm on 4.5.1 on macOS and I cannot reproduce 😢

## Screenshot

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/180550137-b362c894-82b7-4fc1-9222-a2f3dea0f133.png">

## Related

This looks like the exact same issue upstream, right? 

https://github.com/microsoft/vscode/issues/132102

Maybe worth dropping a comment on that.

**Comment by mathematicalmichael** [comment] 2022-08-12 23:07
regarding the 503... i think this was a temporary microsoft server thing, because it came back up later that day iirc.
so is this issue closable now? are any problems persisting? (i haven't noticed anything but I've been using chrome to be safe lately with the code-server app so I wouldn't have noticed it on firefox).

**Comment by Emporea** [comment] 2022-08-13 00:43
The problem still persists for me. 4.4.0 has no issue in loading jupyter files. >4.4.0 (for examples latest) doesn't load, or only very occasionally.
So I am using 4.4.0 since.
I wont say its definitly an issue with code-server. Maybe its a vscode or jupyter extension bug, but it began to occur after 4.4.0 as stated enough for now.

**Comment by Emporea** [comment] 2022-08-13 01:37
Please test for yourself.
[4.4.0.emporea.net](url)
[4.5.1.emporea.net](url)

Password: coder

**Comment by benz0li** [comment] 2022-08-13 07:45
> Please test for yourself and tell me if you have the same problem. (firefox)

Initially, I had the same problem with your deployment.

Then I cleared all history

<img width="373" alt="clear-all-history" src="https://user-images.githubusercontent.com/20233085/184474239-e009fd85-d44f-4150-ab6f-a06069a24fff.png">

and never had the problem again:

<img width="1280" alt="Firefox" src="https://user-images.githubusercontent.com/20233085/184474353-5f83c3fc-47d1-411d-b9e8-c2fc875a5060.png">

**Comment by Emporea** [comment] 2022-08-13 11:25
Thanks for testing.

---

> 4.4.0 (for examples latest) on the other hand doesn't load, or only very occasionally.

Once its working (for example after history cleanup) the file will also load on tab reloads, that's apparently true.

But close test.ipynb and load it again, and it will fail to load again. (test it please)

**Comment by benz0li** [comment] 2022-08-13 11:33
> But close test.ipynb and open it up, and it will fail to load once again. (test it please)

Only the first time. When I close it [while it fails loading] and open it again it loads properly.

**Comment by Emporea** [comment] 2022-08-13 11:36
Okey. Well I am not able to test under MacOS. I tested several Linux Distros and Windows. Might be working on MacOS, seems to be a weird bug anyway cause every other Browser than Firefox is doing a proper job at loading it.

**Comment by benz0li** [comment] 2022-08-13 11:39
@Emporea I have tested with your deployment at https://4.5.1.emporea.net/

**Comment by jsjoeio** [comment] 2022-08-17 17:27
> yeah verify should be first priority and make sure it does not happen in codespaces
i think if we discover this is caused by a bug we wrote then we should write an e2e test otherwise hold off for now

This is our plan for this issue.

**Comment by jsjoeio** [comment] 2022-08-18 16:30
## Cannot reproduce bug with latest version

I tested this today and it worked as expected.

### Steps to Reproduce
1. download latest code-server - [v4.6.0-rc.1](https://github.com/coder/code-server/releases/tag/v4.6.0-rc.1)
2. run code-server and open in Firefox
3. Install Python/Jupyter extensions 
4. Open Jupyter file

### Expected

It shows the Jupyter file and runs code.

### Actual 

It shows the Jupyter file and runs code.

### Screenshot

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/185446715-a558d14c-a185-448b-be47-3c4b439600e1.png">

Since VS Code (assumingely) tests this on their own, we decided not to add an e2e test for now. If we find out one of our patches introduces a bug or something breaks in the future, we will revisit adding a test.

Closing this for now.

**Closed by jsjoeio** 2022-08-18 16:30 UTC
Labels: needs-investigation

**Comment by H4Njx** [comment] 2023-06-14 01:40
> > But thanks for solving it in theory.
> 
> It runs just smoothly [also in practice] at https://demo.jupyter.b-data.ch 😉.

how can i get the Dockerfile about the image registry.gitlab.b-data.ch/jupyterlab/python/base, another way , how  put the code-server in jupyterlab, can you give me some help or url about this ? thank you

**Comment by benz0li** [comment] 2023-06-14 03:13
@H4Njx My JupyterLab Python docker stack is publicly available.

Repository: https://github.com/b-data/jupyterlab-python-docker-stack:

Usage > Build image:

```bash
cd base && docker build \
  --build-arg PYTHON_VERSION=3.11.4 \
  -t jupyterlab/python/base \
  -f latest.Dockerfile .
```

`latest.Dockerfile`: https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/base/latest.Dockerfile  
👉 Have a look at the [conf](https://github.com/b-data/jupyterlab-python-docker-stack/tree/main/base/conf) files and [scripts](https://github.com/b-data/jupyterlab-python-docker-stack/tree/main/base/scripts/usr/local/bin), too. Some are essential to make it all work together.

---

Other JupyterLab docker stacks (which also include Python v3.11.4):

* Julia: https://github.com/b-data/jupyterlab-julia-docker-stack
* R: https://github.com/b-data/jupyterlab-r-docker-stack

---

ℹ️ [Dev Containers](https://containers.dev) for use with [Codespaces](https://github.com/features/codespaces) are a work in progress and will be available soon.

**Comment by H4Njx** [comment] 2023-06-14 04:33
> @H4Njx My JupyterLab Python docker stack is publicly available.
> 
> Repository: https://github.com/b-data/jupyterlab-python-docker-stack:
> 
> Usage > Build image:
> 
> ```shell
> cd base && docker build \
>   --build-arg PYTHON_VERSION=3.11.4 \
>   -t jupyterlab/python/base \
>   -f latest.Dockerfile .
> ```
> 
> `latest.Dockerfile`: https://github.com/b-data/jupyterlab-python-docker-stack/blob/main/base/latest.Dockerfile 👉 Have a look at the [conf](https://github.com/b-data/jupyterlab-python-docker-stack/tree/main/base/conf) files and [scripts](https://github.com/b-data/jupyterlab-python-docker-stack/tree/main/base/scripts/usr/local/bin), too. Some are essential to make it all work together.
> 
> Other JupyterLab docker stacks (which also include Python v3.11.4):
> 
> * Julia: https://github.com/b-data/jupyterlab-julia-docker-stack
> * R: https://github.com/b-data/jupyterlab-r-docker-stack
> 
> ℹ️ [Dev Containers](https://containers.dev) for use with [Codespaces](https://github.com/features/codespaces) are a work in progress and will be available soon.

thank you so much.
