### ISSUE TITLE
[Bug]: Java extension not working in 4.0.1, connection broken very often

### ISSUE THREAD

**Issue by steeeffen** [coder/code-server#4779] opened 2022-01-21 16:45 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

```markdown
- Web Browser: Chrome 97.0.4692.99
- Local OS: Mac OS 12.0.1, Chrome OS 97.x
- Remote OS: Ubuntu 20.04 LTS
- Remote Architecture: Hyperviser Proxmox, LXC
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc
```

### Expected

Java plugin should start/work. This is a vanilla installation but upgrading an existing (working) installation (3.11) does not work either afterwards.

I'm getting the dialog "Cannot reconnect. Please reload the window" after a short time (ca. 30-45s) as well. After reconnecting, the dialog comes up again after some time and so forth.

### Actual

Just nothing, footer shows "activiting extension" and nothing else happens.

### Logs

[log.txt](https://github.com/coder/code-server/files/7915304/log.txt)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

Does work as a expected under 3.11 and 3.12 (same environment)

**Comment by jsjoeio** [comment] 2022-01-24 20:37
Oops. Looks like our new template is missing reproduction steps. How do I reproduce this?

**Comment by jkcoxson** [comment] 2022-01-26 04:44
I am also running into the issue of the site constantly requiring a window reload. I am able to reproduce this by installing the latest code-server (4.0.1) through the deb package and then access the site through my iPad or my Mac running Safari on the latest version.

**Comment by jkcoxson** [comment] 2022-01-26 04:46
@steeeffen you’ve leaked your password in the log by the way…

**Comment by dr0p** [comment] 2022-01-26 10:06
I am also seeing a lot or disconnect and reconnects. I have not tried 4.0.0.. I am trying to use 4.0.1, but it is reconnecting every minute or so and is basically unusable. I am seeing the following in the stderr log 

```
[Error: EISDIR: illegal operation on a directory, read] {
  errno: -21,
  code: 'EISDIR',
  syscall: 'read'
}
```
and in the stdout log this repeats on every window reload.
```
[12:00:36] [192.168.1.108][9d8a3d6d][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[12:00:40] [192.168.1.108][79f6ab37][ManagementConnection] New connection established.
[12:00:41] [192.168.1.108][8b0420b7][ExtensionHostConnection] New connection established.
[12:00:41] [192.168.1.108][8b0420b7][ExtensionHostConnection] <8833> Launched Extension Host Process.
[12:01:01] [192.168.1.108][8b0420b7][ExtensionHostConnection] The client has reconnected.
[12:01:21] [192.168.1.108][8b0420b7][ExtensionHostConnection] The client has reconnected.
[12:01:41] [192.168.1.108][8b0420b7][ExtensionHostConnection] <8833> Extension Host Process exited with code: 0, signal: null.
```

----
I have tried resetting code-server's settings by deleting the ~/.local/shared/code-server folter, but this did not help.

**Comment by steeeffen** [comment] 2022-01-26 18:44
@jkcoxson: to reproduce, just install a fresh (vanilla) code-server, a jdk11 and use the java extension from the marketplace (the bundle one from MS). Click on "new project" -> nothing will happen. 

BTW: Password is not leaked, is replaced with a dummy one in the logs (and not a public server anyway) but thx for the hint.

**Comment by jsjoeio** [comment] 2022-01-26 21:29
> use the java extension from the marketplace (the bundle one from MS). Click on "new project" -> nothing will happen.

I can't use the one from MS for legal reasons but I am using the built-in one. Where do I go to hit "new project"?

![image](https://user-images.githubusercontent.com/3806031/151250063-ada0316f-d0da-4c58-8b23-8f101ccdf07e.png)

**Comment by jkcoxson** [comment] 2022-01-26 21:35
Should I create a new issue for the constant reloading prompts? My issue is independent of any particular language or extension.

**Comment by jsjoeio** [comment] 2022-01-27 21:32
@jkcoxson sure but please check to make sure there isn't an existing one first!

**Comment by steeeffen** [comment] 2022-01-28 18:24
@jsjoeio See attached screenshot. Take this from the open marketplace. Once installed, you get the "create project"...
![vscode_java](https://user-images.githubusercontent.com/30724471/151601102-aa65e1d2-3169-4a2e-bffb-1e4efc9322d2.png)

**Comment by jsjoeio** [comment] 2022-01-31 20:22
Just what I needed. Thank you! I will look into this.

**Comment by code-asher** [comment] 2024-07-11 23:55
Closing because of age, and because this appears to be an extension issue.

If it is still a problem, we should try to reproduce in Codespaces and perhaps report it to the extension author.

**Closed by code-asher** 2024-07-11 23:55 UTC
