### ISSUE TITLE
Profiles and portability

### ISSUE THREAD

**Issue by SonahtQ** [coder/code-server#6922] opened 2024-01-27 18:32 UTC
I am writing to propose an enhancement for code-server. I've noticed that user profiles in code-server are saved in the browser's localStorage. This approach limits the profiles accessibility across different devices.

Given that code-server is essentially a server-based implementation of VSCode, it would be immensely beneficial to have profiles stored on the server side. This change would allow users to retain their profiles regardless of the device or browser they are using to access code-server.

To elaborate, when a user configures a profile and adjusts settings in settings.json on one device, these changes are not reflected when the same user accesses code-server from a different machine, because each device currently has his own, separated profile list.

Thank you for considering this request. I am looking forward to any updates regarding this potential enhancement.

Best regards,

**Comment by code-asher** [comment] 2024-07-26 18:20
Duplicate of https://github.com/coder/code-server/issues/4212.

I agree with the idea, and I remember trying to patch VS Code to store state in the remote but ran into some issues.  I will go ahead and close this as a duplicate and re-open the other.  I do not think we have plans to work on this but a PR is welcome.  Possibly implementation could be done as an extension, which would be even better (fewer patches to maintain).

**Closed by code-asher** 2024-07-26 18:20 UTC
Labels: enhancement, feature
