### ISSUE TITLE
[Bug]: iPadOS Mouse Cursor (Safari)

### ISSUE THREAD

**Issue by MitchellPT** [coder/code-server#5196] opened 2022-05-11 17:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: iPadOS 15.4.1
- Remote OS: Ubuntu 21.94
- Remote Architecture: Linux
- `code-server --version`: v4.4.0

### Steps to Reproduce

1. Connect a mouse on iPad OS
2. Hover over text

### Expected

Show the thin cursor

### Actual

shows the circle cursor

### Screenshot/Video

https://user-images.githubusercontent.com/24734120/167912820-ec21ebca-951b-4534-a030-6a0eb1573af5.mp4

https://user-images.githubusercontent.com/24734120/167912927-43f987ad-89bf-4b81-9169-905abfd41f91.mp4

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

It works fine in chrome so i am not sure whether this issue is related to the OS or Code-Server

Apologies if this is a Apple thing

**Comment by MitchellPT** [comment] 2022-05-11 17:44
(Video 2 also showed a bug in chrome web browser where you are unable to select text <- This works in safari

**Comment by jsjoeio** [comment] 2022-05-11 21:51
Can you reproduce this on vscode.dev?

**Comment by MitchellPT** [comment] 2022-05-11 22:08
> Can you reproduce this on vscode.dev?

It works perfectly on vscode.dev. Both chrome and safari cursor shows correctly and allows text selection.

**Comment by code-asher** [comment] 2024-07-12 23:57
Does this reproduce in Codespaces?  That one is closer to code-server than vscode.dev.  Always possible it is a problem in code-server but it does seem likely to be an upstream issue, since I think we are not patching anything here.  Or maybe it was fixed upstream and we were a version behind.

**Comment by code-asher** [comment] 2024-09-19 21:34
Closing for now but let me know if you come back to this and if it can be reproduced in Codespaces.  I know there are a few iPad issues currently going on upstream in the VS Code repository and this might be one of them.

**Closed by code-asher** 2024-09-19 21:34 UTC
Labels: bug
