### ISSUE TITLE
[Bug]: Tar Archives for releases contain broken symlinks

### ISSUE THREAD

**Issue by davellas** [coder/code-server#6139] opened 2023-04-11 11:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

Not-relevant

### Steps to Reproduce

1. download any release e.g.   [code-server-4.11.0-linux-amd64.tar.gz](https://github.com/coder/code-server/releases/download/v4.11.0/code-server-4.11.0-linux-amd64.tar.gz) 
2. folder /lib/vscode/extensions/node_modules/.bin contains broken links pointing to /lib/vscode/extensions/node_modules/typescript/bin that is not existing

### Expected

The tar archives shouldn't contain broken symlinks as that can break certain archiving tools. 
Manually untarring the file will work, but not all similar tools will.

### Actual

The tar archives contain broken symlinks resulting in errors when extracting the archive with certain tools

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment] 2023-04-11 20:41
Ah yeah for some reason VS Code leaves broken symlinks.  We remove them before publishing the deb and rpm but not for the tars.  We should move that line so it applies to all the release types.

https://github.com/coder/code-server/blob/aed1fc0119b57e3141542c76285617ac88d1901e/ci/build/build-packages.sh#L56

**Comment by code-asher** [comment] 2024-07-12 01:14
Duplicate of https://github.com/coder/code-server/issues/5157

**Closed by code-asher** 2024-07-12 01:14 UTC
Labels: bug, triage
