### ISSUE TITLE
settings.json seems not functioning as expected

### ISSUE THREAD

**Issue by OliverwengFiltered** [coder/code-server#4263] opened 2021-09-28 14:04 UTC
## OS/Web Information

- Web Browser: Chrome latest
- Local OS: 
- Remote OS: GCP Ubuntu 20.04
- Remote Architecture:
- `code-server --version`: 3.12.0

## Steps to Reproduce

1. use gcp compute engine unbuntu image to spin up the vm machine.
2. install latest 3.12.0
3.  put the below content at `/home/xxx/.local/share/code-server/User/settings.json`
```
{
    "workbench.colorTheme": "Monokai",
    "terminal.integrated.shell.linux": "/bin/bash",
    "workbench.startupEditor": "readme",
    "terminal.integrated.defaultProfile.linux": "bash"
}

```

## Expected

the welcome page should not show up when the folder has the read me.

## Actual

the welcome page showed up regardless of the `"workbench.startupEditor": "readme"`

**Comment by jsjoeio** [comment] 2021-09-28 19:44
I just tested and it works as expected.

- Open a Folder without readme -> shows Welcome
- Open a Folder with a readme -> shows readme

![image](https://user-images.githubusercontent.com/3806031/135155142-5aa8243a-01b8-488a-a987-2a94c235f085.png)

Are there any logs in the browser?

**Comment by OliverwengFiltered** [comment] 2021-09-29 17:23
It's still reproducible on my end.

here is the screen shots.

![Screen Shot 2021-09-29 at 1 23 34 PM](https://user-images.githubusercontent.com/28814939/135318399-69f3baa2-0292-497f-89eb-78862c49d5e1.png)
![Screen Shot 2021-09-29 at 1 20 12 PM](https://user-images.githubusercontent.com/28814939/135318404-fd573993-87a2-4b30-8a44-3ba74dd6bce9.png)

**Comment by jsjoeio** [comment] 2021-09-29 19:00
I don't know if casing is important. Your file is called `README` but I tried with `readme` because that's how you spelled it in `settings.json`. Can you try that?

Also, those service worker errors happen if you're running code-server in an insecure environment (i.e. not using HTTPS).

**Comment by OliverwengFiltered** [comment] 2021-09-29 19:11
to reproduce, I think all you need to do is open it in incog mode.

I think it's reading the setting from browser storage, instead of the server side. (Or maybe it got overriden due to certain timing difference.)

**Comment by jsjoeio** [comment] 2021-09-29 19:25
Okay I just tested in incognito and I cannot reproduce :( I wonder if it's related to you not using a secure environment. Can you please try with code-server running via HTTPS? You can use `code-server --link`

https://user-images.githubusercontent.com/3806031/135335138-cdb187a1-2e41-467e-ae1f-e51eb70e0690.mov

**Comment by OliverwengFiltered** [comment] 2021-09-29 19:34
Hi @jsjoeio ,

I made an example of how to reproduce and sent an email to jjprevite@gmail.com

Let me know if you can reproduce with the link I sent.

**Comment by jsjoeio** [comment] 2021-09-29 19:37
@OliverwengFiltered ahh... do you mind posting here instead? That way, it's all documented in public and others will be able to see it. (that's my personal email and shouldn't be used, I only use it for commits so everything is tied to the same address. joe@coder.com should be used but only if I ask you too)

**Comment by jsjoeio** [comment] 2021-09-29 19:40
@OliverwengFiltered Okay I took a look and I see what you mean but until we resolve other issues, I don't think we can isolate this down. Can you please try using HTTPS and seeing if the issue persists?

Remember, you're telling VS Code to use a `readme` instead of the Welcome page. It renders the `readme` in a webview. Webviews are guaranteed to work properly in insecure environments (i.e. HTTP), which is what you're using. I can't say that's forsure the issue, but unfortunately, you need to test and see if that resolves it, otherwise I won't be able to help!

**Comment by OliverwengFiltered** [comment] 2021-09-29 19:51
@jsjoeio ,

I'm sorry for the email thing.

Back to the topic: I have a proxy on my local and it's https enabled, but can still produce the same issue.

and also if I downgrade the version of the code server to previous one, it works fine.

**Comment by OliverwengFiltered** [comment] 2021-09-29 19:53
it almost feels like this issue happens again: https://github.com/cdr/code-server/issues/2274

**Comment by jsjoeio** [comment] 2021-09-29 20:26
> I'm sorry for the email thing.

No worries at all! Happens all the time. Thanks for understanding!

> Back to the topic: I have a proxy on my local and it's https enabled, but can still produce the same issue.

Interesting...so when you use the proxy + https, do the service workers go away?

> and also if I downgrade the version of the code server to previous one, it works fine.

argh. that's no good. Hmm...is there anything else about your setup that might be related? i.e. what does your `config.yaml` look like or what flags are you using with code-server?

I think @code-asher fixed an issue with this in the past. Maybe he has an idea

**Comment by code-asher** [comment] 2021-10-01 20:46
I was not able to replicate on 3.12.0.

What I did:

1. Launch 3.12.0
2. File > Preferences > Settings > search for workbench.startupEditor > set to `readme`
3. Open terminal
4. `mkdir with-readme && without-readme`
5. `echo '#readme' > with-readme/README.md`
6. File > Open > select with-readme
7. Verify readme shows
6. File > Open > select without-readme
8. Verify welcome shows

**Comment by prabushi** [comment] 2021-11-11 08:37
I'm facing a similar issue.
```
code-server: v3.12.0
VS Code: v1.60.0
Commit: 4cd55f94c0a72f05c18cea070e10b969996614d2
Date: 2021-09-15T19:34:37Z (1 mo ago)
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36
```
Have the following in **User/setting.json**
```
{
    "workbench.startupEditor": "none"
}
```
It goes to the **Getting Started walkthrough** page at the start if I try the code-server on an incognito window.
<img width="1680" alt="Screenshot 2021-11-11 at 13 46 21" src="https://user-images.githubusercontent.com/5234623/141263501-21fea734-0b5b-45ab-91cd-9315a110e1f7.png">
However, once I **Mark Done** on this walkthrough page and reload the window, VS Code behaves according to the defined settings in the current incognito view.
If I close the incognito windows and open a new incognito window, I get the **Getting Started walkthrough** page again. (Suppose the code-server uses browser storage to preserve states)

Could you please let me know if there's a way to skip this Getting Started walkthrough page at the start?

**Comment by jsjoeio** [comment] 2021-11-12 17:14
> User/setting.json

Looks like you have a typo -> should be `settings.json`. Does that fix it?

Otherwise, @code-asher just fixed this in our e2e test suite with that same setting and it worked. See [here](https://github.com/cdr/code-server/pull/4414/files#diff-919759731061eddd8522c53c0651f7328e5030d138e0c0e1005936f33aaf53e7R57-R59). There could be something else at play

**Comment by prabushi** [comment] 2021-11-13 02:38
Thanks for the reply.
> Looks like you have a typo -> should be `settings.json`. Does that fix it?

My bad, it's settings.json.
> 
> Otherwise, @code-asher just fixed this in our e2e test suite with that same setting and it worked. See [here](https://github.com/cdr/code-server/pull/4414/files#diff-919759731061eddd8522c53c0651f7328e5030d138e0c0e1005936f33aaf53e7R57-R59). There could be something else at play

Will check once the new release is available.

**Comment by jsjoeio** [comment] 2021-11-15 21:24
> Will check once the new release is available.

Sorry, you shouldn't have to wait for a release to check this! We haven't added anything new. I'm saying that he fixed it in an e2e test _meaning_ I know it's currently working as expected

**Comment by prabushi** [comment] 2021-11-30 11:49
> > Will check once the new release is available.
> 
> Sorry, you shouldn't have to wait for a release to check this! We haven't added anything new. I'm saying that he fixed it in an e2e test _meaning_ I know it's currently working as expected

I tried with the [codercom/code-server:latest](https://hub.docker.com/layers/codercom/code-server/latest/images/sha256-af1639721e4b05ba3d818f6b294a81779bbd4a72fbb0f38d1a276c598e5c971f?context=explore) docker image. Still, the behavior is the same.

https://user-images.githubusercontent.com/5234623/144038910-a69d375e-d048-4b32-b9b2-5401dc983ce9.mov

Once I clear the cache, the welcome page pops up for the first time even with the `"workbench.startupEditor": "none"` setting. But, it honors the setting when I reload the window. We are trying to avoid this welcome page popping up for the first time.

I'm not sure if it's the same code-server version that is used in your e2e tests. Is there a way to access the version that is used in your e2e tests environment?

**Comment by jsjoeio** [comment] 2021-11-30 21:07
> Once I clear the cache, the welcome page pops up for the first time even with the "workbench.startupEditor": "none" setting.

Hmm this is very strange 🤔

> I'm not sure if it's the same code-server version that is used in your e2e tests

Our e2e tests use the latest version (which isn't released). It will be 4.0.0 when it comes out.

> Is there a way to access the version that is used in your e2e tests environment?

You could download the `release-packages` artifact from [CI](https://github.com/cdr/code-server/actions/runs/1517687901#artifacts). It will have all the releases (it's a big file). Then you can run locally.

```shell
# download folder
cd release-packages 
# example: macOS
tar -xzf code-server-3.12.0-macos-amd64.tar.gz
./code-server-3.12.0-macos-amd64/ <pass flags here>
```

**Comment by benz0li** [comment] 2021-12-11 12:49
@prabushi https://github.com/cdr/code-server/issues/4263#issuecomment-966093946 (Repeated **Getting Started** walkthrough) has to do with https://github.com/cdr/code-server/issues/4212.

With 'incognito mode'/'private windows' there is no way to skip the **Getting Started** walkthrough page, as this prevents storing browser data.

**Comment by code-asher** [comment] 2021-12-14 19:48
This is an interesting comment: 

https://github.com/microsoft/vscode/blob/25d0e27e292fad4454151b85521014d4c92a3aa7/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts#L53

Looks like there are some conditions in which the welcome page will always show up regardless of `startupEditor`'s value.

**Comment by kfriend** [comment] 2022-02-14 19:52
Per @code-asher's comment, and this line https://github.com/microsoft/vscode/blob/25d0e27e292fad4454151b85521014d4c92a3aa7/src/vs/workbench/contrib/welcome/page/browser/welcomePage.ts#L55, I would assume disabling telemetry would disable the welcome screen even for first-load incognito. Seems to work for me.

```
"telemetry.enableTelemetry": false
```

**Comment by code-asher** [comment] 2024-03-12 19:31
Closing since I think this is working as intended at the moment.  But let me know if I missed something.

**Closed by code-asher** 2024-03-12 19:31 UTC
Labels: waiting-for-info
