### ISSUE TITLE
[Bug]: Terminal not working

### ISSUE THREAD

**Issue by filipton** [coder/code-server#5218] opened 2022-05-22 20:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Arch Linux
- Remote OS: Ubuntu
- Remote Architecture: aarch64
- `code-server --version`: 4.4.0

### Steps to Reproduce

1. open code-server
2. open new termina

### Expected

Terminal window should open.

### Actual

Terminal window is blank.

### Logs

[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/usr/bin/bash" and args undefined

...

[22:22:15] Terminal process launching on remote agent {
  shellLaunchConfig: {
    name: undefined,
    executable: '/usr/bin/bash',
    args: undefined,
    cwd: '/root/sandbox/StatusPage',
    env: undefined,
    useShellEnvironment: true
  },

### Screenshot/Video

![image](https://user-images.githubusercontent.com/37213766/169714453-a9298fab-b48e-4432-a6c0-9250a024aa5b.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

### Notes

I tried to reinstall code-server, and even I ran the docker version from linuxservers with the same results. It's weird because 2 days ago it was working, and I didn't update anything on that server.

**Comment by jsjoeio** [comment] 2022-05-23 18:39
Do you have bash installed?

I've seen this happen when I don't have zsh installed. You can also change the default shell in the VS Code Settings UI. I would try that.

**Comment by exosiscrypto** [comment] 2022-05-29 06:59
I confirm this issue, after updating to 4.4.0 terminal is not working

**Comment by filipton** [comment] 2022-05-29 07:02
> Do you have bash installed?
> 
> I've seen this happen when I don't have zsh installed. You can also change the default shell in the VS Code Settings UI. I would try that.

It was working before update, but yup i have bash installed.

**Comment by ljishen** [comment] 2022-06-11 23:55
I have the same issue after updating to 4.4.0

**Comment by Steveorevo** [comment] 2022-06-12 17:53
New installation 4.4.0, Ubuntu 20.04 on arm64, 

[IPC Library: Pty Host]  WARN Shell integration cannot be enabled for executable "/bin/bash" and args []

**Comment by jsjoeio** [comment] 2022-06-13 14:52
> It appears that my issue appears with code-server is run from a chroot/jailkit account. Seems to work fine on a regular user; non-root account on Ubuntu. Wondering if it's a missing dependency issue of something simply not copied over to the jailed account.

@code-asher any ideas?

**Comment by Steveorevo** [comment] 2022-06-14 00:09
I found out that you can mount your /dev and /dev/pts folders to your jailkit account and it works. I.e.

mount -o bind /dev /[your jailkit root]/dev
mount -t devpts devpts /[your jailkit root]/dev/pts 

However, this mounts everything in your root /dev to the jailkit and may defeat the purpose of jailkit altogether; to provide isolation. Other forums have indicated that /dev/pts is the only device necessary and doesn't pose a "big risk" as each device has it's own owner/group; but I couldn't get it to work with just that. I'm wondering what else is actually needed and is a dependency? I don't want to give full access to items like /dev/mem (memory) to a jailkit'd user.

**Comment by code-asher** [comment] 2022-06-14 18:39
Does anything in this issue help? https://github.com/microsoft/vscode-remote-release/issues/4233

At first glance seems like `/dev/ptmx` and `/dev/pts` should do it.

**Comment by bcotton** [comment] 2022-06-29 20:00
Can confirm. Running code-server on OSX, with a vanilla docker-code-server, running on Docker locally. 

No terminal start, nothing in any of the logs that I could find. 

Downgrading to 4.3.0 seems to fix it

**Comment by bcotton** [comment] 2022-06-29 22:08
> @bcotton nothing in the browser logs either?

Nope, I checked the "window" logs. Tailed all logs in the running image, in addition to the output of coder command line. 

is there somewhere else to check?

**Comment by bcotton** [comment] 2022-06-30 18:21
> wait are you using code-server or `coder`?

I'm using `coder` to start `code-server` in a docker container.

**Comment by jsjoeio** [comment] 2022-06-30 18:37
@bcotton oh! thanks for clarifying. That sounds specific to `coder` then. Do you mind opening an [issue](https://github.com/coder/coder) there with steps to reproduce it? Sorry for the confusion!

**Comment by enkeys** [comment] 2022-07-15 14:33
@jsjoeio I had the same issue today after upgrade code-server from 4.4.0 to 4.5.0 and I don't use 'coder'.

The background steps for the upgrade:

1. Using code-server 4.40 ssh forward with chrome + safari on client side
2. Install script upgrade failed on rpm 
3. Manually run `rpm -U --replacefiles --replacepkgs  ~/.cache/code-server/code-server-4.5.0-amd64.rpm`

I could open more terminals, but I didn't see the content and titles of the terminals and otherwise exactly as the description/screenshot.  

Likewise, I think it was caused by browser some cache or cookies. Because after I returned from a few local errands, the problem magically resolved itself. I had problem on client node with Safari and Chrome, server side RHEL 8.6, logs from the systemd coda-server service are clean, and I can't give you any more information backwards from the browsers, unfortunately.

**Comment by consideRatio** [comment] 2022-07-18 19:58
Using code-server 4.5.0, as started directly via `code-server`, the following occurs when I use `ctrl+shift+p` and then run the command to create a new terminal.

![image](https://user-images.githubusercontent.com/3837114/179605951-a971068f-b660-42e7-88f3-6dd8a0e40512.png)

`code-server` 4.4.0 worked fine without this issue. Note that in case its relevant, using 4.4.0 also resolved #4344 in my case.

I've installed `code-server` in a docker image defined here: https://github.com/pangeo-data/jupyter-earth/blob/master/hub.jupytearth.org-image/Dockerfile.

**Comment by jsjoeio** [comment] 2022-07-18 22:18
I believe this might be a duplicate of https://github.com/coder/code-server/issues/5321

If someone wants to check, here is the PR which fixed it: https://github.com/coder/code-server/pull/5332

**Comment by consideRatio** [comment] 2022-07-18 22:26
@jsjoeio for me, the base path was not `/`, so any fix related to that seems to be relevant!

**Comment by jsjoeio** [comment] 2022-07-18 22:28
I hope we're right then 🤞🏼 Hoping to get [4.5.1](https://github.com/coder/code-server/pull/5354) out soon. Sorry for all the trouble!

**Comment by consideRatio** [comment] 2022-07-18 22:30
@jsjoeio do you think the regression about syntax highlighting (#5343) was resolved by #5332 as well? I could not find a clear error message or similar, but only conclude it didn't properly syntax-highlight as before in for example a .py file.

**Comment by jsjoeio** [comment] 2022-07-18 22:34
@consideRatio I would bet so! CI just finished and now i'm testing 4.5.1 (what we'll publish) locally. I'll run it behind Caddy and check syntax highlighting now. Thanks for mentioning it!

**Comment by jsjoeio** [comment] 2022-07-18 22:38
Everything appears to be working for me!

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/179628931-dc061ce2-4f57-4340-bf2c-37432e32ddd5.png">

**Comment by moqsien** [comment] 2022-10-06 12:54
The same bug occurs on FreeBSD.
Maybe due to that the  '@parcel/watcher' package does not support FreeBSD.

**Comment by jsjoeio** [comment] 2022-10-06 15:00
> Maybe due to that the '@parcel/watcher' package does not support FreeBSD.

Hmm...any ideas for ways we can fix that? Would it be worth raising [upstream](https://github.com/parcel-bundler/watcher/issues?q=is%3Aissue+is%3Aopen+freebsd)?

**Comment by moqsien** [comment] 2022-10-07 03:17
> > Maybe due to that the '@parcel/watcher' package does not support FreeBSD.
> 
> Hmm...any ideas for ways we can fix that? Would it be worth raising [upstream](https://github.com/parcel-bundler/watcher/issues?q=is%3Aissue+is%3Aopen+freebsd)?

`[IPC Library: File Watcher] Loading "@parcel/watcher" failed
[IPC Library: File Watcher] Error: /usr/local/lib/node_modules/@parcel/watcher/build/Release/watcher.node: Undefined symbol "_ZTV17BruteForceBackend"
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1189:18)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at load (/usr/local/lib/node_modules/@parcel/watcher/node_modules/node-gyp-build/index.js:22:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/@parcel/watcher/index.js:1:42)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at r (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:101)
    at e.load (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1720)
    at e.load (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:11005)
    at a (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10302)
    at Object.errorback (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10423)
    at e.triggerErrorback (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:11369)
    at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:11075
    at e.load (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1737)
    at e.load (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:11005)
    at a (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10302)
    at o._loadModule (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10432)
    at o._resolve (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:452)
    at o.defineModule (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6144)
    at y (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1825)
    at h (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/files/node/watcher/watcherMain.js:14:21897)
    at Object.<anonymous> (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/platform/files/node/watcher/watcherMain.js:14:33421)
    at e._createAndEvalScript (/usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2598)
    at /usr/local/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2237
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[IPC Library: File Watcher] Here are the modules that depend on it:
[IPC Library: File Watcher]% [ 'vs/platform/files/node/watcher/parcel/parcelWatcher' ]
[11:03:49] [192.168.98.1][1b00a7cd][ExtensionHostConnection] New connection established.
[11:03:49] [192.168.98.1][1b00a7cd][ExtensionHostConnection] <894> Launched Extension Host Process.
File not found: /usr/local/lib/node_modules/code-server/lib/vscode/node_modules/vscode-textmate/release/main.js
File not found: /usr/local/lib/node_modules/code-server/lib/vscode/node_modules/vscode-oniguruma/release/onig.wasm
File not found: /usr/local/lib/node_modules/code-server/lib/vscode/node_modules/vscode-oniguruma/release/main.js
File not found: /usr/local/lib/node_modules/code-server/lib/vscode/node_modules/xterm/lib/xterm.js`

[https://github.com/parcel-bundler/watcher](@parcel/watcher)

I have no idea how to fix it by now. Maybe raising upstream is viable.
Otherwise, just disable the terminal on FreeBSD, or else it may lead to high CPU usage.

**Comment by jsjoeio** [comment] 2022-10-07 16:50
@moqsien do you mind opening an issue upstream and linking here?

**Comment by rob4226** [comment] 2022-10-23 00:53
I'm having same issue on FreeBSD. Terminal does not work. Some languages, like Python, there is no syntax highlighting but JavaScript is highlighted correctly.  The errors from the code-server server on FreeBSD 13.1 and code-server v4.7.1 look like:
```sh
[20:42:29] ptyHost was unable to resolve shell environment Error: Unable to resolve your shell environment: Unexpected exit code from spawned shell (code 1, signal null)
...
[20:45:18] [Unknown channel: Channel name 'ptyHost' timed out after 1000ms]
rejected promise not handled within 1 second: Unknown channel: Channel name 'ptyHost' timed out after 1000ms
```
Also, when installed on FreeBSD via npm, I keep getting missing module errors after starting code-server. I had to keep killing/restarting to install the packages it was asking for until I stopped getting those errors. I ended having to manually install:  `npm i yazl yauzl @microsoft/1ds-core-js vscode-regexpp xterm-headless vscode-proxy-agent`

**Comment by jiegec** [comment] 2023-01-13 08:20
I got watcher working by installing watchman(!) and using @parcel/watcher from pr https://github.com/parcel-bundler/watcher/pull/128.

**Comment by moqsien** [comment] 2023-01-13 08:21
这是来自FoxMail邮箱的假期自动回复邮件。
 
您好，我是Mo-Qsien，最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复！

**Comment by code-asher** [comment] 2024-03-12 19:27
Closing since it looks like the original issue was resolved?  Check https://github.com/coder/code-server/issues/5741 for the FreeBSD issue.

**Closed by code-asher** 2024-03-12 19:27 UTC
Labels: waiting-for-info
