### ISSUE TITLE
[Bug]: Code-Server Version is still 4.4.0 after upgrading to 4.5.0

### ISSUE THREAD

**Issue by balajib-b** [coder/code-server#5316] opened 2022-07-02 01:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Kubuntu 20.04
- Remote OS: Ubuntu 20.04
- Remote Architecture: arm64
- `code-server --version`:4.5.0

### Steps to Reproduce

1. click menu
2. click Help
3. click About

### Expected

version : 4.5.0

### Actual

Version 4.4.0

### Screenshot/Video

![image](https://user-images.githubusercontent.com/64471553/176981494-7a20814e-dbb5-4b67-8c4a-139f27bf2ef3.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by thediveo** [comment] 2022-07-03 14:21
Confirming for arm64 .deb on Ubuntu 21.04 arm64: `systemctl status code-server` shows v4.5.0 in the logs, but even after clearing browser caches the web UI always shows v4.4.0 and the wrong commit hash.

**Comment by AalmanMohd** [comment] 2022-07-03 19:26
Confirmed on Debian for arm64 and amd64 with individual .deb packages as well as using install script.

**Comment by GuillaumeLazar** [comment] 2022-07-06 07:21
Same issue after upgrading from v4.4.0 to v4.5.0 using the `install.sh` script on Ubuntu 22.04 LTS  (arm64).

```shell
$ dpkg -s code-server | grep Version
Version: 4.5.0
```

code-server "About popup" displays:
```shell
code-server
code-server: v4.4.0
Code: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
```

**Comment by LCMilstein** [comment] 2022-07-06 16:55
Same issue trying multiple install approaches, including the GUI in Docker on Synology

**Comment by benz0li** [comment] 2022-07-08 13:50
@jsjoeio Also reproducible at https://vscode-r.jupyter.b-data.ch with image `R (base:test) + code-server` as your account is still whitelisted.

_JupyterLab > Terminal:_

```bash
$ code-server --version
4.5.0 02b9d7ee856e31d9008d1ff24a175ff03b49010e with Code 1.68.1
```

_code-server > Help > About:_

<img width="520" alt="code-server_Help_About" src="https://user-images.githubusercontent.com/20233085/178004765-e620b10e-a1c6-470c-b730-0b761e9c09b6.png">

**Comment by somnisomni** [comment] 2022-07-16 07:19
In released `code-server-4.5.0-linux-amd64.tar.gz/lib/vscode/product.json`, seems like some properties remain as same as v4.4.0 one.

![image](https://user-images.githubusercontent.com/82272900/179344609-d13dd273-ba44-454e-8fa2-4c14f5a73434.png)

**Comment by jsjoeio** [comment] 2022-07-19 16:25
We think this is because CI hit the cache when releasing 4.5.0 so it didn't rebuild leading to this issue.

See https://github.com/coder/code-server/pull/5354/commits/3cd34755404d5b9cb6e403cd311e1b3cab908bd7

**Comment by jsjoeio** [comment] 2022-07-19 18:08
fixed via https://github.com/coder/code-server/commit/3cd34755404d5b9cb6e403cd311e1b3cab908bd7

<img width="1712" alt="version" src="https://user-images.githubusercontent.com/3806031/179819269-126e1ea2-0962-49e2-b2a6-23aafb83007a.png">

This will be updated in the next release.

**Closed by jsjoeio** 2022-07-19 18:08 UTC
Labels: bug, high-priority
