### ISSUE TITLE
[Bug]: Can not public forwarded port

### ISSUE THREAD

**Issue by checho221** [coder/code-server#6459] opened 2023-09-30 18:22 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Android
- Remote OS: Termux
- Remote Architecture: arm64
- `code-server --version`: 4.17.1

### Steps to Reproduce

1.  code-server --auth none --cert
2. open port forwarding tab

### Expected

When configuring a new port forwarding as last docs says it must displays github login and give option to public forwarder port to the internet

https://code.visualstudio.com/docs/editor/port-forwarding

### Actual

It just have normal options and forwards port just locally with no "Port Visibility" options

### Screenshot/Video

![Screenshot_20230930_125546_Samsung Internet](https://github.com/coder/code-server/assets/10603888/dacc0ab1-5775-402d-b960-4d9a681cd3b9)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment] 2024-07-12 22:53
Duplicate of https://github.com/coder/code-server/issues/6008

**Closed by code-asher** 2024-07-12 22:53 UTC
Labels: bug, triage
