### ISSUE TITLE
[Feat]: Allow installing .vsix extensions in restricted environments

### ISSUE THREAD

**Issue by jsjoeio** [coder/code-server#5465] opened 2022-08-16 22:49 UTC
## What is your suggestion?

Allow users to install `.vsix` extensions offline via the CLI.

## Why do you want this feature?

Some community members and customers work in airgapped or offline environments and want to be able to install extensions.

## Are there any workarounds to get this functionality today?

No.

## Are you interested in submitting a PR for this?

Yes

### Related

Technically this is upstream, but I'm considering fixing it first in code-server and then submitting a patch upstream

https://github.com/microsoft/vscode/issues/142812

**Comment by powershot275** [comment] 2022-08-23 13:17
I believe we can already do this by running the following:
```
code-server --install-extension /path/to/my/extension.vsix
```

**Comment by jsjoeio** [comment] 2022-08-23 16:14
You're right  🤔

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/186208451-e80d7563-b599-4d7c-84ca-e7ff757361f9.png">

Weird. I used `--log trace` and don't see anything about it trying to access the internet.

cc @code-asher can you confirm you're seeing the same thing? Maybe this is no longer a thing.

**Comment by code-asher** [comment] 2022-08-24 20:26
Huh yeah it works for me too.  I tried the Python extension which was the one that was hanging for me.

**Comment by jsjoeio** [comment] 2022-08-25 15:33
Hmm...[this person](https://github.com/microsoft/vscode/issues/142812#issuecomment-1226970265) says it's still happening. I may investigate adding an integration test to verify that it does not make any network requests and works offline.

**Comment by cccs-nik** [comment] 2022-08-25 18:23
I'm using a slightly outdated version of code-server (v4.3.0) but I run into the same issue which is that it takes a little over 2 minutes for a single extension to install. I've never had one outright fail to install, it's always just been very slow because of the call to the marketplace that's been added to VS Code sometime ago now.

**Comment by jsjoeio** [comment] 2022-08-25 18:50
@cccs-nik are you in an offline or restricted environment? @code-asher noticed that the behavior is different with the latest version.

**Comment by cccs-nik** [comment] 2022-08-25 18:56
Yeah I'm in a restricted environment. I'll give the latest version a try and get back to you.

**Comment by jsjoeio** [comment] 2022-08-29 16:31
@cccs-nik very helpful - thank you so much! Appreciate your help.

I was chatting with @code-asher - we believe that this only happens in restricted environments. He was doing some poking around to see if we could figure out what the root cause is. Still working on that though.

**Comment by code-asher** [comment] 2022-08-30 17:28
Yeah I am still unclear on how exactly to reproduce.  I have tried going
offline and blocking open-vsx.org via DNS but I think to reproduce we
need DNS to resolve and then for the request not to be blocked but to
not respond at all.  Maybe like a firewall that just drops packets.

**Comment by code-asher** [comment] 2022-08-30 17:30
If there is a firewall just dropping packets then I assume there is a timeout somewhere we can lower although I am not sure what a good timeout is; maybe in some environments it really does take two minutes to resolve.  So if this is what is happening then the ideal fix is likely to make the firewall respond with a denial rather than silently dropping.

**Comment by code-asher** [comment] 2022-10-11 09:16
Yeah I am still unclear on how exactly to reproduce.  I have tried 
going
offline and blocking open-vsx.org via DNS but I think to reproduce 
we
need DNS to resolve and then for the request not to be blocked but 
to
not respond at all.  Maybe like a firewall that just drops 
packets.

**Comment by itaynvn** [comment] 2023-11-30 15:07
@code-asher i've ran tcpdump while starting code server and found the following URL's to be requested:
(i've ran this in a container to make sure nothing else is running or might interrupt the records)

```
DNS	238	Standard query response 0x2814 A openvsxorg.blob.core.windows.net CNAME blob.dub09prdstr08a.store.core.windows.net A 20.60.40.4
DNS	177	Standard query response 0x537d AAAA open-vsx.org SOA dns1.datacentres.rogers.com
```

**Comment by code-asher** [comment] 2024-07-11 23:28
Closing this out for now since it appears to be an upstream issue which while we could patch, would be better fixed upstream, and because I think this can be resolved by blocking requests immediately rather than timing them out, although admittedly I am fuzzy on how this happens.

**Closed by code-asher** 2024-07-11 23:28 UTC
Labels: needs-decision
