### ISSUE TITLE
GitHub login redirect fails due to missing subpath

### ISSUE THREAD

**Issue by Nick-Hopps** [coder/code-server#4107] opened 2021-09-05 18:48 UTC
## OS/Web Information

- Web Browser: Firefox
- Local OS: Windows10
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd64
- `code-server --version`: 3.11.1

## Steps to Reproduce

1. click the link: ![图片](https://user-images.githubusercontent.com/16911282/132138006-70fbbdbd-0c3d-4751-b21d-04ef3caf59f4.png)
2. The page shows 404 not found.
3. Login failed.

## Expected

Login to github without failing.

## Actual

Failed logining into GitHub.

## Notes

This issue can be reproduced in VS Code: No

**Comment by Nick-Hopps** [comment] 2021-09-05 18:50
I'm using code-server under reverse proxy, which is handled by Nginx, My config is:

```
server {
    listen 8080;
    server_name xxx.com;

    location /code-server/ {
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_pass http://10.0.0.1:8000/;
    }
}

```

**Comment by Nick-Hopps** [comment] 2021-09-05 18:53
After investigation, I found that it was the authentication URL which lead to the failing:

https://xxx.com/callback?vscode-requestId=......

It suppose to be:

https://xxx.com/code-server/callback?vscode-requestId=......

Is there any workaroud to deal with such situation? I've tried some but failed.

**Comment by jsjoeio** [comment] 2021-09-07 21:28
For whatever reason, I can't seem to find the "Sign in with GitHub" from GitLens. 

![image](https://user-images.githubusercontent.com/3806031/132412856-3576bda6-8615-44d5-9fc2-ec9d2553e34f.png)

If it's the authentication URL, you should be able to modify it manually:

see https://github.com/cdr/code-server/issues/1883#issuecomment-659836909

Let me know if that works!

**Comment by Nick-Hopps** [comment] 2021-09-08 02:02
For the origin URL:

![image](https://user-images.githubusercontent.com/16911282/132434114-95686f7e-e2c4-4ef4-a5ad-e2e6a9836e94.png)

When adding my subpath "/code-server/" to the host name:

![image](https://user-images.githubusercontent.com/16911282/132434256-f84f331d-0c51-4181-b7d9-f4a319c287c9.png)

**Comment by jsjoeio** [comment] 2021-09-08 20:59
Thanks for the screenshots! 

So I clicked on that, it asked for a PAT, I copied one from https://github.com/settings/tokens and it worked? Can you try that approach instead of the auth URL callback?

![image](https://user-images.githubusercontent.com/3806031/132584651-4af24923-a307-4a0c-9ada-650b2a982dac.png)

![image](https://user-images.githubusercontent.com/3806031/132584744-3380d90c-e027-434a-a643-4e720368187b.png)

**Comment by Nick-Hopps** [comment] 2021-09-09 01:55
Wow, it works for me! Thx very much. If only callback also works, it'd be perfect.

**Comment by jsjoeio** [comment] 2021-09-09 17:31
I'll let @code-asher chime in and see if he is able to reproduce the issue with the callback

**Comment by Nick-Hopps** [comment] 2021-09-10 01:39
waiting for good news 😄

**Comment by code-asher** [comment] 2021-09-10 15:59
Ah yup there is a bug where the redirect URL does not include the
sub-path. It should be a simple fix but I have not had the chance to
look into it.

**Comment by jsjoeio** [comment] 2021-09-10 17:26
No worries! I've changed the title to reflect so and added to On Deck. @Nick-Hopps can't tell you when we'll get to it, but it's on the list and will be in an upcoming milestone in the future!

**Comment by Nick-Hopps** [comment] 2021-09-11 01:37
> No worries! I've changed the title to reflect so and added to On Deck. @Nick-Hopps can't tell you when we'll get to it, but it's on the list and will be in an upcoming milestone in the future!

It's ok and thx again.

**Comment by gmrukwa** [comment] 2021-12-12 13:21
> Thanks for the screenshots!
> 
> So I clicked on that, it asked for a PAT, I copied one from https://github.com/settings/tokens and it worked? Can you try that approach instead of the auth URL callback?
> 
> ![image](https://user-images.githubusercontent.com/3806031/132584651-4af24923-a307-4a0c-9ada-650b2a982dac.png)
> 
> ![image](https://user-images.githubusercontent.com/3806031/132584744-3380d90c-e027-434a-a643-4e720368187b.png)

I am using such an approach, but it asks me for the token each time I do `git pull` or anything else that requires authentication. It just drives me crazy. The answer I suggested [here](https://github.com/cdr/code-server/issues/1883#issuecomment-712595418) and the solution from that thread don't work anymore. Is there any better solution?

I do have a reverse proxy, too. I replace the corresponding part of the URL, but it doesn't help, exactly like in the case of @Nick-Hopps.

**Comment by jsjoeio** [comment] 2021-12-13 17:12
> I am using such an approach, but it asks me for the token each time I do git pull or anything else that requires authentication.

Usually when this happens, I think it means git isn't caching your credentials. Have you tried [this](https://www.freecodecamp.org/news/how-to-fix-git-always-asking-for-user-credentials/)?

**Comment by gmrukwa** [comment] 2021-12-13 17:31
> > I am using such an approach, but it asks me for the token each time I do git pull or anything else that requires authentication.
> 
> Usually when this happens, I think it means git isn't caching your credentials. Have you tried [this](https://www.freecodecamp.org/news/how-to-fix-git-always-asking-for-user-credentials/)?

Thanks, it worked. My bad, didn't check this, just thought it's an issue with the code-server. 🤦🏻

**Comment by jsjoeio** [comment] 2021-12-14 17:15
> My bad, didn't check this, just thought it's an issue with the code-server. 🤦🏻

Happens to all of us once in a while! Glad that's resolved :)

**Comment by twittyc** [comment] 2022-04-22 17:06
Hello, If I can be pointed in the right direction. I don't mind doing the work to fix this bug since it affects me. I'm not sure where the callback is in the code.

**Comment by jsjoeio** [comment] 2022-04-22 20:57
This is our [GitHub auth patch](https://github.com/coder/code-server/blob/main/patches/github-auth.diff) so that's where the code for this should be. That would be a good place to start

**Comment by code-asher** [comment] 2022-04-25 16:12
I think I might have fixed this (I must have forgotten this issue existed).  Is is still present in latest code-server?

**Comment by twittyc** [comment] 2022-04-25 16:18
I cannot complete the OAuth flow for Gitlens+ login (required for their subscription). So I believe so.

**Comment by code-asher** [comment] 2022-04-28 16:14
Ahhh my bad I was thinking about the builtin git extension. 

It looks like GitLens uses `asExternalUri` to generate the redirect URI:
https://github.com/gitkraken/vscode-gitlens/blob/ec6e207eae89c87152cff89d70f415cc82602527/src/plus/subscription/serverConnection.ts#L113-L120

So I bet we need to update `asExternalUri` to include the full path rather than just the host.

**Comment by code-asher** [comment] 2022-10-11 07:22
Is this still a problem in latest code-server?  I thought I fixed this
but I might be mistaken.

https://github.com/coder/code-server/blob/c35bf1311e85d031e40ca42fe0342a47c2c254a8/patches/base-path.diff#L293

**Comment by code-asher** [comment] 2022-10-13 22:51
Six months for this comment that I initially sent through email to arrive.  How strange.  :stuck_out_tongue:

**Comment by Msadat97** [comment] 2022-12-07 09:46
Is there a fix for this? When I use GitLense Sign-in, it redirects me to the GitLense page, but from there, I cannot authorize anything for the code-server. It always opens the local vscode.

![image](https://user-images.githubusercontent.com/71992433/206144652-a0f56ea9-69eb-4e23-ae7c-e1523d471347.png)

The sign-in option in the code-server opens this page instead of the authorization page.

**Comment by jsjoeio** [comment] 2022-12-07 16:13
@Msadat97 what version of code-server are you using? and can you provide repro steps? i can look into it

**Comment by Msadat97** [comment] 2022-12-08 10:10
I am using the latest version (4.9.0) of code-server. To reproduce this, you can go to the sidebar page of the GitLens extension and click on the sign-in option. 

<img width="1904" alt="Screenshot 2022-12-08 at 11 08 32" src="https://user-images.githubusercontent.com/71992433/206419761-60e1ed2a-882d-49c7-95c8-eda37e643dae.png">

Then, it doesn't redirect to the correct page.

**Comment by jsjoeio** [comment] 2022-12-08 16:38
Are there any logs in the browser console? And what page does it redirect to?

**Comment by Msadat97** [comment] 2022-12-09 00:17
It basically does nothing other than opening the page that I sent before: 

![image](https://user-images.githubusercontent.com/71992433/206593388-340cded1-e1c7-463e-a1ee-3af7893683c2.png)

These are the logs that I get, which I think are not relevant.

```
DevTools failed to load source map: Could not load content for chrome-extension://bmnlcjabgnpnenekpadlanbbkooimhnj/browser-polyfill.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://nllcnknpjnininklegdoijpljgdjkijc/bundles/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://nllcnknpjnininklegdoijpljgdjkijc/bundles/writingMonitor.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://nllcnknpjnininklegdoijpljgdjkijc/bundles/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://nllcnknpjnininklegdoijpljgdjkijc/bundles/writingMonitor.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://nllcnknpjnininklegdoijpljgdjkijc/bundles/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
DevTools failed to load source map: Could not load content for chrome-extension://nllcnknpjnininklegdoijpljgdjkijc/bundles/writingMonitor.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by jsjoeio** [comment] 2022-12-12 15:59
I can't find the authorization URL it's looking for either. 

https://user-images.githubusercontent.com/3806031/207092584-35f35699-6a95-4e91-81f4-573bc26bc58f.mov

Can you try raising an issue with GitLens? Seems like it's not giving us the authorization URL to paste into code-server.

**Comment by Msadat97** [comment] 2022-12-20 15:20
Sure. I will mention the issue with the GitLense team.

**Comment by amirhmoradi** [comment] 2023-04-13 13:39
Here is the solution to connect your GitLens Pro account in hosted code-server:
1: Click on the signing link as shown in the screenshot:
<img width="601" alt="signin-gitlens-code-server" src="https://user-images.githubusercontent.com/1281163/231774537-60cfac74-4c7a-4d20-8961-4335bc79d172.png">

2: Allow the usage of GitLens+:
<img width="637" alt="signin-gitlens-code-server-allow" src="https://user-images.githubusercontent.com/1281163/231774591-1dea7a41-4b32-4304-95cc-a61a2fb40f09.png">

3: "Copy" the link:
<img width="654" alt="signin-gitlens-copy-link" src="https://user-images.githubusercontent.com/1281163/231774629-77b77a83-824a-4e51-8b09-055f71eac2ce.png">

4: From the link, extract the `gkstate` value:
example: `b4bbb363-b3e5-4014-efb8-a7a0f9e42135`

5: Replace `GKSTATE_HERE` in the link below with your own `gkstate`:
⚠️  Careful not to touch the `D` before, nor the `%` after the gkstate.

`https://app.gitkraken.com/register?referrer=gitlens&pass-token=true&return-url=vscode%3A%2F%2Feamodio.gitlens%2Fdid-authenticate%3Fgkstate%253DGKSTATE_HERE%2526windowId%253D2`

6: Open the new URL from step 5 in your browser (not in code-server) and connect to your GitLens Pro account, then the page would redirect to a validation page where you must copy the Authorization URL (do not click on Open in VSCode, if the popup is presented to you as this will open the local vscode and not your hosted Code-Server)
<img width="1278" alt="signin-gitlens-copy-authorization-url" src="https://user-images.githubusercontent.com/1281163/231775359-00d00986-9732-49a9-93bf-5de7fec21d32.png">

7: Paste the Authorization URL in the popup in Code-Server:
<img width="764" alt="signin-gitlens-paste-url-and-enter" src="https://user-images.githubusercontent.com/1281163/231775416-11da402a-5b9f-4db4-8c04-b7338a603bc3.png">

8: Voila:
<img width="451" alt="code-server-gitlens-pro-signin" src="https://user-images.githubusercontent.com/1281163/231775496-bf938792-23fb-4476-971b-ec30db45bab2.png">

**Comment by code-asher** [comment] 2024-07-13 00:12
I tried to reproduce the original issue but I am not seeing an option to log into GitHub anywhere in GitLens.

But, I signed into GitKraken without any issues.

**Closed by code-asher** 2024-07-13 00:12 UTC
Labels: bug
