### ISSUE TITLE
Easymotion does not work in the Vim plugin under Code-Server

### ISSUE THREAD

**Issue by konstantint** [coder/code-server#3196] opened 2021-04-23 09:54 UTC
- Web Browser: Chrome
- Local OS: Windows or ChromeOS
- Remote OS: Ubuntu 16.04
- Remote Architecture: x86_64
- `code-server --version`: 3.9.3 fe2dc2deb08e378069891b622bb62ad1d261d1b1

## Steps to Reproduce

1. Install the VSCodeVim extension.
2. Edit settings.json by copying over the [quick example from the VSCodeVim page](https://github.com/VSCodeVim/Vim).
3. Enter the easymotion shortcut (`<space><space>w`)

## Expected

The plug-in should highlight first letters of the various words in the text to jump to. This is what happens if the same sequence of actions is performed on the vanilla VSCode (even with `--extensions-dir=.local/share/code-server/extensions`).

## Actual

The cursor is moved one word forward (as if just `w` was pressed)

## Notes

I do not see any errors in the browser console (and the server-side logs are probably irrelevant is vscodevim is a purely front-end extension). For starters it would be nice to check whether the issue is reproducible by someone else.

This issue can be reproduced in VS Code: No

**Comment by konstantint** [comment] 2021-04-24 14:35
Hm, that's strange.

By now I tried installing code-server in three different servers (2x Ubungu, 1x Chromebook Crostini), and tested several clients (2x Windows, ChromeOS). I tried both SSH-forwarding as well as a server with a proper DNS. I only used the Vim plugin on the code-server side and disabled all browser extensions (also tried with a guest account and incognito mode) and I can't get the behaviour you observe.

I do see that the "<leader>" key is detected correctly, no matter what setting I use - this is visible by the status bar indication (which shows <leader> when you press the leader). I can also use the remapping of the <leader>d sequence to act as dd (i.e. delete a line) and this works. I can even configure a remapping for <leader><leader>w to something else and it works, yet it does not activate the Easymotion mode as it should (and, to reiterate, the same actions in vanilla VSCode work fine).

How do I debug this? Could I access the internals of the plugin from the Dev console somehow? Maybe there's a window.* variable exposed or breakpoint I could set somehow somewhere to understand what happens?

Perhaps those questions are better asked in VSCodeVim's repository, but maybe you have good ideas.

**Comment by code-asher** [comment] 2021-04-26 17:10
Huh, strangely enough I'm able to reproduce. Running Firefox on Linux.

**Comment by rliang** [comment] 2021-05-27 22:13
I found that if the extension is installed via `code-server --install-extension`, then it works, however if it is installed via the marketplace UI (which makes it get installed as a "browser extension"), then it doesn't work.

**Comment by konstantint** [comment] 2021-05-29 16:02
Tried both ways - doesn't work in either case for me.

**Comment by nigelgbanks** [comment] 2022-03-18 10:07
Still not working as either "browser extension" or  "remote extension"

**Comment by chromakode** [comment] 2022-05-28 21:31
I'm running into this too on code-server v4.4.0. I've tried both installing the extension locally and via `code-server --install-extension` -- in both cases, the EasyMotion mode does not activate.

**Comment by jsjoeio** [comment] 2022-05-31 14:19
@chromakode are there any browser/server logs you can share? Or steps to reproduce?

**Comment by joshuali925** [comment] 2022-06-12 03:10
possibly related https://github.com/VSCodeVim/Vim/issues/7238

code server used to install extensions on the server side, but after some version (4.x?) vim is installed to the browser. Vim plugins won't work anymore due to the issue above, not sure if it's intentional. I sent a PR about 2 weeks ago and this issue has been there longer but neither got any attention yet

**Comment by jsjoeio** [comment] 2022-06-13 14:51
Nice! Well let's hope they review and merge your PR soon!

**Comment by yingpwu** [comment] 2023-01-16 02:09
> @chromakode are there any browser/server logs you can share? Or steps to reproduce?

```js
[Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys=w. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key=w. keySlice=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: Selections: Adding Selection Change to be Ignored! Hash: [2, 0; 2, 0], Selections: [2, 0], [2, 0] Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 3ms Dismiss Suppress Errors
console.ts:137 [Extension Host] Extension Startup: Selections: Ignoring selection: [2, 0; 2, 0], Count left: 0 Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys=w. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key=w. keySlice=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: Selections: Adding Selection Change to be Ignored! Hash: [2, 1; 2, 1], Selections: [2, 1], [2, 1] Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] Extension Startup: Selections: Ignoring selection: [2, 1; 2, 1], Count left: 0 Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys=w. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key=w. keySlice=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: Selections: Adding Selection Change to be Ignored! Hash: [3, 0; 3, 0], Selections: [3, 0], [3, 0] Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] Extension Startup: Selections: Ignoring selection: [3, 0; 3, 0], Count left: 0 Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap found. waiting for other key or timeout to finish. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 0ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= , . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= , . keySlice=  . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= , . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap broken. resending keys without allowing a potential remap on first key. keys= ,  Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap found. waiting for other key or timeout to finish. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 0ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= ,w. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= ,w. keySlice= w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= ,w. keySlice=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap broken. resending keys without allowing a potential remap on first key. keys= ,w Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys=w. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key=w. keySlice=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: Selections: Adding Selection Change to be Ignored! Hash: [3, 6; 3, 6], Selections: [3, 6], [3, 6] Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 2ms Dismiss Suppress Errors
console.ts:137 [Extension Host] Extension Startup: Selections: Ignoring selection: [3, 6; 3, 6], Count left: 0 Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap found. waiting for other key or timeout to finish. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 0ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= , . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= , . keySlice=  . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= , . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap broken. resending keys without allowing a potential remap on first key. keys= ,  Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap found. waiting for other key or timeout to finish. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 0ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 1ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= ,w. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= ,w. keySlice= w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= ,w. keySlice=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: normalModeKeyBindingsMap. potential remap broken. resending keys without allowing a potential remap on first key. keys= ,w Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=<space>. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys= . mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key= . keySlice= . Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('<space>') took 0ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handling key=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: trying to find matching remap. keys=w. mode=Normal. keybindings=normalModeKeyBindingsMap. Dismiss Suppress Errors
console.ts:137 [Extension Host] Remapper: key=w. keySlice=w. Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: Selections: Adding Selection Change to be Ignored! Hash: [3, 8; 3, 8], Selections: [3, 8], [3, 8] Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 2ms Dismiss Suppress Errors
console.ts:137 [Extension Host] ModeHandler: handleKeyEvent('w') took 3ms Dismiss Suppress Errors
console.ts:137 [Extension Host] Extension Startup: Selections: Ignoring selection: [3, 8; 3, 8], Count left: 0 Dismiss Suppress Errors
```

**Comment by micahnz** [comment] 2023-09-14 12:59
So I ran into this problem today and did a little regression testing since I would really like to use the plugin and found the breaking update is in the plugin its-self from 1.21.8 onward.

I currently have 1.21.7 installed and everything works as expected but the minute I install a more recent version code-server no longer registered the <leader> key presses

code-server version: 4.16.1

**Comment by GeekNOmore** [comment] 2023-12-02 00:21
> So I ran into this problem today and did a little regression testing since I would really like to use the plugin and found the breaking update is in the plugin its-self from 1.21.8 onward.
> 
> I currently have 1.21.7 installed and everything works as expected but the minute I install a more recent version code-server no longer registered the key presses
> 
> code-server version: 4.16.1

can confirm this. Though my code-server is on a much older version: 1.17.1

**Comment by joshuali925** [comment] 2023-12-02 03:26
I haven't got much response from vscodevim members in my PR whether it will be merged or not, but someone left a comment there that they were able to build and install the custom vscodevim extension with the fix https://github.com/VSCodeVim/Vim/pull/7728#issuecomment-1605889568

if you run into this issue you can probably do the same or just install their build (at your own discretion)

**Comment by code-asher** [comment] 2024-07-11 23:30
Closing out as an upstream issue (but let me know if I got it wrong).

**Closed by code-asher** 2024-07-11 23:30 UTC
Labels: needs-investigation

**Comment by code-asher** [comment] 2024-09-05 19:25
Thanks for the update!  I think we should keep this closed though as there is nothing we can do from our end.
