### ISSUE TITLE
[Bug]: Does docker image works on kubernetes 

### ISSUE THREAD

**Issue by bainadeashish** [coder/code-server#6308] opened 2023-07-05 13:37 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

Base image used is  codercom/code-server
1. Below command we use to start vscode 
/usr/bin/code-server \
                        --bind-addr 0.0.0.0:8443 \
                        --verbose \
                        --config /tmp/code-server/config.yaml \
                        --user-data-dir /tmp/data \
                        --extensions-dir /tmp/extensions \
                        --disable-telemetry \
                        --auth "none" \
                        /notebooks/notebooks
 
Error we are getting is below:
[2023-07-05T13:26:09.613Z] info  Wrote default config file to /tmp/code-server/config.yaml
[2023-07-05T13:26:24.342Z] debug parent:25 spawned child process 43
[2023-07-05T13:26:34.346Z] error timed out
[2023-07-05T13:26:34.348Z] debug parent:25 disposing {}

### Expected

coder-server process should start but its failing

### Actual

Code server process failing with below
[2023-07-05T13:26:09.613Z] info  Wrote default config file to /tmp/code-server/config.yaml
[2023-07-05T13:26:24.342Z] debug parent:25 spawned child process 43
[2023-07-05T13:26:34.346Z] error timed out
[2023-07-05T13:26:34.348Z] debug parent:25 disposing {}

### Logs

[2023-07-05T13:26:09.613Z] info  Wrote default config file to /tmp/code-server/config.yaml
[2023-07-05T13:26:24.342Z] debug parent:25 spawned child process 43
[2023-07-05T13:26:34.346Z] error timed out
[2023-07-05T13:26:34.348Z] debug parent:25 disposing {}

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by aleleba** [comment] 2023-07-11 23:11
@bainadeashish it works, I have used it in a cluster of kubernetes as a service for my own environment some time, I have used it and run also docker inside code-server and all the tooling, but for that run code-server inside a deployment and this deployment was accesible from ngnx ingress controller (with websocket activated), for https connection an lets encrypt certifivates I have used cert manager.

**Comment by code-asher** [comment] 2023-07-13 21:49
That timeout is the parent process waiting for the child process 
it forked to report.  Could there be something wrong with forking? 
A process limit or something?  I assume you only get this error in 
Kubernetes and not if you run the image locally or something?

**Comment by sofusalbertsen** [comment] 2023-09-20 14:51
We are also using this in a kubernetes cluster, so it is confirmed to work.
Anything else to report?

**Comment by code-asher** [comment] 2024-07-12 23:15
I am closing this for now since it looks like an issue with that cluster and not in code-server, but we can reopen if this is not the case.  But it will be difficult for us to debug with a reproduction I think.

**Closed by code-asher** 2024-07-12 23:15 UTC
Labels: bug, triage
