### ISSUE TITLE
[Bug]: code server goes to "Sleeping State" when closing the browser

### ISSUE THREAD

**Issue by ky1emoon** [coder/code-server#5589] opened 2022-09-26 05:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 11
- Remote OS: Ubuntu 20.04
- Remote Architecture: amd64
- `code-server --version`: 4.7.0

### Steps to Reproduce

1. open code-server (I'm using k8s and run the pod with cpu limit N)
2. run some heavy cpu-bound job in the terminal of code-server client (something like stress -c N)
3. close the browser
4. code-server (parent pid) and child processes including cpu-bound job go to sleeping state occassionally. 

### Expected

The server should be in a running state regardless of client connection

### Actual

The code-server process should be in a running state but **occasionally** goes to a sleeping state.
This leads to other terminal child processes also going to a sleeping state.

### Logs

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/14849142/192201141-3c1a22f8-689a-4844-8de7-448f284ccfef.png">

### Screenshot/Video

<img width="994" alt="image" src="https://user-images.githubusercontent.com/14849142/192201074-de00e386-5ac7-47e2-a19a-5d0a663f9116.png">

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I wonder if this is expected behavior.

**Comment by ky1emoon** [comment] 2022-09-26 06:03
I believe this might be related to https://github.com/microsoft/vscode-remote-release/issues/3096, but not sure.

**Comment by jsjoeio** [comment] 2022-09-26 20:10
🤔 if that is related and it is upstream, we not be able to do much. cc @code-asher in case you have any thoughts/ideas!

**Comment by code-asher** [comment] 2022-09-28 17:28
What do you mean by the process going into a sleeping state?  I think VS Code kills terminal processes if they are not reconnected within a timeout, could that be the cause?

**Comment by Creling** [comment] 2022-10-01 03:58
Well, I think background jobs should be guaranteed alive by tmux, screen or something similiar, but not code-server.

If you ssh to a remote server and run some jobs, you should not expect it to keep working after closing the ssh connection, so do code-server.

**Comment by code-asher** [comment] 2022-10-04 18:40
Ah so the issue is that code-server is *not* terminating jobs when closing the browser?

The reason they stay alive is in case the browser temporarily loses connectivity so it can reconnect the terminals once the network comes back up.

It is supposed to eventually kill the jobs after a timeout I believe (I think it is five minutes).

**Comment by code-asher** [comment] 2024-07-12 23:48
Closing as stale but feel free to comment if you come back to this.  This behavior is defined by VS Code though so any changes will need to go there.

**Closed by code-asher** 2024-07-12 23:48 UTC
Labels: bug, triage
