### ISSUE TITLE
[Bug]: code-server ignores path argument and always opens last location

### ISSUE THREAD

**Issue by lanrat** [coder/code-server#5195] opened 2022-05-11 17:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: macOS
- Remote OS: Linux
- Remote Architecture: amd64
- `code-server --version`: 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2

### Steps to Reproduce

1. open code-server on directory foo: `code-server /path/to/project/foo`
2. close/kill/stop code-server
3. open code-server on directory bar: `code-server /some/other/path/bar`

### Expected

For code-server to run with the project base in `/some/other/path/bar`.

### Actual

code-server runs with the project base `/path/to/project/foo`

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This has worked fine until recently.

Using over SSH tunnel, NOT HTTPS.

**Comment by jsjoeio** [comment] 2022-05-11 21:50
Can you please upgrade to 4.4.0 and see if the issue persists?

**Comment by lanrat** [comment] 2022-05-11 23:15
I just upgraded to 4.4.0 and tested and got the same result.

**Comment by lanrat** [comment] 2022-07-10 00:17
Just upgraded to v4.5.0 and still have this problem.

**Comment by code-asher** [comment] 2022-08-02 18:33
I believe this is as designed; code-server will prefer the last opened directory to whatever is passed on the command line.

This behavior can be prevented with `--ignore-last-opened` to always open the directory passed on the command line.

**Comment by lanrat** [comment] 2022-08-02 18:43
> I believe this is as designed; code-server will prefer the last opened directory to whatever is passed on the command line.
> 
> This behavior can be prevented with `--ignore-last-opened` to always open the directory passed on the command line. Let us know if that works for you!

@code-asher This is not the behavior of older versions of code-sever. Additionally if that is the case, then why does code-server even take a path at all?

I think that if a path is provided, code-server should use it. If no path is provided, then defaulting to the last used path is desirable. But ignoring a path the user intentionally provided seems undesirable.

Thanks for letting me know about the `--ignore-last-opened` flag. That, at least temporarily, does provide the desired behavior.

**Comment by code-asher** [comment] 2022-08-02 19:42
Yeah I had the same thoughts which is the reason we initially implemented it such that the path was preferred.  I originally wrote in [this issue](https://github.com/coder/code-server/issues/1132):

> [...] if you explicitly call code-server it'll favor the last directory instead of whatever you passed on the command line. It feels unexpected to me [...]

I was going back and forth on it for a bit since code-server was intended to be ran as a long-lived server process via systemd or something like that and not spawned manually with different paths but ultimately we decided to prefer the path over the last opened.

Today though the path acts as a default directory for when there is not yet any last opened directory (to answer the question of why it still takes a path) and `--ignore-last-opened` can be used to revert to the old behavior.

This default directory behavior is useful but we could have instead implemented this with a `--fallback-directory` or something which I think would make more sense.  I am not sure why we went with the implementation we did.

**Comment by code-asher** [comment] 2022-08-02 20:01
So looking at the commit history I think this happened during the switch to upstream's server.  Upstream's implementation was preferring the last opened to the provided path so that naturally became our default as well.  That makes sense since I did not recall explicitly changing this behavior.

This happened during a major version bump so I guess that panned out; changing it at this point seems like it might be risky if users are depending on the current behavior unless we major bump.

**Comment by Oglopf** [comment] 2022-11-08 15:37
I'm currently having problems with this on version `4.5.1`. Currently, we have [an app for codeserver](https://github.com/OSC/bc_osc_codeserver) to be used on HPC systems, where a user selects a path in a form and launches their own codeserver in a container to work in. 

This workflow seems to be at odds with the intended design that I'm reading in this issue though, where codesrver instead is used as a long lived process to open many paths from(?), if I'm understanding correctly.

Trying to use the `--ignore-last-opened` in the `script` [where `coderserver` is called](https://github.com/OSC/bc_osc_codeserver/blob/master/template/script.sh.erb#L52) also is not fixing the issue for me when the script runs. Any ideas how to get the `4.5.1` version to just take the path I give it and not the behavior of loading a cached directory (where does it actually get this?)?

Is there a version that fixes this issue and works with a passed path?

**Comment by jsjoeio** [comment] 2022-11-08 17:34
I was looking through the release notes to see when that might have changed after `4.5.1` but couldn't find anything. 

I'm on `4.8.2` and when I launch `code-server --ignore-last-opened` it loads an empty window. 

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/200634878-a18c8e7e-9de5-458a-9690-1f0b6d154878.png">

When I launch `code-server ./dev/coder/code-server` it opens that folder:

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/200635082-eb002523-c5f6-422c-bd54-ec17cfe9d67d.png">

The other thing you can do is use the query parameter: `https://localhost:8080/?folder=/Users/jp/dev/coder`

**Comment by Oglopf** [comment] 2022-11-08 18:56
Thanks @jsjoeio 

My requirement at the moment was `4.5` so `4.8` is not an option I can use at the moment. However, if it's the case that this behavior is in fact broken in `4.5` and fixed by `4.8` I can put the request in to use that version instead. Is that correct that passing a path will have it load correctly on `4.8`?

In `4.5` this does not work, and while passing the `--ignore-last-opened` does launch an empty window, this breaks the functionality of the user selecting the working directory in the `form` they are shown, and instead relies on the user understanding how to navigate to the correct location within `codeserver` which is not ideal for the users across all the institutions using this.

**Comment by jsjoeio** [comment] 2022-11-08 19:47
> My requirement at the moment was 4.5. However, if it's the case that this behavior is in fact broken in 4.5 and fixed by 4.8 I can put the request in to use that version instead. Is that correct that passing a path will have it load correctly on 4.8?

Yes! 4.8.2 should have the behavior you're looking for then

**Comment by code-asher** [comment] 2024-07-11 23:23
I think we are stuck on the current status quo for now, but if someone wants to open a PR for a new flag that has different behavior, that would be welcome.

**Closed by code-asher** 2024-07-11 23:23 UTC
Labels: needs-decision
