### ISSUE TITLE
Support PAM authentication

### ISSUE THREAD

**Issue by niyazialpay** [coder/code-server#5906] opened 2022-12-17 21:44 UTC
## What is your suggestion?
In my opinion, starting a service in this way "systemctl status code-server@$USER" separately for each system user creates too much system load. I think if each user can log in with his own system password, it can work under his own home directory without any problems.

## Why do you want this feature?
I want to use VSCode-Server on a web server to authorize users to operate under their own directory.

## Are there any workarounds to get this functionality today?
I don't know

## Are you interested in submitting a PR for this?
Sorry, I don't know typescript or nodejs

**Comment by tobycm** [comment] 2022-12-18 07:22
You could take a look at this: https://coder.com/blog/code-server-multiple-users

**Comment by jsjoeio** [comment] 2022-12-19 15:27
> VSCode-Server

You may be looking at the wrong project! This is code-server which is a fork of VS Code with a couple patches to allow you to self-host

**Comment by code-asher** [comment] 2024-07-13 01:40
Duplicate of https://github.com/coder/code-server/issues/1988

**Closed by code-asher** 2024-07-13 01:40 UTC
Labels: enhancement
