### ISSUE TITLE
Code server not work in android userland [Bug]: 

### ISSUE THREAD

**Issue by Mustapha-aneen** [coder/code-server#6571] opened 2023-12-08 09:56 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

1. 
2.g
3.

### Expected

root@localhost:~# code-server
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node'
Require stack:
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/argon2.js
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/util.js
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/cli.js
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/entry.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/argon2.js',
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/util.js',
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/cli.js',
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/entry.js'
  ]
}

Node.js v18.19.0
root@localhost:~#

### Actual

I install code server using npm but in I run code-server it not work

### Logs

root@localhost:~# code-server
node:internal/modules/cjs/loader:1137
  throw err;
  ^

Error: Cannot find module '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/lib/binding/napi-v3/argon2.node'
Require stack:
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/argon2.js
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/util.js
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/cli.js
- /root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/entry.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1134:15)
    at Module._load (node:internal/modules/cjs/loader:975:27)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/argon2.js:9:25)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/node_modules/argon2/argon2.js',
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/util.js',
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/cli.js',
    '/root/.nvm/versions/node/v18.19.0/lib/node_modules/code-server/out/node/entry.js'
  ]
}

Node.js v18.19.0
root@localhost:~#

### Does this issue happen in VS Code or GitHub Codespaces?

- [ ] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [x] I am using a secure context.

**Comment by code-asher** [comment] 2023-12-08 17:21
Looks like a duplicate of https://github.com/coder/code-server/issues/5561?  I am not sure what the fix is.

**Comment by code-asher** [comment] 2024-07-12 22:38
Closing as a duplicate of https://github.com/coder/code-server/issues/5561

**Closed by code-asher** 2024-07-12 22:38 UTC
Labels: bug, duplicate
