### ISSUE TITLE
Tasks doesn't work: tries to run cmd.exe under freebsd

### ISSUE THREAD

**Issue by olegsidorkin** [coder/code-server#4743] opened 2022-01-13 17:55 UTC
## OS/Web Information

- Web Browser: Firefox 95.0.2
- Local OS: Windows 10
- Remote OS: FreeBSD 13
- Remote Architecture: x86_64
- `code-server --version`: 4.0.1 735c6da829535969ff7193c79379299e4a1cb9bc

## Steps to Reproduce

1. Create workspace
2. Put attached tasks.json to the .vscode folder
3. Try to run the task (e.g. with Ctrl-Shift-B)

## Expected
Task is run. 123 message is printed

## Actual
```
> Executing task in folder src: echo 123 <

The terminal process failed to launch: Path to shell executable "cmd.exe" does not exist.

Terminal will be reused by tasks, press any key to close it.
```

## Logs
Debug logs are attached. It does detect bash (it doesn't detect csh - that's another issue), but still tries to run cmd.exe

[tasks.json.zip](https://github.com/coder/code-server/files/7864845/tasks.json.zip)
[log.txt](https://github.com/coder/code-server/files/7864882/log.txt)

**Comment by jsjoeio** [comment] 2022-01-14 21:34
Hmm...I'm on macOS and it worked. 

![image](https://user-images.githubusercontent.com/3806031/149588169-28aaf008-41d5-4be3-8c52-4ad70099e483.png)

Do you know what the path to the shell executable should be on FreeBSD?

cc @code-asher

**Comment by olegsidorkin** [comment] 2022-01-15 21:29
Base (every) system has /bin/sh for simple shell and /bin/csh for tcsh.
Other shells are optional.

**Comment by jsjoeio** [comment] 2022-01-18 17:38
@olegsidorkin got it! We'll look into this. Thank you!

**Comment by olegsidorkin** [comment] 2022-01-18 20:11
An interesting moment: everything is OK if I run firefox on the same FreeBSD box the code-server is running. Error arises only if I'm using remote windows PC. It seems that it  somehow detects the client OS and misuses this knowledge.

**Comment by jsjoeio** [comment] 2022-01-18 20:20
Interesting data point! I wonder where that logic lives 🤔 so to summarize, it sees you're running on a Windows PC (maybe based on the User Agent?) and tries to use `cmd.exe` instead of `/bin/sh` on your FreeBSD box? Is that right?

**Comment by olegsidorkin** [comment] 2022-01-18 20:37
Yes, exactly. 

 It seems to be somewhere here: https://github.com/microsoft/vscode/blob/e8838f10628a63ca0c9d73fbedabfd35d6abf2cb/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1040 but I'm not a NodeJS developer.

**Comment by olegsidorkin** [comment] 2022-01-18 20:57
I've just faked userAgent via general.useragent.override config var to _Mozilla/5.0 (X11; FreeBSD amd64; rv:95.0) Gecko/20100101 Firefox/95.0_ , reloaded codeserver page and everything worked. Also tried to replace FreeBSD with Linux - that also worked :)

**Comment by jsjoeio** [comment] 2022-01-18 21:28
> It seems to be somewhere here: https://github.com/microsoft/vscode/blob/e8838f10628a63ca0c9d73fbedabfd35d6abf2cb/src/vs/workbench/contrib/tasks/browser/terminalTaskSystem.ts#L1040 but I'm not a NodeJS developer.

Wow, nice find! That looks promising. 

> reloaded codeserver page and everything worked. Also tried to replace FreeBSD with Linux - that also worked :)

No way! Is there any chance you can see if this error happens on Codespaces? (probably not but worth asking).

I'm wondering if this is a VS Code bug or a code-server bug. Either way, I think we should be able to patch it somehow

**Comment by olegsidorkin** [comment] 2022-01-18 22:07
No, I have no access to codespaces.

I think it's easy to reproduce it in any environment now: run codeserver, run firefox, set user agent to 
_Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0_
open codeserver and try to execute any task (just tested this on my BSD box - it tried to launch cmd.exe).

**Comment by jsjoeio** [comment] 2022-01-19 20:43
Hmm...I tried overriding my useragent in Firefox and I can't reproduce. Am I doing something wrong?

## Video

https://user-images.githubusercontent.com/3806031/150210444-aa642142-831e-462f-834e-9c9ebcfa7909.mov

![image](https://user-images.githubusercontent.com/3806031/150210599-2a0109db-6837-486c-8dce-ccbe7e1e3051.png)

**Comment by olegsidorkin** [comment] 2022-01-20 00:01
And what happens if you try replace it with one from windows ( _Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0_ )?

**Comment by jsjoeio** [comment] 2022-01-20 17:06
Still doesn't reproduce. Hmm...Do I need to refresh Firefox for the changes to take effect?

![image](https://user-images.githubusercontent.com/3806031/150386832-8f9ddc78-4e32-4f09-be13-983ca6fc2cb7.png)

EDIT: tried closing and opening FF, no luck

**Comment by olegsidorkin** [comment] 2022-01-20 17:26
That's strange: it reproduces for me consistently. In my case refreshing the window was enough. Could you please open developer tools and check what UserAgent header is actually passed to the server?

I'll try to reproduce this on the linux host to check if this is BSD-specific,

**Comment by jsjoeio** [comment] 2022-01-21 17:27
@olegsidorkin Sorry I didn't get a chance to retest. But happy to hear you were able to isolate it to BSD. I wonder if we need to add some check that's specific for BSD.

Do you have access to Codespaces by chance? I'm wondering if this is actually an issue upstream

**Comment by jsjoeio** [comment] 2022-01-21 17:27
Or actually, if you clone microsoft/vscode and run it locally via the web version, I wonder if you can reproduce

**Comment by olegsidorkin** [comment] 2022-01-21 20:08
> Or actually, if you clone microsoft/vscode and run it locally via the web version, I wonder if you can reproduce

Tried to build it but it fails to load in the browser: just white screen with infinite loading. I think there are some changes in codeserver to allow it to run under BSD

**Comment by jsjoeio** [comment] 2022-01-21 20:56
Ah dang, okay. You must be right. Thank you for trying at least!

**Comment by code-asher** [comment] 2024-07-13 01:34
Let me know if this still happens in the latest release, although we do not officially support FreeBSD and I think any fixes will need to go upstream anyway https://github.com/microsoft/vscode

**Closed by code-asher** 2024-07-13 01:34 UTC
Labels: bug
