### ISSUE TITLE
[Bug]: Error: Creating workers from remote extensions is currently not supported.

### ISSUE THREAD

**Issue by bilogic** [coder/code-server#5869] opened 2022-12-12 18:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Ubunu
- Remote Architecture: amd64
- `code-server --version`: 4.9.0 0502dfa1ff42ab8a43adb911f7bf21f8b09ee25f with Code 1.73.1

### Steps to Reproduce

1. Installed PHP Tools extension by devsense.com https://open-vsx.org/api/devsense/phptools-vscode/web/1.25.11540/file/DEVSENSE.phptools-vscode-1.25.11540@web.vsix
2. Extension is unable to run in code-server
3. Error given is `Error: Creating workers from remote extensions is currently not supported.`

### Expected

PHP Tools extension should be able to install and run as it works in vscode.dev and github.dev

### Actual

1. Extension is unable to run in code-server
2. Error given is `Error: Creating workers from remote extensions is currently not supported.`

### Screenshot/Video

![image](https://user-images.githubusercontent.com/946010/207124216-7119793f-48e2-4aba-9106-1418f4f705aa.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment] 2022-12-12 19:05
Interesting! I haven't seen this one before. @code-asher have you?

**Comment by bilogic** [comment] 2022-12-13 02:20
I have been trying to fix this for about a week now. It is 100% reproducible. 

I think it has something to do with this https://github.com/microsoft/vscode/issues/144513

But I'm on the impression that the VSCode part of github/vscode.dev is entirely open sourced and same as code-server, so I'm surprised to know there is this difference. Would this be something that code-server can fix?

Thank you

**Comment by jsjoeio** [comment] 2022-12-13 17:07
Hmm..if it works on github/vscode.dev then it's a bug in code-server and something we may be able to fix if we can figure out why it's happening.

**Comment by bilogic** [comment] 2022-12-13 17:38
https://github.com/microsoft/vscode/blob/96bf637c101b8832e44a97a27a26305d8c2cf22e/src/vs/workbench/api/worker/extensionHostWorker.ts#L100-L103

@jsjoeio I located the error message in vscode, does it help?

**Comment by jsjoeio** [comment] 2022-12-13 20:43
Definitely a step forward! Thank you! Thinking out loud for second here...

**The Problem**: extensions cannot create workers

_What is a worker?_
I assume it's referring to a [web worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers)? 

_Can this be reproduced?_
Yes, in code-server using [this PHP extension](https://open-vsx.org/extension/devsense/phptools-vscode).

_Does this bug occur upstream?_
No, at least not on github/vscode.dev so it's definitely possible to make work in code-server.

_If someone picks this up, where should they start looking?_
The error occurs here (thanks to @bilogic): https://github.com/microsoft/vscode/blob/96bf637c101b8832e44a97a27a26305d8c2cf22e/src/vs/workbench/api/worker/extensionHostWorker.ts#L100-L103

I'd also look into this: https://github.com/microsoft/vscode/issues/144513#issuecomment-1112963321

**Comment by code-asher** [comment] 2022-12-19 21:23
One interesting difference is that the vscode.dev one is marked as a browser extension while on code-server it is marked as a remote extension.

For vscode.dev I used the extension panel to install but in code-server I had to install from vsix because from the extension panel it said the extension is not supported in web (which given this error appears to be true).

So one theory is that Open VSX is not serving the web version of this extension yet.

I tried installing in Codespaces from the command line (`code --install-extension DEVSENSE.phptools-vscode`) to force it to install the non-web version and I get a different error but it does not work there either.

I am not sure it actually works in vscode.dev either.  Am I supposed to get intellisense for functions?  I tried typing `explode` for example but nothing comes up.

**Closed** 2024-07-11 23:35 UTC
Labels: upstream:vscode
