### ISSUE TITLE
[Bug]: Text in terminal Nearly/is unreadable

### ISSUE THREAD

**Issue by Topdog1221** [coder/code-server#5036] opened 2022-03-27 02:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: Windows 11
- Remote OS: Ubuntu Server LTS
- Remote Architecture: ARM
- `code-server --version`: 4.2.0 arm64

### Steps to Reproduce

1. Open code-server
2. New Terminal

### Expected

I should be able to read the text

### Actual

It becomes almost packed in

### Screenshot/Video

![image](https://user-images.githubusercontent.com/55218279/160264296-6b68705d-7f03-4b41-975c-db6264b78aa9.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This does not occur on chrome.

**Comment by jsjoeio** [comment] 2022-03-28 22:44
Can you reproduce this on https://xtermjs.org/?

**Comment by jsjoeio** [comment] 2022-04-01 21:07
@MattJGH Can you reproduce this on https://xtermjs.org/?

**Comment by mahir256** [comment] 2022-04-05 04:46
I am using Firefox 98.0.2 on Windows 10 accessing, via an SSH tunnel and thus not HTTPS, a code-server 4.2.0 arm64 instance hosted on Ubuntu 20.04.4. I too run into this problem frequently and have never experienced this under VS Code, and using the same browser the example terminal at xtermjs.org does not have this problem.

What's interesting is that when I select text in the terminal, the resulting highlight suggests that the characters are in fact normally positioned and not packed, but that there's some other styling rule being applied which is cutting through each of the characters to yield this effect. (This is the reason I state that I encounter this frequently and not always, because sometimes I start a code-server session and this styling rule may randomly not get applied. As a matter of fact, there was one prior occasion when I opened a terminal pane and the text was for a split-second normal before characters got cut off again.)

**Comment by jsjoeio** [comment] 2022-04-05 18:19
@mahir256 I wonder if there is some font rendering performance option or something in the `settings.json` related to this. I can't remember what it's called but maybe someone else can.

**Comment by MattJGH** [comment] 2022-04-05 18:21
> 

Yep, same thing happens in the emulated terminal. I think its an issue with my browser then.

**Comment by jsjoeio** [comment] 2022-04-05 18:29
@MattJGH ahh! thanks for following up.

Does this help at all? https://github.com/xtermjs/xterm.js/wiki/FAQ

**Comment by avsthiago** [comment] 2022-04-08 15:44
I had the same issue. The link that @jsjoeio [posted](https://github.com/coder/code-server/issues/5036#issuecomment-1089160815) solved for me.

**Comment by Hpmason** [comment] 2022-05-15 03:54
What did you do to fix this @avsthiago? Is there a specific Firefox setting that I can change?

**Comment by avsthiago** [comment] 2022-05-15 07:59
Hi @Hpmason. Since I use the Brave browser, I went to the "orange lion icon" next to the search bar and allowed the trackers.

It is possible that you have an extension that is causing this issue, e.g. AdBlock. You could try disabling them.

**Comment by Hpmason** [comment] 2022-05-15 18:28
Thanks. Turns out it was the `DuckDuckGo Privacy Essentials` extension of all things. Turning it off for the site fixes the issue

**Comment by jsjoeio** [comment] 2022-05-19 21:43
Great! I'm going to close this for now.

**Closed by jsjoeio** 2022-05-19 21:43 UTC
Labels: waiting-for-info

**Comment by d3ssen** [comment] 2022-06-22 06:40
I had this issue but didn't want to disable the 'Privacy Essentials' extension fully. I found that it is possible to add the url of my Code-Server to 'unprotected sites' if you manage the extension. After reloading the site the terminal looked normal.
