### ISSUE TITLE
[Feat]: Darkmode on Login Page

### ISSUE THREAD

**Issue by catalpaaa** [coder/code-server#6292] opened 2023-06-28 11:21 UTC
## What is your suggestion?
Darkmode on login page

## Why do you want this feature?
Save our eyes!

## Are there any workarounds to get this functionality today?
Darkreader, but not all devices have it install. It also mess up all the UI.

## Are you interested in submitting a PR for this?
No, sorry

**Comment by code-asher** [comment] 2023-06-29 23:06
I think this is a duplicate of https://github.com/coder/code-server/issues/3019 although the title is not very discoverable so I will rename it.

I think what we should do is try reading the VS Code settings to get the current theme background color and use that on the login page.

**Closed by code-asher** 2023-06-29 23:06 UTC
Labels: enhancement

**Comment by sickplanet** [comment] 2024-10-12 10:33
@catalpaaa 
try this: https://github.com/sickplanet/code-server-dark-mode-login-page
