### ISSUE TITLE
[Bug]: The built-in language plug-in is invalid

### ISSUE THREAD

**Issue by dingzhouL** [coder/code-server#6688] opened 2024-02-26 07:18 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: firefox
- Local OS: Ubuntu20.04 
- Remote OS: Ubuntu20.04
- Remote Architecture: amd64
- `code-server --version`: V4.19.1

### Steps to Reproduce

1. Compile code-server v4.19.1 as an image;
2. run the `docker run -d name code-server -e PASSWORD=111111 [image-id] `command;
3.Access the browser.

### Expected

I packed the plugin `Language pack extension for Chinese (Simplified)` into it, but did not get the `zh-cn` option through`Configure Display Language`.
![1708929150941](https://github.com/coder/code-server/assets/111402326/dc56cae0-b915-47ab-900c-aa5e5f125438)

This seems strange, but when I installed other language packs in the plugin market, the `zh-cn` option appeared.
![1708929250502](https://github.com/coder/code-server/assets/111402326/e786ae0e-9d51-4ac9-b689-746cfc0f1708)

### Actual

How do I change the default language option to `zh-cn` with the built-in plugin?

In addition, when I switch the language to `zh-cn`, the current language in the configuration is still `en`, which is just a display problem and does not affect the user's use.

![1708930467096](https://github.com/coder/code-server/assets/111402326/7ae6d412-8a20-41cd-8b94-8478acc530c8)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I tested this in native VS Code.
- [X] This does not happen in native VS Code.
- [ ] I tested this in GitHub Codespaces.
- [ ] This does not happen in GitHub Codespaces.

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

This problem does not occur by manually installing the language pack.

**Comment by code-asher** [comment] 2024-02-26 22:02
I think this is a duplicate of https://github.com/coder/code-server/issues/4735

Basically, when a language pack is installed, VS Code generates a language bundle, but unfortunately there is a bug and this only happens when you install from the UI.

We do patch language stuff here in code-server, so I am not sure if this is our bug or something upstream.  More investigation will be required.

**Comment by dingzhouL** [comment] 2024-02-27 01:00
Thank you very much for answering my question.

**Closed** 2024-07-12 00:26 UTC
Labels: bug, triage
