### ISSUE TITLE
[Bug]: Broken Terminal Text

### ISSUE THREAD

**Issue by MattJGH** [coder/code-server#5059] opened 2022-04-01 13:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Brave
- Local OS: Windows 11 Pro
- Remote OS: Ubuntu 20.04 (code-server is containerized)
- Remote Architecture: amd64
- `code-server --version`: Cannot run command in container - code-server not found.

### Steps to Reproduce

1.  Open code-server
2.  Run a python file

### Expected

Output should be readable, clear.

### Actual

Output text is broken - 'fuzzy'

### Screenshot/Video

![LSDCwhbcW3](https://user-images.githubusercontent.com/62468422/161277482-ce45405f-ef17-41a6-8d98-4d9ba79034a6.png)
![BjLHvjBgfr](https://user-images.githubusercontent.com/62468422/161277533-c095d7a0-b88e-4a8a-8c08-1e0390090fa4.png)

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment] 2022-04-01 21:06
Duplicate of https://github.com/coder/code-server/issues/5036

Let's consolidate there.

**Closed by jsjoeio** 2022-04-01 21:06 UTC
Labels: bug, triage
