### ISSUE TITLE
[Bug]: install fails for RPI4

### ISSUE THREAD

**Issue by s0170071** [coder/code-server#5966] opened 2023-01-12 19:21 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: not applicable
- Local OS: Linux Mint 21
- Remote OS: "Raspbian GNU/Linux 10 (buster)"
- Remote Architecture: ARM v7 (RPI4)
- `code-server --version`: 4.9.1 f7989a4dfcf21085e52157a01924d79d708bcc05 with Code 1.73.1

### Steps to Reproduce

1. get a RPI4 with openhabian image installed. 
2. run install script curl -fsSL https://code-server.dev/install.sh | sh
3.  start code-server

it will fail because there are packages missing. They can be installed manually. This fixes this for me: 

```
npm install -g minimist yazl yauzl @microsoft/1ds-core-js spdlog  vscode-regexpp vscode-proxy-agent @vscode/ripgrep xterm-headless  @parcel/watcher
sudo apt-get install libsecret-1-dev
npm install keytar

```

### Expected

painless clean install ...

### Actual

comes up with a 500 error in the web browser and some more messages on the console.

### Logs

19:45:29] [192.168.1.11][e90bc42c][ManagementConnection] The client has disconnected gracefully, so the connection will be disposed.
[19:45:29] [192.168.1.11][20a87450][ExtensionHostConnection] <24644> Extension Host Process exited with code: 0, signal: null.
[19:45:31] [192.168.1.11][71275f9c][ManagementConnection] New connection established.
[IPC Library: File Watcher] Loading "@parcel/watcher" failed
[IPC Library: File Watcher] Error: Cannot find module '@parcel/watcher'
Require stack:
- /usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-amd.js
- /usr/lib/node_modules/code-server/lib/vscode/out/bootstrap-fork.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at r (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:101)
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1720)
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10382)
    at a (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10224)
    at Object.errorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10345)
    at e.triggerErrorback (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10746)
    at /usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10452
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:1737)
    at e.load (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:3:10382)
    at a (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10224)
    at s._loadModule (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:10354)
    at s._resolve (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:452)
    at s.defineModule (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:5:6066)
    at y (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:6:1825)
    at h (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2554)
    at Object.<anonymous> (/usr/lib/node_modules/code-server/lib/vscode/out/vs/platform/files/node/watcher/watcherMain.js:15:21899)
    at Object.<anonymous> (/usr/lib/node_modules/code-server/lib/vscode/out/vs/platform/files/node/watcher/watcherMain.js:15:33430)
    at e._createAndEvalScript (/usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2598)
    at /usr/lib/node_modules/code-server/lib/vscode/out/vs/loader.js:4:2237
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[IPC Library: File Watcher] Here are the modules that depend on it:
[IPC Library: File Watcher]% [ 'vs/platform/files/node/watcher/parcel/parcelWatcher' ]
[19:45:32] [192.168.1.11][c138bc21][ExtensionHostConnection] New connection established.
[19:45:32] [192.168.1.11][c138bc21][ExtensionHostConnection] <25552> Launched Extension Host Process.
File not found: /usr/lib/node_modules/code-server/lib/vscode/node_modules/vscode-textmate/release/main.js
File not found: /usr/lib/node_modules/code-server/lib/vscode/node_modules/vscode-oniguruma/release/main.js
File not found: /usr/lib/node_modules/code-server/lib/vscode/node_modules/vscode-oniguruma/release/onig.wasm

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment] 2023-01-13 17:07
Hmmm 🤔 Is this postinstall script running after installing code-server?

**Comment by s0170071** [comment] 2023-01-13 17:48
Yes, i think so. That is the one recommending the path variable update , right?

**Comment by jsjoeio** [comment] 2023-01-13 21:19
Hmm..I don't think so. It should say like `sh postinstall.js` in the output which is where it will install VS Code node_modules and stuff. Can you try reinstalling and then post the logs?

**Comment by tmisch** [comment] 2023-01-30 10:39
I think i am facing the same error in trying to run code-server in a container image on RPI4 (with 64 bit OS: `Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64 GNU/Linux`). So the issue might be reproducible using a container build.

Architecture for the container image is `arm/v8`, which is not provided by the `codercom/code-server` images, that's why i build the image on my own. Since the image build does not work directly on RPI4 (at least using podman, due to error `package architecture (arm64) does not match system (armhf)`) i am doing a cross-build on Windows for platform `arm/v8`. As far as i understood, script `install.sh` falls back to build code-server from scratch on this platform. 

When running the final image on RPI4 using podman, the errors about missing packages occur when trying to login to vscode in the browser.

This is the Dockerfile i am using to build the image:
```
FROM debian:bullseye

RUN apt-get update && apt-get install -y \
        curl \
        dumb-init \
        build-essential \
        pkg-config \
        python3 \
    && curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt install nodejs \
    && rm -rf /var/lib/apt/lists/*

RUN npm config set python python3 \
    && curl -fsSL https://code-server.dev/install.sh | sh

EXPOSE 8080

ENTRYPOINT ["dumb-init", "/usr/bin/code-server", "--bind-addr", "0.0.0.0:8080"]
```

The build process is started with this command (using Docker on windows):
`docker buildx build --rm --platform linux/arm/v8 -t <image> .`

And finally, the image is run on RPI4:
`podman run --rm -p 8080:8080 <image>`

I hope this helps to narrow down the problem.

**Comment by code-asher** [comment] 2023-02-06 17:03
I think the install script falls back to installing via npm so it 
sounds like this could also be reproduced with `npm install -g 
code-server` which I guess means this is an npm bug?

**Comment by U5B** [comment] 2023-02-10 16:50
Same issue as this one: https://github.com/coder/code-server/issues/5530
Seems like Raspberry PIs have an issue.

**Comment by code-asher** [comment] 2023-02-13 18:57
@U5B thank you for that link, will close this as a duplicate of #5530

**Closed by code-asher** 2023-02-13 18:57 UTC
Labels: waiting-for-info
