### ISSUE TITLE
Can't install extensions with code-server on Termux

### ISSUE THREAD

**Issue by Clem0803** [coder/code-server#4235] opened 2021-09-23 20:15 UTC
### Discussed in https://github.com/cdr/code-server/discussions/4223

<div type='discussions-op-text'>

<sup>Originally posted by **Clem0803** September 22, 2021</sup>
When I try to install extensions, I have everytime the same error : Can't install 'ms-python.python' extension because it is not compatible with the current version of VS Code (version 1.60.0).
I run code server version 3.12.0 on Android with Termux and I use Brave as browser but I try Chrome and there is no difference.
![Screenshot_20210922-184327_Termux](https://user-images.githubusercontent.com/48407049/134386186-c520aeb7-8eb4-4250-820b-7797e1059396.jpg)
</div>

**Comment by jsjoeio** [comment] 2021-09-23 23:02
Can you install extensions directly from code-server?

**Comment by jsjoeio** [comment] 2021-09-23 23:04
Sadly, I cannot reproduce on macOS. I wonder if this is specific to your environment (Termux)

![image](https://user-images.githubusercontent.com/3806031/134595128-7e9eeb44-6a01-4d20-b390-50d74849e896.png)

**Comment by Vaitek** [comment] 2021-09-24 12:49
How can we help with this problem? the previous version worked well in Termux.

**Comment by jsjoeio** [comment] 2021-09-24 17:19
> How can we help with this problem? the previous version worked well in Termux.

I wish I had a good answer for that 😢 I took a quick look and I believe what happens is:
1. user passes `--install-extension <name>`
2. we use the vscode CLI to call this and install extension
3. vscode checks `engines` field in extension manifest/package.json
4. vscode checks current version 
5. if mismatch or not supported, throws this error

You'd have to look at [our fork](https://github.com/cdr/vscode/tree/1.60.0-code-server-patch) and see what might be wrong. 

I know that's not very helpful 😅 But I'm around and can share more tips/guidance here.

@TeffenEllis might be able to provide some tips as well.

**Comment by Nyonyix** [comment] 2021-09-26 00:35
Just wanted to put my 2 cents in,

Fresh termux and code server, Nothing else and it still fails to install.

In the meantime would an older version work and how would we go about that?

**Comment by Clem0803** [comment] 2021-09-27 03:45
I don't know why the latest version doesn't work with me but the version 3.11.2 work so I will not complain

**Comment by ZhReimu** [comment] 2021-09-27 14:14
It works with version `3.11.0 4e8cd09ef0412dfc7b148b7639a692e20e4fd6dd`

**Comment by code-asher** [comment] 2021-09-27 18:16
Hmm, might be because our marketplace does not have the latest Python
extension.

Switching to Open VSX may resolve the issue.

**Comment by jsjoeio** [comment] 2021-09-27 18:59
> In the meantime would an older version work and how would we go about that?

`yarn global add code-server@3.11.2` will let you install an older version.

@Clem0803 @ZhReimu are you able to install other extensions? Wondering if this is specific to the Python extension

**Comment by Clem0803** [comment] 2021-09-27 20:40
It is not specific to Python. I get this error everytime I try to install an extension
![Screenshot_20210922-195048_Termux](https://user-images.githubusercontent.com/48407049/134981759-3ebbafc2-1a97-4356-bd9a-9d11d6825422.jpg)

**Comment by jsjoeio** [comment] 2021-09-27 22:14
Hmm...I think something on code-server's side must be wrong because one of the extensions you tried — Material Icon Theme — [sets the VS Code version engine to be 1.51.0](https://github.com/PKief/vscode-material-icon-theme/blob/main/package.json#L8) or above so this should work 🤔

@code-asher any ideas?

**Comment by ZhReimu** [comment] 2021-09-28 02:42
> > In the meantime would an older version work and how would we go about that?
> 
> `yarn global add code-server@3.11.2` will let you install an older version.
> 
> @Clem0803 @ZhReimu are you able to install other extensions? Wondering if this is specific to the Python extension

I also installed those extensions:
![image](https://user-images.githubusercontent.com/58155247/135013772-4a71a46d-a6a9-40ab-b0be-a3ea79634c27.png)
and one of theme 
![image](https://user-images.githubusercontent.com/58155247/135013852-5c177b32-4d68-4ae7-aa55-b452ae59051f.png)

**Comment by code-asher** [comment] 2021-09-28 18:52
I tried 3.12.0 on Termux and got the same issue.

It looks like in 1.60.0 there was a platform component added to the
compatibility check here:
https://github.com/microsoft/vscode/blob/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/src/vs/platform/extensionManagement/common/extensionGalleryService.ts#L562

The error message is still the same as before so it says it fails
because of the VS Code version but it might actually be because of this
new platform check.

Perhaps we can fix it by adding to the targets here:
https://github.com/microsoft/vscode/blob/e7d7e9a9348e6a8cc8c03f877d39cb72e5dfb1ff/src/vs/platform/extensionManagement/common/extensionManagement.ts#L21

**Comment by jsjoeio** [comment] 2021-09-28 19:53
Wow! Nice find  🔥 cc @TeffenEllis (just so you see this). 

> Perhaps we can fix it by adding to the targets here

Sound straightforward enough!

**Comment by Clem0803** [comment] 2021-09-30 12:54
I am not sure what to do to fix the problem.  Is there a command to write or something else?

**Comment by jsjoeio** [comment] 2021-09-30 18:28
@Clem0803 unfortunately, this is a bug on our end that needs to be fixed. In the meantime, I would suggest you downgrade code-server in your environment:

```shell
yarn global add code-server@3.11.2
```

**Comment by Clem0803** [comment] 2021-09-30 19:11
Ok thanks for your help and good luck to fix this problem

**Comment by helojo** [comment] 2022-03-31 03:17
I have the same probrem. How to do?
![8B22EE8A-42D6-4D2F-B383-2009CD97DDA7](https://user-images.githubusercontent.com/5379090/160969388-e9f0a0c1-c979-4d1c-84de-bfb2e5816718.png)

**Comment by helojo** [comment] 2022-04-01 01:17
> @helojo that's a compatibility issue. You'll need to install an older version of the Python extension.

@jsjoeio  thank you！I installed the old version "ms-python.python-2022.4.0.vsix".it got better. 
**but there is another problem:**
when I open the url on the ipad browser, there is no any display, and the screen is always white after input the password.But it's ok on Macos or windows.Has anyone else encountered this problem?

![IMG_E9AAAA813D13-1](https://user-images.githubusercontent.com/5379090/161175964-55d80820-9a8a-4be0-a792-5443328e3936.jpeg)

**Comment by jsjoeio** [comment] 2022-04-01 20:59
Hooray! Gonna close this for now.

**Closed by jsjoeio** 2022-04-01 20:59 UTC
Labels: bug, high-priority
