### ISSUE TITLE
Fix FOUC issues in dark mode

### ISSUE THREAD

**Issue by qupig** [coder/code-server#7077] opened 2024-11-12 18:21 UTC
Currently, after selecting the dark theme, every operation such as opening/closing a folder will produce a brief full-screen white screen flicker i.e. `FOUC (Flash of Unstyled Content)`, which is very unfriendly to the eyes.

An additional question is that when the system/browser is in dark mode, the light theme is always the default when entering `code-server`. I always have to choose it manually. Maybe the matching theme should also be automatically applied?

**Comment by code-asher** [comment] 2024-11-12 19:34
These are probably best solved upstream, we are just wrapping VS Code's HTML.

That said, having to select the theme multiple times sounds like a bug, and it could be a problem created by our patches.  We patch the theme to be stored on the remote server, so as long as the config is not deleted from there it should keep using the same theme.

**Comment by code-asher** [comment] 2024-11-12 19:35
Actually we may need to solve it here anyway because we should also style the login page with the current theme.

**Comment by code-asher** [comment] 2024-11-12 19:37
I modified https://github.com/coder/code-server/issues/3019 to include styling the VS Code page before it loads, since it will all be the same work, and will close this one as a duplicate.

**Closed by code-asher** 2024-11-12 19:37 UTC
Labels: bug, enhancement

**Comment by code-asher** [comment] 2024-11-13 18:31
Ahh I see.  This is expected behavior, in that case.  You could work around it by seeding each instance with a `settings.json` file that has the theme set.
