### ISSUE TITLE
Cannot select text on iPad with trackpad / mouse

### ISSUE THREAD

**Issue by Prushka** [coder/code-server#3203] opened 2021-04-24 23:23 UTC
## OS/Web Information

- Web Browser: Safari (with / without PWA) / Chrome
- Local OS: iOS
- Remote OS: Ubuntu Server
- Remote Architecture: Arm64
- `code-server --version`: 3.9.3

## Steps to Reproduce

1. Connect a mouse or trackpad to iPad.
2. Select any text in the editor with Mouse / Trackpad (i.e., press the Trackpad or Mouse left button and move around).

## Expected

The text should be selected. 

## Actual

Only the cursor gets moved around. Nothing gets selected.

## Notes

This works on some other implementations (e.g., Gitpod). 

This issue can be reproduced in VS Code: No

**Comment by auebersohn** [comment] 2021-04-25 18:38
I am still on 3.9.2, but experiencing the same issue.

iOS device: iPad Pro 2018 model, running iOS 14.5
Browser: Safari
Remote server: Debian Buster (10.9)
Remote arch: arm64

Cannot select text using a magic keyboard’s trackpad, a mouse connected via bluetooth, or via the touchscreen. Like above, just sets the text cursor location on the first click, and then the device cursor just continues to move w/o highlighting when you start moving the cursor to select.

**Comment by reticulatingsplines** [comment] 2021-04-25 19:01
Unsurprisingly, an upgrade to 
Duplicate of #

> I am still on 3.9.2, but experiencing the same issue.
> 
> iOS device: iPad Pro 2018 model, running iOS 14.5
> Browser: Safari
> Remote server: Debian Buster (10.9)
> Remote arch: arm64
> 
> Cannot select text using a magic keyboard’s trackpad, a mouse connected via bluetooth, or via the touchscreen. Like above, just sets the text cursor location on the first click, and then the device cursor just continues to move w/o highlighting when you start moving the cursor to select.

Unsurprisingly, can confirm an upgrade to 3.9.3 did not resolve.

**Comment by jsjoeio** [comment] 2021-04-26 17:36
I'm using code-server 3.9.3 with iPad Pro 2nd gen running iOS 14.5 with an Apple Magic keyboard and cannot reproduce your issue.

## Screenshot

https://user-images.githubusercontent.com/3806031/116125904-e6015500-a67a-11eb-8cad-4e44205c0ace.MP4

A couple questions:
- Could you post a [screen recording](https://support.apple.com/guide/ipad/take-a-screenshot-or-screen-recording-ipad08a40f3b/ipados) showing what's happening? 
- What mouse/trackpad are you using?

**Comment by Prushka** [comment] 2021-04-26 18:17
> I'm using code-server 3.9.3 with iPad Pro 2nd gen running iOS 14.5 with an Apple Magic keyboard and cannot reproduce your issue.
> 
> ## Screenshot
>  RPReplay_Final1619458341.MP4 
> A couple questions:
> 
> * Could you post a [screen recording](https://support.apple.com/guide/ipad/take-a-screenshot-or-screen-recording-ipad08a40f3b/ipados) showing what's happening?
> * What mouse/trackpad are you using?

Thanks for the reply. Were you trying to double click the text? 

This is what I meant:

### code-server:


https://user-images.githubusercontent.com/39870883/116131129-0096f680-a69a-11eb-98e3-d3ab1827701a.mp4


### expected behavior (Gitpod):


https://user-images.githubusercontent.com/39870883/116131136-0260ba00-a69a-11eb-856b-516f6d9d8de7.mp4

**Comment by jsjoeio** [comment] 2021-04-26 18:42
> double click the text
Yes!

Ah! Seeing those side-by-side makes it a bit more clear - sorry for my misunderstanding. Okay now this is really interesting 🤔 When I try it on my code-server deployment running on [Railway](https://railway.app/), it works as expected (I can select text). But when I try using running with `code-server --link` on my laptop and accessing on my iPad, I see the bug/issue.

## Screenshot

https://user-images.githubusercontent.com/3806031/116134096-5d87b200-a684-11eb-9ec5-084c2011eaaf.MP4

I have no idea why it would work with one environment but not the other. 

cc @oxy @code-asher - any ideas?

**Comment by code-asher** [comment] 2021-04-26 18:43
Is Railway running a different version?

**Comment by jsjoeio** [comment] 2021-04-26 20:29
Nope. Running 3.9.3 locally on laptop and [in Railway](https://github.com/jsjoeio/code-server-railway2/blob/main/Dockerfile#L1).

**Comment by reticulatingsplines** [comment] 2021-04-26 20:47
Curious if others experiencing this issue are also on iOS 14.5 - seems like the most obvious thing that's changed recently.

PS, apologies if this is already obvious to the majority of people who'd be using code-server in the first place, but a simple (and hopefully temporary!) workaround is to hold shift, click at one end of the desired selection, click the other end, and release shift.

**Comment by knavels** [comment] 2021-06-07 09:35
I have the same problem on 14.5 even in PWA mode that the scroll is working but I can’t select text, text selection works in terminal but not in editor

**Comment by fabianSorn** [comment] 2021-06-08 14:59
For me on 14.5, the text selection works neither in the editor nor in the terminal window (iOS 14.5.1).

**Comment by knavels** [comment] 2021-06-10 11:03
Here, I found a workaround for scrolling and text selection code-server on ipad pro without pain and in the browser

- in the keyboard settings turn on “shortcut” for all keyboards to enable scrolling when you’re in broaswer
- download “lunascape” browser from appstore
- in the lunascape settings change User Agent to “Galaxy NEXUS (AOSP)”
- do not use desktop mode
- as long as keyboard bar (mini keyboard bar not the whole keyboard) is apear and with that User Agent I could scroll, select text like normal

Thanks to Apple that made us to discover such a brilliant things and brings us such a fantastic user experiences, I have Samsung Dex, code-server works without any pain, I don’t know why people can make music, edit videos and other stuff on ipad but there is no “Browser-for-modern-human” on ios 🤦🏻🤦🏻 😄

**Comment by janiversen** [comment] 2021-06-15 17:21
I have the issue with iPadOs 14.6 (and earlier 14.5) as frontend, and a raspberry pi 4 with buster as backend (using the “official” install.sh).

If anybody can give me a code pointer, then I am more happy to try and debug my way through it and isolate the culpit (as mentioned in my other PR that was closed as a duplicate).

**Comment by jsjoeio** [comment] 2021-06-15 17:56
> If anybody can give me a code pointer, then I am more happy to try and debug my way through it and isolate the culpit (as mentioned in my other PR that was closed as a duplicate).

Thanks for offering to chip in! If I were to dive into this, here's where I would start:
- see if this can be reproduced in [GitHub Codespaces](https://github.com/features/codespaces). If it can, file a bug there.
- see if this can be reproduced in [Xterm.js](https://xtermjs.org/) (this is the library used by VSCode to render the terminal)

Start there and see what you find. If it's not reproducible in either, then it's specific to code-server and we can provide more direction there.

**Comment by janiversen** [comment] 2021-06-16 08:54
I am on the waiting list for Github Codespaces, hoping to get access soon, but in the meantime I will test term.js.

**Comment by sionicion** [comment] 2021-06-24 18:28
GitHub Codespaces doesn’t have this issue, I just checked.

**Comment by janiversen** [comment] 2021-06-24 18:47
thanks, so this is a code-server issue.

**Comment by jsjoeio** [comment] 2022-02-22 20:39
@nickpoorman Great! Can you open an issue upstream?

**Closed** 2022-02-22 20:39 UTC
Labels: bug, os-ios, needs-investigation, upstream:vscode

**Comment by kevin-king** [comment] 2023-03-25 01:21
On iPadOS 16.3.1, iPad Pro 11in 4th gen, code-server 1.76.1 arm64

I've noticed that the actions that consistently reproduce this issue is contained to 3 scenarios:
1. Your code-server is in **full screen** and you (even slightly) **reveal the stage manager** on the left
2. Your code-server is in **full screen** and you (even slightly) **reveal the dock** at the bottom
3. Your code-server is in **full screen** and you return to the **home screen**

After lots of testing I don't believe the issue occurs under any conditions. The Command Center and Notifications menu don't seem to trigger it even when in full screen mode.

One interesting thing is that my Apple Pencil always works for selection. My mouse and fingers do not.

The conditions above all appear to hold true regardless of whether Stage Manager is on or off. The also seem to hold true regardless of whether you're fetching code-server from in a regular Safari tab or from inside a PWA.

**Comment by dmuiX** [comment] 2023-08-31 18:56
i can confirm. I have the same issue.
apple pencil selection works, with touchpad not.

**Comment by maekporydzaj** [comment] 2023-12-20 17:18
Confirmed. Same issue with iPhone. Unable show popup with select.

**Comment by code-asher** [comment] 2023-12-21 19:36
I think this is the upstream issue: https://github.com/microsoft/vscode/issues/167151

**Comment by ivandamyanov** [comment] 2024-03-28 13:22
Doesn't work on a Samsung Android tablet in Chrome.  It's impossible to select text in the terminal, switched theme to light but it's the same and experimental web platform features flag is off

**Comment by code-asher** [comment] 2024-03-29 22:04
@ivandamyanov make sure to leave any reproductions with Codespaces upstream (https://github.com/microsoft/vscode/issues) if you have not already.
