### ISSUE TITLE
[Bug]: HTML / TypeScript and JavaScript Language Features Error

### ISSUE THREAD

**Issue by oognuyh** [coder/code-server#5087] opened 2022-04-11 13:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome, Firefox
- Local OS: Windows 11
- Remote OS: Ubuntu 20.04 (WSL2)
- Remote Architecture: amd64
- `code-server --version`: 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2

### Steps to Reproduce

1. Open *.html -> HTML Language Server server crashed(Cannot find module 'typescript')
2. Open *.js, *.ts ->  VSCode's tsserver was deleted by another application error + Could not find bundled tsserver.js

### Expected

No alerts, working fine

### Actual

1. Open *.html

![image](https://user-images.githubusercontent.com/48203569/162734527-1fdec8a3-c718-48d3-a778-ec4fa6d6dd79.png)

```
Error: Cannot find module 'typescript'
```

2. Open *.ts or *.js

![image](https://user-images.githubusercontent.com/48203569/162735276-5772f1d5-3c75-4700-923f-5f4caed9d955.png)

### Logs

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'typescript'
Require stack:
\- /usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.5034 (/usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1335953)
    at n (/usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5906 (/usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1310082)
    at n (/usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145)
    at Object.5704 (/usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1323446)
    at n (/usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js:1:1336145) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/code-server/lib/vscode/extensions/html-language-features/server/dist/node/htmlServerMain.js'
  ]
}
```

```
Uncaught (in promise) Canceled: Canceled
    E http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:8
    cancel http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:75
    cancel http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:75
    unwatch http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1198
    u http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1198
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    dispose http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:690
    destroyModel http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:732
    dispose http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1558
    destroyReferencedObject http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:2393
    destroyReferencedObject http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:2393
    D http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:17
    t http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:9
    dispose http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:17
    dispose http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1751
    promise callback*dispose http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1751
    setInput http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:2370
    editorPromise http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:2370
    E http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:75
    setInput http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:2370
    showChannel http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:2370
    onDidRegisterChannel http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1598
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    registerChannel http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1598
    $register http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1598
    _doInvokeHandler http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _invokeHandler http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _receiveRequest http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _receiveOneMessage http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    u http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    _receiveMessage http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    p http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    acceptChunk http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    o http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    onData http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:585
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    onload http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:585
workbench.web.main.js:8:1096
The HTML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. workbench.web.main.js:789:179061
[Extension Host] rejected promise not handled within 1 second: Error: Connection to server got closed. Server will not be restarted. workbench.web.main.js:75:453
[Extension Host] stack trace: Error: Connection to server got closed. Server will not be restarted.
	at b.handleConnectionClosed (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:462016)
	at b.handleConnectionClosed (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:522108)
	at t (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:459791)
	at invoke (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:382922)
	at o.fire (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:383683)
	at Q (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:370567)
	at invoke (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:382922)
	at o.fire (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:383683)
	at d.fireClose (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:391564)
	at ChildProcess.<anonymous> (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:402530)
	at ChildProcess.emit (events.js:412:35)
	at maybeClose (internal/child_process.js:1058:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) workbench.web.main.js:75:453
[[object Object]]Connection to server got closed. Server will not be restarted. workbench.web.main.js:1927:24892
    $onExtensionRuntimeError http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1927
    _doInvokeHandler http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _invokeHandler http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _receiveRequest http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _receiveOneMessage http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    u http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    _receiveMessage http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    p http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    acceptChunk http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    o http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    onData http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:585
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    onload http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:585
Error: Connection to server got closed. Server will not be restarted.
	at b.handleConnectionClosed (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:462016)
	at b.handleConnectionClosed (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:522108)
	at t (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:459791)
	at invoke (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:382922)
	at o.fire (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:383683)
	at Q (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:370567)
	at invoke (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:382922)
	at o.fire (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:383683)
	at d.fireClose (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:391564)
	at ChildProcess.<anonymous> (/usr/lib/code-server/lib/vscode/extensions/html-language-features/client/dist/node/htmlClientMain.js:1:402530)
	at ChildProcess.emit (events.js:412:35)
	at maybeClose (internal/child_process.js:1058:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5) workbench.web.main.js:1927:24928
    $onExtensionRuntimeError http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1927
    _doInvokeHandler http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _invokeHandler http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _receiveRequest http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    _receiveOneMessage http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    u http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:1541
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    _receiveMessage http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    p http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    acceptChunk http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    o http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:83
    onData http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:585
    fire http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:67
    onload http://localhost:8080/static/out/vs/workbench/workbench.web.main.js:585
```

```
workbench.web.main.js:789 VS Code's tsserver was deleted by another application such as a misbehaving virus detection tool. Please reinstall VS Code.
onDidChangeNotification @ workbench.web.main.js:789
(anonymous) @ workbench.web.main.js:789
fire @ workbench.web.main.js:67
addNotification @ workbench.web.main.js:791
notify @ workbench.web.main.js:1598
(anonymous) @ workbench.web.main.js:1534
_showMessage @ workbench.web.main.js:1534
$showMessage @ workbench.web.main.js:1534
_doInvokeHandler @ workbench.web.main.js:1541
_invokeHandler @ workbench.web.main.js:1541
_receiveRequest @ workbench.web.main.js:1541
_receiveOneMessage @ workbench.web.main.js:1541
(anonymous) @ workbench.web.main.js:1541
fire @ workbench.web.main.js:67
fire @ workbench.web.main.js:83
_receiveMessage @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:83
fire @ workbench.web.main.js:67
acceptChunk @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:585
fire @ workbench.web.main.js:67
E._fileReader.onload @ workbench.web.main.js:585
workbench.web.main.js:1927 [[object Object]]Could not find bundled tsserver.js
$onExtensionRuntimeError @ workbench.web.main.js:1927
_doInvokeHandler @ workbench.web.main.js:1541
_invokeHandler @ workbench.web.main.js:1541
_receiveRequest @ workbench.web.main.js:1541
_receiveOneMessage @ workbench.web.main.js:1541
(anonymous) @ workbench.web.main.js:1541
fire @ workbench.web.main.js:67
fire @ workbench.web.main.js:83
_receiveMessage @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:83
fire @ workbench.web.main.js:67
acceptChunk @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:585
fire @ workbench.web.main.js:67
E._fileReader.onload @ workbench.web.main.js:585
workbench.web.main.js:1927 Error: Could not find bundled tsserver.js
	at l.get bundledVersion [as bundledVersion] (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:505534)
	at l.get defaultVersion [as defaultVersion] (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:504672)
	at new u (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:501694)
	at new w (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:517792)
	at new y (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:509005)
	at r._getValue (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:460375)
	at r.get value [as value] (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:555853)
	at p (:8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:460751)
	at :8080/usr/lib/code-server/lib/vscode/extensions/typescript-language-features/dist/extension.js:1:460909
	at l.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at :8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:69680
	at l.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at v.acceptDocumentsAndEditorsDelta (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:74565)
	at v.$acceptDocumentsAndEditorsDelta (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:72836)
	at i._doInvokeHandler (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13801)
	at i._invokeHandler (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:13485)
	at i._receiveRequest (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:12147)
	at i._receiveOneMessage (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:10825)
	at :8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:97:8934
	at l.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at s.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
	at :8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:34512
	at l.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at s.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:19002)
	at a._receiveMessage (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:23583)
	at :8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:21117
	at l.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at _.acceptChunk (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:15833)
	at :8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:72:14963
	at l.fire (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:64:1712)
	at f._processReadQueue (:8080/usr/lib/code-server/lib/vscode/out/vs/workbench/services/extensions/node/extensionHostProcess.js:112:21320)
$onExtensionRuntimeError @ workbench.web.main.js:1927
_doInvokeHandler @ workbench.web.main.js:1541
_invokeHandler @ workbench.web.main.js:1541
_receiveRequest @ workbench.web.main.js:1541
_receiveOneMessage @ workbench.web.main.js:1541
(anonymous) @ workbench.web.main.js:1541
fire @ workbench.web.main.js:67
fire @ workbench.web.main.js:83
_receiveMessage @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:83
fire @ workbench.web.main.js:67
acceptChunk @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:83
(anonymous) @ workbench.web.main.js:585
fire @ workbench.web.main.js:67
E._fileReader.onload @ workbench.web.main.js:585
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

1. I tried without extension after reinstall but same.
2. When I connect WSL2 using VSCode(Ver. 1.66.1) Remote, it works.
3. However, I downgraded code-server from 4.2.0 693b1fac04524bb0e0cfbb93afc85702263329bb with Code 1.64.2 to 4.1.0 9e620e90f53fb91338a2ba1aaa2e556d42ae52d5 with Code 1.63.0 and it works fine.

**Comment by jsjoeio** [comment] 2022-04-12 00:00
Sounds like a duplicate of https://github.com/coder/code-server/issues/5019 which will be fixed in the next release!

**Closed by jsjoeio** 2022-04-12 00:00 UTC
Labels: bug, triage
