### ISSUE TITLE
"+" in dir wont open

### ISSUE THREAD

**Issue by killerdevildog** [coder/code-server#5483] opened 2022-08-20 04:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: The Legendary: Fire Fox
- Local OS: The Best OS: Ubuntu Intel X64 
- Remote OS: The Better Than Best OS: Debian 11 I686
- Remote Architecture: Intel Atom I686
- `code-server --version`: 4.5.2

### Steps to Reproduce

1. on host machine make a dir with '+' in the name ie mkdir dir_c++
2. Start server on host machine and port forward into remote machine through ssh
3. on remote machine open the legendary fire fox 
4. go to 127.0.0.1:(what ever port your boat configured it too)
5. log in using the password you configured it to be
6. open application menu in top left and go file->open foler
7. follow the path to the folder you want 
8. the error says that the workspace does not exist

### Expected

It should open the directory path 

### Actual

it shows a dialoge box saying that "The workspace does not exist. Please select another workspace to open." with options to Cancel and Open Workspace...

### Logs

[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:45] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:45] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:45] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:45] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:45] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:46] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:46] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:46] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:46] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [File Watcher (node.js)] Request to start watching: /home/killer/.local/share/code-server/User/snippets (excludes: /home/killer/.local/share/code-server/extensions/**, includes: <all>)
[22:36:46] [File Watcher (node.js)] Started watching: '/home/killer/.local/share/code-server/User/snippets'
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:46] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:46] Started scanning system extensions
[22:36:46] Started scanning user extensions
[22:36:46] Scanned user extensions: 1
[22:36:46] Scanned system extensions: 88
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/systemExtensionsCache.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/systemExtensionsCache.json)
[22:36:46] [File Watcher (node.js)] [raw] ["change"] systemExtensionsCache.json
[22:36:46] [File Watcher (node.js)] [CHANGED] /home/killer/.local/share/code-server/User/systemExtensionsCache.json
[22:36:46] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/systemExtensionsCache.json)
[22:36:46] [File Watcher (node.js)] [raw] ["change"] systemExtensionsCache.json
[22:36:46] [File Watcher (node.js)] [CHANGED] /home/killer/.local/share/code-server/User/systemExtensionsCache.json
[22:36:46] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:46] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/systemExtensionsCache.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/systemExtensionsCache.json)
[22:36:46] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/systemExtensionsCache.json)
[22:36:46] [File Watcher (node.js)] >> normalized [CHANGED] /home/killer/.local/share/code-server/User/systemExtensionsCache.json
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json)
[22:36:47] [Disk FileSystemProvider]: open() - storing lock for handle 46 (/home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json)
[22:36:47] [File Watcher (node.js)] [raw] ["change"] customBuiltinExtensionsCache.json
[22:36:47] [File Watcher (node.js)] [CHANGED] /home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json
[22:36:47] [File Watcher (node.js)] [raw] ["change"] customBuiltinExtensionsCache.json
[22:36:47] [File Watcher (node.js)] [CHANGED] /home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json
[22:36:47] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 46
[22:36:47] [Disk FileSystemProvider]: close() - disposing lock for handle 46
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json)
[22:36:47] [File Watcher (node.js)] >> normalized [CHANGED] /home/killer/.local/share/code-server/User/customBuiltinExtensionsCache.json
[22:36:47] Started scanning user extensions
[22:36:47] Scanned user extensions: 1
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: open() - storing lock for handle 46 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 46
[22:36:47] [Disk FileSystemProvider]: close() - disposing lock for handle 46
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] Started scanning system extensions
[22:36:47] Started scanning user extensions
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - request to acquire resource lock (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - new resource lock created (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: open() - storing lock for handle 22 (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] Scanned user extensions: 1
[22:36:47] Scanned system extensions: 88
[22:36:47] [Disk FileSystemProvider]: close() - resource lock removed from handle-lock map 22
[22:36:47] [Disk FileSystemProvider]: close() - disposing lock for handle 22
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock dispose() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock removed from resource-lock map (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] [Disk FileSystemProvider]: createResourceLock() - resource lock barrier open() (/home/killer/.local/share/code-server/User/caches/CachedConfigurations/folder/-1222ab71/configuration.json)
[22:36:47] Started scanning user extensions
[22:36:47] Scanned user extensions: 1
[2022-08-20T04:36:49.506Z] debug child:22253 disposing [38;2;140;140;140m{"code":"SIGINT"}[0m

### Screenshot/Video

![Screenshot from 2022-08-19 22-44-25](https://user-images.githubusercontent.com/31830590/185729296-9f9e0e41-8865-46ee-8186-318eb4e57f88.png)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

I use ssh to port it over to the other machine.

**Comment by jsjoeio** [comment] 2022-08-22 16:27
I was able to reproduce this locally with 4.6.0

https://user-images.githubusercontent.com/3806031/185970810-d2d8668b-bd35-44de-84c2-07683ce9f3bc.mov

I could not reproduce in VS Code, github.dev, or Codespaces. That means this is specific to code-server.

**Comment by code-asher** [comment] 2024-07-12 01:04
This seems to be fixed in the latest version.

**Closed by code-asher** 2024-07-12 01:04 UTC
Labels: bug
