### ISSUE TITLE
UI issue: interruptions when naming new files or renaming them

### ISSUE THREAD

**Issue by mcg1969** [coder/code-server#4385] opened 2021-10-21 16:27 UTC
Hey folks, I apologize that there may not be a lot here to help reproduce the issue but I would be happy to do more specific tests if offered instructions. Thank you!

## OS/Web Information

- Web Browser: Chrome 95.0.4638.54 
- Local OS: macOS 11.6
- Remote OS: RHEL ubi8.4
- Remote Architecture: Running in a container, behind an nginx proxy
- `code-server --version`: 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2

## Steps to Reproduce

1. Click the "new file" icon
2. Start typing a filename

OR

1. Right-click on a file
2. Select "Rename"
3. Start typing a filename

## Expected

The UI patiently waits for me to finish typing

## Actual

After a couple of seconds, it closes the file naming box on me, before I have finished typing, and if I continue typing, the text is entered into what looks like a native VSCode filename filtering/search UI

## Logs

The code-server-stderr and code-server-stdout logs are empty

Debug logs attached
```
# Command line: /tools/vscode/bin/code-server --log debug --auth none --disable-update-check --user-data-dir /opt/continuum/.config/code-server --extensions-dir /tools/vscode/extensions --disable-telemetry --port 7050 --host 0.0.0.0 /opt/continuum/project
[2021-10-21T16:10:47.615Z] info  Wrote default config file to ~/.config/code-server/config.yaml
[2021-10-21T16:10:48.268Z] info  code-server 3.12.0 4cd55f94c0a72f05c18cea070e10b969996614d2
[2021-10-21T16:10:48.270Z] info  Using user-data-dir ~/.config/code-server
[2021-10-21T16:10:48.301Z] info  Using config file ~/.config/code-server/config.yaml
[2021-10-21T16:10:48.302Z] info  HTTP server listening on http://0.0.0.0:7050 
[2021-10-21T16:10:48.302Z] info    - Authentication is disabled 
[2021-10-21T16:10:48.302Z] info    - Not serving HTTPS 
[2021-10-21T16:10:50.976Z] debug forking vs code...
[2021-10-21T16:10:51.623Z] debug setting up vs code...
[2021-10-21T16:10:51.628Z] debug vscode got message from code-server [38;2;140;140;140m{"type":"init"}[0m
[2021-10-21T16:10:52.969Z] debug setting up vs code...
[2021-10-21T16:10:52.970Z] debug vscode got message from code-server [38;2;140;140;140m{"type":"init"}[0m
[2021-10-21T16:10:54.749Z] debug vscode got message from code-server [38;2;140;140;140m{"type":"socket"}[0m
[2021-10-21T16:10:54.752Z] debug protocol Initiating handshake... [38;2;140;140;140m{"token":"d4e38fde-1169-4e2b-b374-d7f87382b5c1"}[0m
[2021-10-21T16:10:54.801Z] debug protocol Handshake completed [38;2;140;140;140m{"token":"d4e38fde-1169-4e2b-b374-d7f87382b5c1"}[0m
[2021-10-21T16:10:54.802Z] debug management Connecting... [38;2;140;140;140m{"token":"d4e38fde-1169-4e2b-b374-d7f87382b5c1"}[0m
[2021-10-21T16:10:54.802Z] debug vscode 1 active management connection(s)
[2021-10-21T16:10:55.400Z] debug vscode got message from code-server [38;2;140;140;140m{"type":"socket"}[0m
[2021-10-21T16:10:55.400Z] debug protocol Initiating handshake... [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:10:55.563Z] debug protocol Handshake completed [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:10:55.564Z] debug exthost Connecting... [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:10:55.565Z] debug exthost Getting NLS configuration... [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:10:55.565Z] debug vscode 1 active exthost connection(s)
[2021-10-21T16:10:55.565Z] debug exthost Spawning extension host... [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:10:55.574Z] debug exthost Waiting for handshake... [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:10:56.686Z] debug exthost Handshake completed [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:10:56.686Z] debug exthost Sending socket [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:11:50.974Z] debug 2 active connections
[2021-10-21T16:12:50.975Z] debug 2 active connections
[2021-10-21T16:13:50.978Z] debug 2 active connections
[2021-10-21T16:14:50.982Z] debug 2 active connections
[2021-10-21T16:15:50.985Z] debug 2 active connections
[2021-10-21T16:16:50.986Z] debug 2 active connections
[2021-10-21T16:17:50.989Z] debug 2 active connections
[2021-10-21T16:17:53.647Z] debug management Disposing... [38;2;140;140;140m{"token":"d4e38fde-1169-4e2b-b374-d7f87382b5c1"}[0m
[2021-10-21T16:17:53.648Z] debug management Closed [38;2;140;140;140m{"token":"d4e38fde-1169-4e2b-b374-d7f87382b5c1"}[0m
[2021-10-21T16:17:53.768Z] debug exthost Got disconnected message [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:17:53.768Z] debug exthost Disconnected [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:17:54.691Z] debug exthost Exited [38;2;140;140;140m{"code":0,"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:17:54.691Z] debug exthost Disposing... [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:17:54.692Z] debug exthost Closed [38;2;140;140;140m{"token":"465008a6-0cfb-4d2b-adac-5e263d893ae6"}[0m
[2021-10-21T16:18:05.517Z] debug setting up vs code...
[2021-10-21T16:18:05.518Z] debug vscode got message from code-server [38;2;140;140;140m{"type":"init"}[0m
[2021-10-21T16:18:08.944Z] debug vscode got message from code-server [38;2;140;140;140m{"type":"socket"}[0m
[2021-10-21T16:18:08.946Z] debug protocol Initiating handshake... [38;2;140;140;140m{"token":"ce98b4ae-27d9-4055-8a89-afa21ae981b6"}[0m
[2021-10-21T16:18:09.122Z] debug protocol Handshake completed [38;2;140;140;140m{"token":"ce98b4ae-27d9-4055-8a89-afa21ae981b6"}[0m
[2021-10-21T16:18:09.123Z] debug management Connecting... [38;2;140;140;140m{"token":"ce98b4ae-27d9-4055-8a89-afa21ae981b6"}[0m
[2021-10-21T16:18:09.123Z] debug vscode 1 active management connection(s)
[2021-10-21T16:18:10.301Z] debug vscode got message from code-server [38;2;140;140;140m{"type":"socket"}[0m
[2021-10-21T16:18:10.301Z] debug protocol Initiating handshake... [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[2021-10-21T16:18:10.448Z] debug protocol Handshake completed [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[2021-10-21T16:18:10.448Z] debug exthost Connecting... [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[2021-10-21T16:18:10.449Z] debug exthost Getting NLS configuration... [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[2021-10-21T16:18:10.449Z] debug vscode 1 active exthost connection(s)
[2021-10-21T16:18:10.449Z] debug exthost Spawning extension host... [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[2021-10-21T16:18:10.462Z] debug exthost Waiting for handshake... [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[2021-10-21T16:18:11.252Z] debug exthost Handshake completed [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[2021-10-21T16:18:11.252Z] debug exthost Sending socket [38;2;140;140;140m{"token":"f4588fc3-b1f0-4da6-8dd5-f7c0ca384f94"}[0m
[IPC Library: Pty Host]  INFO Persistent process "1": Replaying 8920 chars and 1 size events
[2021-10-21T16:18:50.992Z] debug 2 active connections
[2021-10-21T16:19:50.995Z] debug 2 active connections
[2021-10-21T16:20:50.998Z] debug 2 active connections
[2021-10-21T16:21:51.001Z] debug 2 active connections
[2021-10-21T16:22:51.005Z] debug 2 active connections
[2021-10-21T16:23:51.008Z] debug 2 active connections
```

## Notes

This issue can be reproduced in VS Code: Unknown

**Comment by jsjoeio** [comment] 2021-10-29 18:25
>  I am putting code-server behind a proxy and in an iframe. If I forego the iframe alone it seems fine, so I suspect something CORS-related

Ahhh...okay so this is environment specific then. @code-asher any ideas on why this might be happening with a proxy and/or how it could be related to CORS? I'm drawing blanks

**Comment by code-asher** [comment] 2021-10-29 20:27
Nothing off the top of my head, I will try to reproduce in an iframe and
see what happens.

**Comment by code-asher** [comment] 2021-11-04 19:58
No worries, I have not had the chance to debug yet as we are working on
getting the next release ready but hopefully soon after that.  Iframe
usage is something we employ as well so I want to test it anyway. :)

**Comment by mcg1969** [comment] 2022-02-04 22:00
@code-asher I was finally able to create a screen recording! I hope this helps spur some suggestions about the kind of debug logs and/or configuration information that may help debug

https://user-images.githubusercontent.com/2797735/152608974-d416076f-4b84-4bca-9bfc-d45fca49bfa3.mp4

.

**Comment by code-asher** [comment] 2022-03-10 20:44
Thank you for the recording!  Sorry I let this slip by me.  I played around with 4.0.2 in an iframe but for the life of me have not been able to reproduce.  I wonder if there is anything in the browser logs although I doubt it.  Looks like something steals focus and when the file is created on input blur.

I tried Firefox and Chromium, only other difference is that I am on Linux but seems unlikely to be OS-related.  @jsjoeio any idea if it works for you in an iframe?

Do you have any browser extensions installed that might be doing something funky?

The only other idea I have is that there is something specific about the way code-server is being embedded in your case.

**Comment by mcg1969** [comment] 2022-03-10 20:54
This is consistently reproducible in my setup across multiple installations so I am suspecting something in our proxy configuration

**Comment by jsjoeio** [comment] 2022-03-11 19:22
> I tried Firefox and Chromium, only other difference is that I am on Linux but seems unlikely to be OS-related. @jsjoeio any idea if it works for you in an iframe?

I tested in the Brave PWA on macOS and could not reproduce either unfortunately. 

## Video

https://user-images.githubusercontent.com/3806031/157937023-5a0b927f-80cb-4631-9d50-eaa1d0b9e50d.mov

**Comment by mcg1969** [comment] 2022-08-19 20:05
Hey folks, I recently pulled down a newer version of code-server, and this problem... is gone. We haven't changed our proxy, so I can't take credit for this. And you may not know what changes you may have made. But I personally don't dwell on such questions!

**Comment by jsjoeio** [comment] 2022-08-19 20:49
Hooooooray! Thanks for following up and confirming @mcg1969 - we appreciate that a ton. Closing now.

**Closed by jsjoeio** 2022-08-19 20:49 UTC
Labels: needs-investigation
