### ISSUE TITLE
Image not showing up

### ISSUE THREAD

**Issue by ggvick** [coder/code-server#4658] opened 2021-12-24 06:47 UTC
- Web Browser: tested on both Brave and safari 
- Local OS: macOS big sur 11.6
- Remote OS: ubuntu 20.04 LTS
- Remote Architecture: 64 bit
- `code-server --version`: 3.12

## Steps to Reproduce

1. Open any png/jpg image

## Expected

It shows me the image selected 

## Actual

no image shows up, its just blank and says nothing.

Nothing shows up. No logs to provide for this because there are no errors, even with the debug.

I uploaded an image that I know works because I previewed it  on my device before uploading. It still did not show.

## Screenshot

<img src="https://cdn.upload.systems/uploads/VDqWBh2n.png">
<img src="https://cdn.upload.systems/uploads/bdYO9fSj.png">
<img src="https://cdn.upload.systems/uploads/2Y1iKOpA.png">

## Notes
I uploaded an image that I know works because I previewed it on my device before uploading. It still did not show.

This issue can be reproduced in VS Code: Yes

**Comment by gogobd** [comment] 2021-12-31 10:49
I'm seeing the same issue:

code-server: v3.12.0
 VS Code: v1.60.0
Commit: 4cd55f94c0a72f05c18cea070e10b969996614d2
Date: 2021-09-15T19:34:37Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36

**Comment by jsjoeio** [comment] 2022-01-03 17:31
@ggvick Are there any logs in the browser console? Are you accessing via https?

**Comment by or0986113303** [comment] 2022-01-07 03:42
I'd saw the same issue wehn I opened any image file, 
the environment as below : 

- Remote OS : ubuntu 20.04 TLS
- Local OS : windows 10
- code-server --version : 4.0.1
- Browser : Chrome/96.0.4664.110

And capture console logs at browser as below : 

Activating extension 'hediet.vscode-drawio' failed: Cannot find module '/home/xxx/.local/share/code-server/extensions/hediet.vscode-drawio-999.0.0-alpha/dist/extension/index'
Require stack:
- /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/loader.js
- /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-amd.js
- /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-fork.js.
	$onExtensionActivationError	@	mainThreadExtensionService.ts:95
        _doInvokeHandler	@	rpcProtocol.ts:472
        _invokeHandler	@	rpcProtocol.ts:457
        _receiveRequest	@	rpcProtocol.ts:373
        _receiveOneMessage	@	rpcProtocol.ts:295
        (anonymous)	@	rpcProtocol.ts:160
        fire	@	event.ts:577
        fire	@	ipc.net.ts:511
        _receiveMessage	@	ipc.net.ts:869
        (anonymous)	@	ipc.net.ts:708
        fire	@	event.ts:577
        acceptChunk	@	ipc.net.ts:284
        (anonymous)	@	ipc.net.ts:245
        (anonymous)	@	browserSocketFactory.ts:197
        fire	@	event.ts:577
        C._fileReader.onload	@	browserSocketFactory.ts:81

**Comment by jsjoeio** [comment] 2022-01-07 20:49
Typically an image won't show up if you're accessing via HTTP (in which case service workers are disabled by the browser).

I tested in 4.0.1 and cannot reproduce. I'm going to close this for now since we don't have any new information and can't reproduce. If it's still an issue, please open a new bug report!

![image](https://user-images.githubusercontent.com/3806031/148605513-798621d9-f18b-4c65-82e2-51ee09a369ab.png)

**Closed by jsjoeio** 2022-01-07 20:49 UTC
