### ISSUE TITLE
[Feat]: Argument to disable Terminal

### ISSUE THREAD

**Issue by Merith-TK** [coder/code-server#6186] opened 2023-05-02 16:24 UTC
## What is your suggestion?
A simple command line argument to disable the integrated terminal

## Why do you want this feature?
There are certain instances where use of an terminal should not be allowed,
1) I am working on a minecraft mod that downloads and runs code-server on the server along side minecraft. As one can imagine, server hosts may not be entirely approving of direct shell access so this argument would be hard coded *enabled* in my mod

2) There may be times where you create an shared code-server workspace, and you do not want users of the code-server instance to have shell access.

## Are there any workarounds to get this functionality today?
Not that I am aware of
## Are you interested in submitting a PR for this?
No, I dont know TS or JS well enough to even conceptualize this code

**Comment by code-asher** [comment] 2023-05-02 21:42
I think we can close this as a duplicate of https://github.com/coder/code-server/issues/1937.

**Closed by code-asher** 2023-05-02 21:42 UTC
Labels: enhancement
