### ISSUE TITLE
After trying many methods,Windows could not install and start code-server successfully

### ISSUE THREAD

**Issue by Super1Windcloud** [coder/code-server#6892] opened 2024-07-10 06:19 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

WIndows 11
node20  
poweshell7 
node-gyp 10 
npm newest 

### Steps to Reproduce

After trying many methods,Windows could not install and start code-server successfully

### Expected

After trying many methods,Windows could not install and start code-server successfully

### Actual

After trying many methods,Windows could not install and start code-server successfully

### Screenshot/Video

f

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment] 2024-07-10 22:46
Yeah I think there are still some issues running on Windows.  I think this is a duplicate of https://github.com/coder/code-server/issues/1397 though.

**Closed by code-asher** 2024-07-10 22:46 UTC
Labels: bug, os-windows, triage
