### ISSUE TITLE
[Feat]: Allow custom path re-write on absproxy

### ISSUE THREAD

**Issue by rafaelnferreira** [coder/code-server#6898] opened 2024-07-13 10:30 UTC
## What is your suggestion?

Scenario: I've deployed code server under a path under your domain, the path structure is suffixed for each user id. For example:

```
http://mydomain.com/vscode --> app served here
http://mydomain.com/vscode/user1 --> url for individual user
```

While trying to serve a react app, I've noticed that requests were stripping out the `vscode/user1`, hence not hitting the webpack server in the react app with the right path.

This is the intended behaviour of [pathProxy.ts](https://github.com/coder/code-server/blob/6467c60166a53c758113bf9754d01e4e918654c9/src/node/routes/pathProxy.ts#L11)

Suggestion: Allows a generic argument to be set while starting the server that will accept a regex to enrich the path forwarded by the `absproxy` , eg something like: `--absproxy-prefix`, if this variable is set, the pathProxy will make use of it and forward the request after enrichment.

## Why do you want this feature?

To simplify the deployment structure and allow get rid of the intermediary proxy. 

I believe this feature will also benefit other users that are constrained on deployment code server using a proxy domain, as the path approach is simpler and easy to navigate from a enterprise security perspective.

## Are there any workarounds to get this functionality today?

Yes, uses one additional reverse proxy next to vs code server, however the UX isn't great.

## Are you interested in submitting a PR for this?

Yes

**Comment by code-asher** [comment] 2024-07-15 21:12
Would https://github.com/coder/code-server/issues/6770 cover this?

So right now we have:

- `/proxy/3000/path/` -> gets rewritten to `/path/`
- `/absproxy/3000/path/` -> no rewriting, gets forwarded as `/absproxy/3000/path/`

Then with the proposed base path flag, for example `--base-path /base/path`:

- `/proxy/3000/path/` -> no change, still gets rewritten to `/path/`
- `/absproxy/3000/path/` -> gets reritten to `/base/path/absproxy/3000/path/`

**Comment by code-asher** [comment] 2024-07-19 18:43
Cool, I will close this as a duplicate of https://github.com/coder/code-server/issues/6770.

It is not being scheduled, mostly our work here is just keeping the VS Code version up to date, but always happy to merge a PR!

**Closed by code-asher** 2024-07-19 18:43 UTC
Labels: enhancement
