### ISSUE TITLE
On browsers using webkitgtk, the editor is blank

### ISSUE THREAD

**Issue by abtye** [coder/code-server#6881] opened 2024-07-04 04:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:  epiphany 46.2-1
- Local OS: Arch Linux
- Remote OS: Arch Linux（Localhost）
- Remote Architecture: amd64
- `code-server --version`: 4.90.3

### Steps to Reproduce

1. Deploying code server on Arch Linux.
2. Run code-server.
3. Open `http://127.0.0.1:8080` in Epiphany.
4. Switch the theme of vscode to Monokai.
5. Edit a file.
6. You will see that the editor window is blank.

### Expected

The editor window should be dark.

### Actual

The editor window is blank.

### Logs

```shell
The solstice is too long, Github doesn't allow pasting here, I put it in the file, you can see it in the Note section.
```

### Screenshot/Video

![screenshot](https://github.com/coder/code-server/assets/123047756/3b27c178-80fc-4083-a332-38b0d129c1b3)

### Does this bug reproduce in native VS Code?

No, this works as expected in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

[code-serve.log](https://github.com/user-attachments/files/16093180/code-serve.log)

**This is related to the theme of vscode, and if you use a light color theme, there won't be this problem. My theme is `Monokai`.**

Epiphany is a browser for the gnome desktop environment, currently using `webkitgtk-6.0`. I have locally deployed code server on Arch Linux, and there are no issues opening it on `Firefox 127.0.2-1` and `Chromium 126.0.6478.126-1`. However, the editor page on Epiphany is blank.

Github codespace also has this issue, but I didn't have this issue when I opened `vscode. dev`.

Perhaps this is a CSS issue.

**Comment by code-asher** [comment] 2024-07-08 19:26
Very interesting.  I am not sure what could cause it, but since you can reproduce in Codespaces you might want to try opening the issue upstream (https://github.com/microsoft/vscode) where they might have a better idea.

**Comment by code-asher** [comment] 2024-07-11 23:56
I marked it as an upstream issue for now.

**Closed** 2024-07-11 23:57 UTC
Labels: bug, browser-safari, upstream:vscode
