### ISSUE TITLE
[Bug]: Terminal not showing up correct, and did not working at all after updating to 4.9.1 from 4.8.3

### ISSUE THREAD

**Issue by Dionysos211** [coder/code-server#5981] opened 2023-01-21 02:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Safari
- Local OS: MacOs
- Remote OS: CentOS
- Remote Architecture: amd64
- `code-server --version`: 4.9.1

### Steps to Reproduce

1.  update to 4.9.1
2. with extensions
3. just open Terminal Window -> bug
4. clean reinstalled 4.8.3
5. no extentions then with extentions
6.  just open Terminal Window -> NO bug
7.  clean reinstalled 4.9.1
8. no extentions
9. just open Terminal Window -> bug
10. installed 4.8.3 OVER 4.9.1 (download extract)
11. no extentions
12.  just open Terminal Window -> NO bug

### Expected

Terminal should work as normal something went wrong from 4.8.3 to 4.9.1

### Actual

actually I stay at 4.8.3 because 4.9.1 not works for me

### Does this issue happen in VS Code or GitHub Codespaces?

- [x] I cannot reproduce this in VS Code.
- [ ] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

if needed I can go on 4.9.1 and make screenshots
beause i have to check this marks before I can send it... I checked it, nut not true...

 I cannot reproduce this in VS Code. Guess u mean local...
 I CAN reproduce this in GitHub Codespaces. Terminal also bugged.

**Comment by Dionysos211** [comment] 2023-01-21 02:12
<img width="1405" alt="Bildschirmfoto 2023-01-21 um 03 10 56" src="https://user-images.githubusercontent.com/3465938/213838975-022e685e-a2ef-46c8-87a9-ca90e72f6f81.png">

here an image from GitHub Codespaces. where the same error is..
black
no prompt 
no typing possible
if I hit enter something happens (blinking)

**Comment by Dionysos211** [comment] 2023-01-21 02:33
Also happens on other devices.. also error on GitHub Codespaces..

But on my resetted Server to 4.8.3 everything works fine..

**Comment by Dionysos211** [comment] 2023-01-23 20:08
still the same behavior also in different Browsers and on different devices and different OS...

**Comment by benz0li** [comment] 2023-01-28 08:59
@Dionysos211 Can you reproduce this on my *reference deployment*?

1. Go to https://demo.jupyter.b-data.ch
2. Log in with your GitHub account
3. (Click "Start My Server")
4. Select image `R (jupyterlab/r/verse:latest)`
5. Open code-server
6. Terminal: Create New Terminal

👉 If the server does not start the first time, simply give it another try.

**Comment by benz0li** [comment] 2023-01-28 09:02
@Dionysos211 What have you set "Terminal > Integrated: Gpu acceleration" (`terminal.integrated.gpuAcceleration`) to?

Maybe related to:

* https://github.com/microsoft/vscode/issues/160070
* https://github.com/coder/code-server/pull/5535#issuecomment-1236281945

**Comment by Dionysos211** [comment] 2023-01-31 15:15
> @Dionysos211 Can you reproduce this on my _reference deployment_?
> 
> 1. Go to https://demo.jupyter.b-data.ch
> 2. Log in with your GitHub account
> 3. (Click "Start My Server")
> 4. Select image `R (jupyterlab/r/verse:latest)`
> 5. Open code-server
> 6. Terminal: Create New Terminal
> 
> 👉 If the server does not start the first time, simply give it another try.

Hi,
I have now tried this once.
Unfortunately, the same error picture appears.
The terminal shows up with artifacts and you don't have the possibility to enter anything.

I have posted a screenshot for comparison:
- Same system, same browser...
Left: My server, where everything still works under version 4.8.3
Middle: Your JupiterLab server, where the error occurs.
Right: The GitHub Codespace server where the error also occurs.
<img width="2173" alt="Bildschirmfoto 2023-01-31 um 16 02 13" src="https://user-images.githubusercontent.com/3465938/215799608-77f1bfff-55c5-48bb-9ed6-73c32aa4f6f1.png">

**Comment by Dionysos211** [comment] 2023-01-31 15:17
> @Dionysos211 What have you set "Terminal > Integrated: Gpu acceleration" (`terminal.integrated.gpuAcceleration`) to?
> 
> Maybe related to:
> 
> * [Safari not properly rendering Terminal after page reload microsoft/vscode#160070](https://github.com/microsoft/vscode/issues/160070)
> * [Update to 1.71 #5535 (comment)](https://github.com/coder/code-server/pull/5535#issuecomment-1236281945)

Hi,
in all my test scenarios the setting of:
"Terminal > Integrated: Gpu acceleration".
was set to "Auto".

**Comment by Dionysos211** [comment] 2023-01-31 15:24
mhm sorry @code-asher but, what do you mean with: "reporting upstream"

**Comment by benz0li** [comment] 2023-01-31 15:24
> Unfortunately, the same error picture appears.
> The terminal shows up with artifacts and you don't have the possibility to enter anything.

When I open it in Safari, the problem is not showing up:

<img width="1280" alt="Screenshot_demo jupyter b-data ch" src="https://user-images.githubusercontent.com/20233085/215802078-ec5dbcbd-fdb7-43d3-a2c2-4841f4f7c0fc.png">

**Comment by benz0li** [comment] 2023-01-31 15:32
> * Same system, same browser...

This problem is rather caused by your setup and/or browser than my *reference deployment* or GitHub Codespaces.

Unfortunately I can't help you any further. It may be a good idea to look for errors in the browser's console.  
👉 Safari: Develop > Show Web Inspector; Firefox: Tools > Browser Tools > Web Developer Tools

**Comment by Dionysos211** [comment] 2023-01-31 15:37
> > * Same system, same browser...
> 
> This problem is rather caused by your setup and/or browser than my _reference deployment_ or GitHub Codespaces.
> 
> Unfortunately I can't help you any further. It may be a good idea to look for errors in the browser's console. 👉 Safari: Develop > Show Web Inspector; Firefox: Tools > Browser Tools > Web Developer Tools

ok @benz0li  but why is everything running normally on my server with version 4.8.3 in the same browser with the same settings.
And when I updated my server to the latest version (I guess as the same on Codespace&Jupiterlab), I had the same problem on my server.

**Comment by benz0li** [comment] 2023-01-31 16:10
@Dionysos211 Try disabling GPU Acceleration.

Cross reference: https://github.com/microsoft/vscode/issues/163448#issuecomment-1283168671

**Comment by Dionysos211** [comment] 2023-01-31 16:22
@benz0li ok wow that worked, change from auto to off... but why xD (canvas mode did not worked)

**Comment by benz0li** [comment] 2023-01-31 16:31
@Dionysos211 Gern geschehen!

**Comment by benz0li** [comment] 2023-02-01 07:44
> @benz0li ok wow that worked, change from auto to off... but why xD (canvas mode did not worked)

@Dionysos211 If this resolves your problem, please close the issue.

Thank you.

**Closed** 2023-02-01 15:53 UTC
Labels: waiting-for-info

**Comment by code-asher** [comment] 2023-02-06 16:33
Sorry, was out last week.  Just for reference upstream is https://github.com/microsoft/vscode (thank you @benz0li for linking the issue upstream).  

Generally bugs that can be reproduced in Codespaces can be reported there since it means code-server is not involved (basically we just wrap VS Code web which is what Codespaces is running).

Glad you got it sorted!  Not sure why it worked in 4.8.3, hopefully the upstream issue gets it fixed.
