### ISSUE TITLE
[Bug]: Node v16 does not work with code-server

### ISSUE THREAD

**Issue by Default-01** [coder/code-server#5028] opened 2022-03-24 12:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS: Windows Server 19
- Remote OS:
- Remote Architecture:
- `code-server --version`: Latest

### Steps to Reproduce

When I run `yarn global add code-server` in a Git Bash I get this error saying it requires nodev14. but on my machine, I use v16 for other applications.

$ yarn global add code-server
yarn global v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "code-server > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
error C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\code-server: Command failed.
Exit code: 1
Command: sh ./postinstall.sh
Arguments:
Directory: C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\code-server
Output:
ERROR: code-server currently requires node v14.
./postinstall.sh: line 38: FORCE_NODE_VERSION: unbound variable
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

### Expected

Should just work

### Actual

it errors out

### Logs

$ yarn global add code-server
yarn global v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "code-server > @coder/logger@1.1.16" has unmet peer dependency "@google-cloud/logging@^4.5.2".
[4/4] Building fresh packages...
error C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\code-server: Command failed.
Exit code: 1
Command: sh ./postinstall.sh
Arguments:
Directory: C:\Users\Administrator\AppData\Local\Yarn\Data\global\node_modules\code-server
Output:
ERROR: code-server currently requires node v14.
./postinstall.sh: line 38: FORCE_NODE_VERSION: unbound variable
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.

### Does this issue happen in VS Code?

- [x] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [x] I am using HTTPS.

**Comment by jsjoeio** [comment] 2022-03-24 16:56
Duplicate of https://github.com/coder/code-server/issues/4894

**Closed** 2022-03-25 08:00 UTC
Labels: duplicate
