### ISSUE TITLE
[Bug]: Error while trying to start code-server arm64

### ISSUE THREAD

**Issue by atRobertoFlores** [coder/code-server#4845] opened 2022-02-09 23:55 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Ubuntu
- Remote Architecture: arm64
- `code-server --version`: 4.0.2

### Steps to Reproduce

There are 2 ways to reproduce the issue, remeber that Arch is arm64:

1. Docker container
   1.1. docker pull codercom/code-server:latest
   1.2. docker run -it --name code-server -p 8080:8080 codercom/code-server:latest

2. Manual installation to ubuntu docker image
  2.1. curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.0.2

### Expected

Container/code-server should log that server is listening and should be able to access to code-server login page

### Actual

error appears while trying to start the application, happens with the docker image codercom/code-server:latest or installing to ubuntu with `curl -fsSL https://code-server.dev/install.sh | sh -s -- --version=4.0.2` , tested with previous version 4.0.1 and the error is not happening, works as expected.

### Logs

```
ubuntu@fed6ac7767c9:/# code-server --bind-addr 0.0.0.0:8080
/usr/lib/code-server/node_modules/@node-rs/argon2/index.js:201
    throw loadError
    ^

Error: Cannot find module '@node-rs/argon2-linux-arm64-gnu'
Require stack:
- /usr/lib/code-server/node_modules/@node-rs/argon2/index.js
- /usr/lib/code-server/out/node/util.js
- /usr/lib/code-server/out/node/cli.js
- /usr/lib/code-server/out/node/entry.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/lib/code-server/node_modules/@node-rs/argon2/index.js:172:31)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/code-server/node_modules/@node-rs/argon2/index.js',
    '/usr/lib/code-server/out/node/util.js',
    '/usr/lib/code-server/out/node/cli.js',
    '/usr/lib/code-server/out/node/entry.js'
  ]
}
```

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment] 2022-02-10 00:01
Duplicate of https://github.com/coder/code-server/issues/4804

This has been fixed and will be out in the next release. Until then, please use 4.0.1!

**Closed by jsjoeio** 2022-02-10 00:01 UTC
Labels: bug, triage
