### ISSUE TITLE
Trying to download a complete folder from the Explorer: "can't open this folder because it contains system files  [Choose a different folder]"

### ISSUE THREAD

**Issue by drmrbrewer** [coder/code-server#4646] opened 2021-12-17 12:25 UTC
This relates to code-server 3.12.0.  

When I want to download a file to my local filesystem I right-click on the file in the Explorer and choose "Download..." -- works fine... downloads right away to the Downloads folder on my local drive (without any prompt for where to save... which is fine).

But when I right-click on a *folder* to download the entire folder, I get the following message:

![image](https://user-images.githubusercontent.com/9009792/146543848-d94ece3b-6770-4664-92de-9788ebab3105.png)

... where the redacted part is just the domain on which code-server instance is hosted e.g. `codeserver.mydomain.com`.

And no, the folder does *not* contain system files... not sure whether it's referring to the remote folder or local folder, but either way there are no system files.

I'm not even sure it's possible to download an entire folder in code-server / VSCode?  I sure *hope* it is possible, and it feels like it's *trying* to do the download (not just saying it's not possible to download folders).  Certainly on Cloud9 it is/was possible to download either a file or folder in this way, direct from the Explorer... for a folder it is just zipped and downloaded the folder as a zip (or maybe gz... either way is fine).

**Comment by jsjoeio** [comment] 2021-12-17 17:50
Hmm...this is very strange 🤔 @code-asher have you seen this before?

**Comment by code-asher** [comment] 2021-12-20 16:28
I have not seen it before.  The last time I tried it was not even
possible to download a folder so maybe it is new functionality that does
not quite work yet.  We will need to poke into the error.

**Comment by drmrbrewer** [comment] 2021-12-21 21:38
@code-asher the same thing happens when I try to download a *file* (in my example a log.html file) that is too big to open and show (completely) in the editor.  Downloading a smaller version of the same log.html file works just fine.

**Comment by code-asher** [comment] 2021-12-22 18:02
Ooo that is very interesting.

**Comment by drmrbrewer** [comment] 2022-06-22 15:32
I'm still seeing this (and being slightly frustrated by this) several times a day, so it would be great it this issue wasn't marked as stale!

**Comment by thomasapto** [comment] 2022-07-14 17:33
I'm seeing the same problem.  Following the instructions at [here](https://stackoverflow.com/questions/7106012/download-a-single-folder-or-directory-from-a-github-repo/70729494#70729494), on a Mac (Monterey 12.4).  Tried various likely places to download to, starting with `~/Downloads`, the default `~/Documents`, and `~/Desktop`.  (BTW, `Downloads` permission should be in place: it is in system prefs > Security & Privacy > Files and Folders, as Google Chrome.app (checkmark) Downloads Folder.  I'm loathe to give Chrome "Full Disk Access" which is unchecked.)

UPDATE: **what finally worked** was choosing `/tmp` (which is actually `/private/tmp`), with a couple of warnings along the lines of "github.dev will be able to read files until it's restarted".  

(At this point, my question is, what is this `github.dev` thing?  Maybe that's what I need to be giving permissions to?  It's not a real application though...)

Thanks

Screen shot below:  I right-clicked on `pyqldbsamples` > Download...

<img width="747" alt="Screen Shot 2022-07-14 at 10 27 46 AM" src="https://user-images.githubusercontent.com/104466558/179046409-195f3484-d12f-4c3f-8983-819b916f4f5c.png">

**Comment by jsjoeio** [comment] 2022-07-20 16:29
## Can't reproduce

I'm testing right now on my macOS + Brave + code-server 4.5.1.

I actually don't have the option to download folders 🤔

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/180034048-50dee05c-2f9c-4f8d-b382-d20077478bb7.png">

And come to think of it, I don't know if I have ever? 

## Same behavior in github.dev

I also don't see the Download option in github.dev...so I feel like this is a limitation upstream?

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/3806031/180034251-67cc6256-00da-45d9-9c35-ba91621b5721.png">

## Open issues

It seems like this is a limitation of Code Web so I don't think we can't do anything about this.

https://github.com/microsoft/vscode/issues/120908

**Comment by code-asher** [comment] 2022-07-21 00:08
Nice find on that issue!

I guess Chrome considers Downloads a system folder.

**Comment by jsjoeio** [comment] 2022-07-21 16:17
Since this has been identified as an upstream limitation, I'm going to close this since I don't think we can work around this.

**Closed by jsjoeio** 2022-07-21 16:17 UTC
Labels: bug

**Comment by drmrbrewer** [comment] 2022-07-21 18:21
@jsjoeio shame.  But thanks to @thomasapto (see [here](https://github.com/coder/code-server/issues/4646#issuecomment-1184720049)) I can now download folders from my code-server IDE, by choosing e.g. folder `C:\Users\Joe\Temp\` to download into, rather than into `Downloads`.

**Comment by jsjoeio** [comment] 2022-07-21 18:45
Oh wow, that is an awesome workaround! Thanks for pointing that out!

**Comment by youthHan** [comment] 2022-09-03 04:48
I encountered the same problem. My workaround is to make a new folder and grant its writing permission to all users, as I cannot find the tmp folder on the popout window on a MAC🤷‍♂️. This workaround allows you to change the place where you want to download them and protect your other personal files. Hope it helps.

**Comment by thomasapto** [comment] 2022-09-07 04:13
1. (I asked) "What is this github.dev thing"?  It's the web version of VSCode.  You get to it from a github.com repo by typing `.` (a dot -- aka hitting the period key).  "Explorer" is the file tree view of a repo.
2. @jsjoeio "I actually don't have the option to download folders 🤔"  It appears you are looking at a repo on your local machine?  (URL says `localhost:8080`) Maybe the thing is saying, hey, this is already on your computer, why would you want to re-download it?
3. @youthHan "I cannot find the tmp folder on the popout window on a MAC🤷‍♂️" The secret shortcut is Cmd-Shift-G and it lets you choose any folder; you can just type in the path.  Such as, in this case, `/tmp`.  (Note that the download dialog operates similarly to Finder, and this is a Finder shortcut too.)
4. I found another workaround (besides using `/tmp`): It's just `Downloads` per se that it doesn't like, so, make a subdirectory to `~/Downloads` and it will accept that.  For example: Back at the original site I was trying to do this on, [https://github.dev/aws-samples/amazon-qldb-dmv-sample-python](https://github.dev/aws-samples/amazon-qldb-dmv-sample-python), right click on `pyqldbsamples` and choose Download.  In the popup window (the download dialog), navigate to the `~/Downloads` folder (shortcut: Cmd-Opt-L) and click `New Folder` and type `foo` as the new folder name; it will create the folder and put you there; and then click `Select` to choose that location.  It will ask for permission and warn you that the website will continue to have that permission until you leave it, and then proceed to download the files to there.  

(It is acting like the JavaScript program that is `github.dev` gets read/write permissions to whatever folder you select.  Maybe one can start a new project in a local directory and do development there using the online VSCode as an IDE, so, this makes some kind of sense.  Chrome and MacOS must have provisions for doing so and have security around it, which is why they don't want you to use `Downloads`, as this is a "special" folder -- too dangerous if some website could drop malicious files there.)

**Comment by 1234567Yang** [comment] 2022-12-10 06:43
just choose Picture floder:
This PC: Pictures

**Comment by filipjnc** [comment] 2023-05-03 11:47
> just choose Picture floder: This PC: Pictures

Can confirm the Pictures folder works also on my Windows 11 work laptop. Simply choosing Downloads, Documents does not work.

**Comment by DabenW** [comment] 2023-06-20 08:55
As mentioned in this issue : [see here](https://github.com/microsoft/vscode/issues/144753#issuecomment-1063606119). "It's one of the stupid restrictions of File System Access API".
Just create a subdirectory in entire home directory, entire desktop or entire documents folder, and you can download your file or folder in there.
<img width="803" alt="image" src="https://github.com/coder/code-server/assets/19250250/e53e01fd-921b-45ba-8f9f-4efa5ea56a1d">

**Comment by drmrbrewer** [comment] 2023-06-20 09:01
So it seems like there's no workaround, but @jsjoeio at the very least could code-server display a more informative message (e.g. telling the user what the issue is and how *they* can work around it), even if this is an upstream issue?  Or is even the message an upstream issue?

**Comment by jsjoeio** [comment] 2023-06-20 15:43
I don't work on the project anymore but maybe @code-asher can chime in

**Comment by code-asher** [comment] 2023-06-20 17:45
A notification would require a patch to VS Code so it would be 
preferable to change it upstream if they are receptive to such a 
change, which I think they would be considering it probably 
affects their own Codespaces.

**Comment by suporte-avancado** [comment] 2023-12-13 20:20
> just choose Picture floder: This PC: Pictures

this works for mac
