### ISSUE TITLE
[Bug]: Docker Compose HASHED_PASSWORD

### ISSUE THREAD

**Issue by groot314** [coder/code-server#5327] opened 2022-07-10 00:16 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: iPad Chrome 
- Local OS: Ubuntu
- Remote OS: iPad
- Remote Architecture: amd64
- `code-server --version`: latest

### Steps to Reproduce

1. Setup with docker-compose
2. Create Argon Hash with desired password
3. Past the hash into the docker compose file environment variable “HASHED_PASSWORD”
4. Check if you can login using password

### Expected

You should be able to login with the password that was hashed

### Actual

Returns “incorrect password”

### Screenshot/Video

![B748BC46-C35E-4E72-9544-B23EE6F99B0B](https://user-images.githubusercontent.com/1497989/178126617-6b9f96b4-3f62-45ac-9bb7-09790d32b9fa.jpeg)

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by jsjoeio** [comment] 2022-07-18 22:07
Inside the container, if you `echo HASHED_PASSWORD`, what do you see? I'm wondering if it needs to be in quotes.

**Comment by Cyborgmatt** [comment] 2022-08-08 13:08
The issue is caused by the `$` signs inside the string.

In order to make this work in your Docker Compose file, you need to change all the single `$` to `$$`.

**Comment by jsjoeio** [comment] 2022-08-08 22:08
Ah got it. Cool, I'm going to close this for now.

**Closed by jsjoeio** 2022-08-08 22:08 UTC
Labels: bug, triage
