### ISSUE TITLE
File not fount

### ISSUE THREAD

**Issue by an-ce** [coder/code-server#6909] opened 2024-07-20 08:31 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:

### Steps to Reproduce

7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:21 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:23 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda_bg.wasm
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda.js

### Expected

7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:21 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:23 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda_bg.wasm
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda.js

### Actual

7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:21 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:23 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda_bg.wasm
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda.js

### Logs

```shell
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:21 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:23 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda_bg.wasm
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda.js
```

### Screenshot/Video

7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:21 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:23 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda_bg.wasm
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda.js

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

### Notes

7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:18:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:00 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:46 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:19:50 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:20 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:20:42 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:14 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:21 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:23 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/tunnel/common/tunnel.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/window/common/window.js
7月 20 16:21:33 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vs/platform/product/common/product.js
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda_bg.wasm
7月 20 16:22:43 yan code-server[2169848]: File not found: /usr/local/code-server/lib/vscode/out/vsda.js

**Comment by code-asher** [comment] 2024-07-22 19:59
It looks like a duplicate of https://github.com/coder/code-server/issues/5696

The problem seems to happen when the main workbench file takes too long to load (usually due to a slow network).  Unfortunately this loader behavior is out of our control.  If someone can reproduce in Codespaces that would be helpful because then we can report it upstream.

**Closed by code-asher** 2024-07-22 19:59 UTC
Labels: bug, triage
