### ISSUE TITLE
Revert Change not working in v4.0.1

### ISSUE THREAD

**Issue by drmrbrewer** [coder/code-server#4757] opened 2022-01-16 09:05 UTC
When I am editing a file that is subject to version control, I get blue marks in the left margin to show where changes have been made:

![image](https://user-images.githubusercontent.com/9009792/149653529-ff2f101b-f8e7-486c-b835-b2a3d5143720.png)

When you click on the blue mark, you are shown exactly what changes have been made, and you also have a "revert change" button as indicated below:

![image](https://user-images.githubusercontent.com/9009792/149653580-adb5863d-62e5-49ec-816b-5dab3a70aee7.png)

In code-server v3.12.1, when I clicked on the "revert change" button, it actually reverted the change.

In code-server v4.0.1, nothing happens, apart from the following in the console:

	  ERR Error: vscode-remote://vscode.myserver.com/root/workspace/test/test.js has changed in the meantime
		at n.apply (bulkTextEdits.ts:246:11)
		at async o._performTextEdits (bulkEditService.ts:118:3)
		at async o.perform (bulkEditService.ts:99:5)
		at async r.apply (bulkEditService.ts:214:4)
	  WARN IGNORING workspace edit Error: vscode-remote://vscode.myserver.com/root/workspace/test/test.js has changed in the meantime
		at n.apply (bulkTextEdits.ts:246:11)
		at async o._performTextEdits (bulkEditService.ts:118:3)
		at async o.perform (bulkEditService.ts:99:5)
		at async r.apply (bulkEditService.ts:214:4)
	  ERR document 'file:///root/workspace/test/test.js already exists!': Error: document 'file:///root/workspace/test/test.js already exists!'
		at p.acceptDocumentsAndEditorsDelta (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:73871)
		at p.$acceptDocumentsAndEditorsDelta (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:73413)
		at t._doInvokeHandler (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:13802)
		at t._invokeHandler (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:13486)
		at t._receiveRequest (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:12148)
		at t._receiveOneMessage (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:10826)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:8922
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at P.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:15967)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:30660
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at P.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:15967)
		at g._receiveMessage (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:21237)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:18115
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at b.acceptChunk (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:13328)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:12676
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:19664
		at afterWrite (internal/streams/writable.js:466:5)
		at onwrite (internal/streams/writable.js:446:7)
		at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
		at Zlib.processCallback (zlib.js:607:8)
	  ERR Unable to retrieve document from URI 'file:///root/workspace/test/test.js': Error: Unable to retrieve document from URI 'file:///root/workspace/test/test.js'
		at I.getDocument (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:70576)
		at U.provideDocumentRangeSemanticTokens (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:100681)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:121170
		at xe._withAdapter (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:111762)
		at xe.$provideDocumentRangeSemanticTokens (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:95:121148)
		at t._doInvokeHandler (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:13802)
		at t._invokeHandler (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:13486)
		at t._receiveRequest (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:12097)
		at t._receiveOneMessage (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:10826)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:99:8922
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at P.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:15967)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:30660
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at P.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:15967)
		at g._receiveMessage (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:21237)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:18115
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at b.acceptChunk (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:13328)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:74:12676
		at a.fire (/usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:66:1712)
		at /usr/lib/code-server/vendor/modules/code-oss-dev/out/vs/server/remoteExtensionHostProcess.js:114:19664
		at afterWrite (internal/streams/writable.js:466:5)
		at onwrite (internal/streams/writable.js:446:7)
		at InflateRaw.afterTransform (internal/streams/transform.js:103:3)
		at Zlib.processCallback (zlib.js:607:8)

Sometimes, after pressing "revert change" I also get the following pop up:

![image](https://user-images.githubusercontent.com/9009792/149653619-c3371349-e9d1-442b-b43f-d540c7f6adb3.png)

**Comment by w0otness** [comment] 2022-01-17 22:25
I can't replicate the behaviour on my 4.0.1 setup.
I am running from a Cloud9 AWS EC2 based instance, with no modifications to file/folder permissions or users.

Can you explain some more about your environment, it is a possibility that is the root cause.

**Comment by jsjoeio** [comment] 2022-01-18 18:27
Thank you both for the details! @drmrbrewer should we close this?

**Comment by drmrbrewer** [comment] 2022-01-18 18:51
@jsjoeio I guess so 🤔 until it's reproducible.

**Closed** 2022-01-18 20:03 UTC
