### ISSUE TITLE
[Feat]: support windows-x86 and x64

### ISSUE THREAD

**Issue by miaomiao1992** [coder/code-server#6678] opened 2024-02-16 11:15 UTC
## What is your suggestion?
my computer is windows-x86, and this project run on win-x86 is a better thing.

## Are there any workarounds to get this functionality today?
yes

## Are you interested in submitting a PR for this?
yes

**Comment by code-asher** [comment] 2024-02-29 00:03
Definitely happy to merge a PR that adds Windows support!

I think we can consider this a duplicate of https://github.com/coder/code-server/issues/1397, so I will close this one in favor of that.

**Closed by code-asher** 2024-02-29 00:03 UTC
Labels: enhancement
