### ISSUE TITLE
titleBar color setting is ignored in version v4.0.1 (PWA mode)

### ISSUE THREAD

**Issue by akares** [coder/code-server#4725] opened 2022-01-11 13:33 UTC
After upgrade 3.12.0 -> 4.0.1 the `titleBar.activeBackground` theme setting doesn't work anymore.

It suppose to change the color of the window title in the PWA mode (see screenshots).

## OS/Web Information

- Web Browser: Chrome
- Local OS: macOS 12.1
- Remote OS: Ubuntu 20.04.3 LTS
- Remote Architecture: x86_64
- `code-server --version`: 4.0.1

## Steps to Reproduce

Working version:
1. Set up 3.12.0.
2. Install it in PWA mode (as separate app window).
3. Edit `settings.json` and customise `workbench.colorCustomizations`->`[yourThemeName]` -> `titleBar.activeBackground` value (CSS color).
An example:
https://gist.github.com/akares/846d368c9ebecfb7fdc51aaa4a91ec12
4. Notice window title background change.

Broken version:

5. Upgrade to 4.0.1
6. The theme tweak is ignored now.

## Screenshot

<img width="659" alt="Screenshot 2022-01-11 at 14 17 21" src="https://user-images.githubusercontent.com/222923/148950434-6025b198-db8b-4fbb-b6c8-13d4392681a1.png">

## Expected

<img width="614" alt="Screenshot 2022-01-11 at 14 24 01" src="https://user-images.githubusercontent.com/222923/148950453-6c739598-0924-48ad-9929-8dda61cddc67.png">

UPD: Seems hex color values preview feature also failed in 4.0.1.

**Comment by jsjoeio** [comment] 2022-01-12 23:56
I tested this and was able to reproduce the issue in code-server 4.0.1
![image](https://user-images.githubusercontent.com/3806031/149241471-f15efdfa-cf5b-4d2c-bbf3-2245824074e3.png)

I also tested on vscode.dev (installing the PWA) and could not reproduce (works as expected).
![image](https://user-images.githubusercontent.com/3806031/149241408-9c4f1e59-68bd-428e-bb01-5f8621451347.png)

cc @code-asher was this ever broken in the past? Maybe we lost a change in the upgrade.

**Comment by code-asher** [comment] 2022-01-13 18:34
Hmm I am not sure.  We have our own PWA setup so maybe there is existing
code that vscode.dev is using that we should switch to.

**Comment by LordMethenor** [comment] 2022-01-25 20:32
Same here on my chromebook. Fresh install on 3.12 (theme-color sets correctly), vs 4.0.1 (theme-color is unchanged)
![theme-color312](https://user-images.githubusercontent.com/37001137/151054690-00e14150-70a5-4114-97d6-920678d16e3c.png)
![theme-color401](https://user-images.githubusercontent.com/37001137/151054687-4fa4fa7c-3317-4df7-8d6a-88105ffe2989.png)

I don't know a ton about web development, but I'm pretty sure theme-color is set dynamically. Even if it's set in the manifest, it can still change in the page's html. The page will load in with the manifest's setting.

**Comment by jsjoeio** [comment] 2022-01-25 22:38
Thanks @LordMethenor! Yeah we probably need to fix something in the PWA manifest

**Comment by shp7724** [comment] 2022-03-08 13:08
# Workaround

Looking at the developer console, I found there exist two `theme-color` meta tags, which looked like the culprit of this issue.

![image](https://user-images.githubusercontent.com/33917774/157243361-3f02bf93-913e-46b7-a778-08460accd99f.png)

As a workaround, I simply deleted the following line in `workbench.html` and everything worked as expected.

```diff
<link rel="alternate icon" href="{{BASE}}/static/resources/server/favicon.svg" type="image/svg+xml" />
<link rel="icon" href="{{BASE}}/favicon.ico" type="image/x-icon" />
<link rel="manifest" href="{{BASE}}/manifest.json" crossorigin="use-credentials">
- <meta name="theme-color" content="{{CLIENT_BACKGROUND_COLOR}}">
<link data-name="vs/workbench/workbench.web.api" rel="stylesheet" href="{{BASE}}/static/out/vs/workbench/workbench.web.api.css">
```
(I installed code-server via homebrew, so in my case, `workbench.html` was located in `/usr/local/Cellar/code-server/4.1.0/libexec/vendor/modules/code-oss-dev/out/vs/code/browser/workbench/workbench.html`.)

I hope this helps.

**Comment by jsjoeio** [comment] 2022-03-08 17:25
@shp7724 wow!!! Nice find. We actually delete this as part of the 1.64 update (https://github.com/coder/code-server/pull/4902) so this should be fixed in the next release. Thank you for posting that!

**Closed** 2022-03-09 21:28 UTC
Labels: bug
