### ISSUE TITLE
[Bug]: tmux and copy to clipboard

### ISSUE THREAD

**Issue by ryanlinnane** [coder/code-server#5112] opened 2022-04-18 15:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS
- Remote OS: CentOS

### Steps to Reproduce

1. Open remote vscode
2. Open terminal and open tmux
3. Try to copy with mouse by dragging, or by holding option/shift. Neither copies.

### Expected

Expecting to be able to copy in some way, whether through holding shift or through ones config with X forwarding.

### Actual

Nothing, option/shift also prevent highlighting.

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by ryanlinnane** [comment] 2022-04-19 14:36
A temp fix for the above:
```
"terminal.integrated.macOptionClickForcesSelection": true,
"terminal.integrated.copyOnSelection": true
```
The above allows me to copy in tmux remotely while holding the option key. It would be ideal if option wasn't needed.

**Comment by jsjoeio** [comment] 2022-04-19 18:48
I don't know if this is something we can fix. We'd have to modify the default Terminal settings which seems like something we don't want to do. Unless I'm misunderstanding something?

**Comment by code-asher** [comment] 2024-02-29 00:14
I am going to go ahead and close this since from what I understand this is how VS Code natively behaves in the web.  But correct me if I am wrong.  We can try it with Codespaces and see if the problem reproduces, if so we should report it upstream.

**Closed by code-asher** 2024-02-29 00:14 UTC
Labels: waiting-for-info
