### ISSUE TITLE
asExternalUri doesn't work

### ISSUE THREAD

**Issue by orshefi** [coder/code-server#1936] opened 2020-08-02 08:52 UTC
Hi Guys,

I had written a new extension which renders Graphs from matplotlib into vscode webview component, it works great on vscode desktop, but I encounter problems when trying to work with it in code-server.

I cannot state what exactly the problem is but here is the workflow:
1. my vscode extension starts and listens to requests for plot viewing on port 11111 (POST request)
2. matplotlib custom backend sends a request to the extension with the url to open in webview
3. I use vscode.env.asExternalUri tunneling in order to open the url in a webview and embed the generated address in an Iframe.
4. Usually by now the webview with the webpage would have been loaded, but instead I get and error openning localhost refuse to connect

<img width="655" alt="Screen Shot 2020-08-02 at 11 50 37" src="https://user-images.githubusercontent.com/17097072/89119347-8b094b80-d4b6-11ea-8822-a17f630954a2.png">

Any ideas what went wrong?

- Web Browser: Chrome
- Local OS: Ubuntu
- Remote OS: MacOS
- Remote Architecture: x86_64
- `code-server --version`: v3.4.1

**Comment by code-asher** [comment] 2020-08-03 15:28
I'm not too familiar with `asExternalUri` but this is might mean there's something missing in our implementation. We'll need to dig further.

**Comment by orshefi** [comment] 2020-08-04 08:36
Thanks for the response, I actually solved it from another direction.

Instead of using iframe to the rendered graph url on the host, I took its html and embedded it into the webview.
I also created a translator from the WebSocket that matplotlib webagg backend creates to vscode Iframe messaging infrastructure.

It works ok, you can close this issue.

I believe soon I'll release this extension to be open source and then I'll need your help to get it into your extensions server

**Comment by code-asher** [comment] 2020-08-04 16:24
Awesome, that sounds like a really good workaround. 

I'm thinking we should leave the issue open until we fix `asExternalUri` since it would be ideal to have parity with local VS Code.

**Comment by jsjoeio** [comment] 2022-06-30 16:18
The Tabnine team is still facing this so we need to dig into it.

**Comment by misskniss** [comment] 2022-07-26 17:48
If the work around is not working @code-asher @jsjoeio @Emyrk  what are options for addressing this?

**Comment by jsjoeio** [comment] 2022-08-01 19:39
I'm guessing @code-asher and I will need to add a patch to fix this then.

**Comment by code-asher** [comment] 2022-08-02 18:41
To fully fix for the Tabnine case we will need:

1. Implement `asExternalUri`
2. Use the sub-domain proxy instead of path-based proxy when available
3. Allow external proxies (like Coder's dev URLs) so it can be set up to work in environments that have their own sub-domain proxy setup and cannot delegate that role to code-server

**Comment by ksylvan** [comment] 2022-09-11 21:01
Any updates on this issue? I’m still running into problems using TabNine on VS Code Web.

**Comment by jsjoeio** [comment] 2022-09-12 18:37
Chatting with their team about this. Stay tuned!

**Comment by Sominemo** [comment] 2022-09-13 06:38
Dart & Flutter extension for VS Code [uses asExternalUri too](https://github.com/Dart-Code/Dart-Code/blob/7c749f194f20ea7adfb7480aef3d4c45b6ea3bf7/src/shared/vscode/utils.ts#L241), and its DevTools iframes don't work without manual port forwarding, because it tries to connect to localhost. As far as I understand, it's related to this issue.

**Comment by jsjoeio** [comment] 2022-09-14 17:16
Thanks for letting us know @Sominemo! That'll be helpful when we go to fix this. We may want to write our own extension that uses asExternalUri and add an e2e test to make sure it works (when we fix this).

**Comment by jsjoeio** [comment] 2022-10-04 17:56
# Notes

I have started looking into this and will share my notes here and update this comment as I go.

## Investigation: does `asExternalUri` work?

Here are the steps I'm following to check:
1. create a new extension: `npx yo code`
2. open code-server (4.7.0) locally (macOS + Brave) and open extension
3. use `vscode.env.asExternalUri` in extension (see code below)
4. run extension (F5) or click "Run extension" in Run and Debug window
5. run command and test 

**Expected**
It logs to the Debug Console a url that I can open in my browser.

**Actual**
WIP

**Video**
WIP

**Comment by jsjoeio** [comment] 2022-10-04 22:32
I've identified the Root Cause as well and have an idea for fixing this.

## Root Cause

Based on my findings, the call stack looks like this:
1. extension calls `asExternalUri` using `vscode.env.asExternalUri`
2. that calls `asExternalUri` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostWindow.ts#L61-L68)
3. that calls `$asExternalUri` [here](https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/browser/mainThreadWindow.ts#L62-L65)
4. calls `openerService.resolveExternalUri` [here](https://github.com/microsoft/vscode/blob/d19445483ef67e2f1019382ef026913a0e30b69d/src/vs/editor/browser/services/openerService.ts#L182-L198)

This last function -- `resolveExternalUri` -- tries to resolve this external uri using one the  `_resolvers` (property on class). The problem is...there are no resolvers in the browser (at least in code-server, where i'm running with `yarn watch`).

"Okay...so shouldn't it throw [this error](https://github.com/microsoft/vscode/blob/d19445483ef67e2f1019382ef026913a0e30b69d/src/vs/editor/browser/services/openerService.ts#L197)?"

You would think so but if you look at the link in #3 in my call stack list, you'll notice the code isn't wrapped in a `try/catch` block. Therefore, that error never bubbles up.

"is that a bug?"

I would say so but I might check with @code-asher. Could be worth raising upstream.

There may be more to this root cause since I'm not sure why there wouldn't be a resolver for this external URI in the first place. I know it works in Codespaces but I can't figure out how.

## Solution

I'd like to discuss with @code-asher first but I did find this. When I add `resolveExternalUri` [here](https://github.com/microsoft/vscode/blob/main/src/vs/code/browser/workbench/workbench.ts#L506-L514) called like so:
```typescript
		resolveExternalUri: async (uri: URI) => {
			const v = await Promise.resolve(URI.parse("http://localhost:8080/proxy/8000"))
			return v
		},
```
then my extension uses it!

<img width="473" alt="image" src="https://user-images.githubusercontent.com/3806031/193941573-f1552bdf-23e1-45df-ac3b-c9b2001270fa.png">

If this is the correct place to patch, then next steps would be to agree upon how external uris should be resolved. One approach could be to use code-server's built-in proxy and do something like `localhost:8000` -> `<base-url>/proxy/8000`.

**Comment by jsjoeio** [comment] 2022-10-06 15:14
I chatted with @code-asher offline and we came up with a fix. I'm going to work on it today and hopefully push up a draft PR soon. Keep an eye out.

**Comment by jsjoeio** [comment] 2022-10-07 22:20
Good news - [PR](https://github.com/coder/code-server/pull/5624) is pretty much good to go. We should be able to wrap it up Monday assuming all goes well.

**Comment by ksylvan** [comment] 2022-10-09 22:31
Awesome. Thank you!

**Comment by ksylvan** [comment] 2022-10-11 22:30
> Good news - [PR](https://github.com/coder/code-server/pull/5624) is pretty much good to go. We should be able to wrap it up Monday assuming all goes well.

Would you like me to try testing this?

**Comment by jsjoeio** [comment] 2022-10-13 16:44
@ksylvan yes please!

P.S. I should have time to clean up my PR today and merge 🤞🏼

**Comment by ksylvan** [comment] 2022-10-13 17:32
What's the easiest way for me to test this?

**Comment by jsjoeio** [comment] 2022-10-13 18:09
Good question! Easiest way that comes to mind:

1. `yarn init -y`
2. `yarn add @coder/code-server-pr@4.7.1-5624-6ae9dec77528bc9af1b1de503d56ea5318bab99b`
3. `yarn code-server --auth none --port 3000`

That'll load code-server with the changes. Then you could try using any basic extension that uses `asExternalUri` and it should work. I think Tabnine will need changes upstream after our PR is merged.

**Comment by ksylvan** [comment] 2022-10-13 18:23
> That'll load code-server with the changes. Then you could try using any basic extension that uses asExternalUri and it should work. I think Tabnine will need changes upstream after our PR is merged.

```
$ yarn code-server --auth none --port 3333
yarn run v1.22.19
error Command "code-server" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ksylvan** [comment] 2022-10-13 18:41
Looks like my Debian instance wasn't updated to NodeJS16. Fixed that and now it's running.

**Comment by jsjoeio** [comment] 2022-10-13 19:57
Hmmm...I'm not sure why it's not installing on the modules. Here is one solution: https://github.com/coder/code-server/issues/5530#issuecomment-1259443775

You could also try with `npm` instead. Sorry for the trouble!

**Closed** 2022-10-14 16:09 UTC
Labels: bug, high-priority

**Comment by ksylvan** [comment] 2022-10-26 01:31
I see the new code with the proxy server auto-forwarding is in code-server, do you know what needs to happen with tabnine extension to use it?

**Comment by jsjoeio** [comment] 2022-10-26 15:26
Hmm...I'd probably have to dig in but ideally they use `asExternalUri` to resolve the uri for their server. Something like:
```typescript
// pseudo code
const serverURL = await vscode.asExternalUri("http://localhost:3000")
```
