### ISSUE TITLE
Unable to install Chinese language plugin(vscode-language-pack-zh-hans) with command

### ISSUE THREAD

**Issue by shaoqingyang** [coder/code-server#7004] opened 2024-09-19 04:08 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS:
- Remote OS:
- Remote Architecture:
- `code-server --version`:
I use command like this ’./code-server --install-extension /xxxx‘ to install plugin, ctrl+shift+p can't find CN language.However I  use UI like this can install this plugin.
![image](https://github.com/user-attachments/assets/52b0a032-78ad-44d5-8746-b85cd8244104)

### Steps to Reproduce

1.
2.
3.

### Expected

Use command can find this to select.
![image](https://github.com/user-attachments/assets/df4325e2-47b2-4b2e-ad1e-dfecc20718e5)

### Actual

Use command ‘./code-server --install-extension /xxxx’ can install plugin,but can't select CN language.

### Does this bug reproduce in native VS Code?

Yes, this is also broken in native VS Code

### Does this bug reproduce in GitHub Codespaces?

Yes, this is also broken in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [ ] I am using a secure context.

**Comment by code-asher** [comment] 2024-09-19 19:06
Yeah I think VS Code might have a bug where it is not generated the language bundle when installing from the command line.

I will close it as a duplicate of https://github.com/coder/code-server/issues/4735 and rename that issue a bit, but I think this will probably have to be fixed upstream in VS Code.

**Closed by code-asher** 2024-09-19 19:06 UTC
Labels: bug, triage
