### ISSUE TITLE
Integrated Terminal does not open at startup and is not persistent on refresh

### ISSUE THREAD

**Issue by schettn** [coder/code-server#6919] opened 2024-07-24 07:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS
- Remote OS:
- Remote Architecture:
- `code-server --version`:
1.84.2
0c98611e6b43803a9d5dba222d7023b569abfb49
x64

### Steps to Reproduce

1. Open code-server in browser
2. See that there is no integrated terminal open at startup
3. Open a new terminal
4. Reload window
5. See that the terminal does not re-open.

### Expected

1. A integrated terminal should be opened on first load
2. The terminal should persist on reloads.

Both points do work in to GitHub CodeSpaces.

### Actual

Neither.

### Screenshot/Video

https://github.com/user-attachments/assets/45b0c27c-e310-4de8-a7f7-cf3b8bb3b7a2

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

No, this works as expected in GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

### Notes

With "persisted" I do not mean the terminal sessions but the persistence of of the opening state.

**Comment by code-asher** [comment] 2024-07-24 21:52
1.84.2 is rather old, does this persist on 4.91.1?

**Comment by schettn** [comment] 2024-07-25 06:09
I installed coder just recently by following https://coder.com/docs/install.

I thought that I am on the latest version. How can I check the version of `code-server`?

```bash
coder version
Coder v2.13.0+56bf386 Tue Jul  2 17:54:06 UTC 2024
https://github.com/coder/coder/commit/56bf386b15128c986ad4172c1932c13bed626d58

Full build of Coder, supports the  server  subcommand.
```

**Comment by schettn** [comment] 2024-07-25 06:10
> code-server --version:
> 1.84.2
> https://github.com/coder/code-server/commit/0c98611e6b43803a9d5dba222d7023b569abfb49
> x64

What is the use for this commit hash? According to the commit I am on [v4.91.1](https://github.com/coder/code-server/releases/tag/v4.91.1), don't I?

**Comment by code-asher** [comment] 2024-07-25 16:49
Your is on [v4.19.1-rc.2](https://github.com/coder/code-server/releases/tag/v4.19.1-rc.2) (19, not 91).

Coder and code-server are two separate products, looks like you have the latest version of Coder but not the latest version of code-server.

**Comment by schettn** [comment] 2024-07-26 09:02
I could not figure out how to update this because I am on the latest coder version and I thought that coder updates code-server.

Now I figured out that the code-server version is specified in the terraform file of the template. It seems like your docker started template uses an old version of coder.

![image](https://github.com/user-attachments/assets/70e9673a-a7ff-44ea-bb72-f0826e9dd96b)

**Comment by code-asher** [comment] 2024-07-26 17:54
Oh!  Yeah you are right.  I will update the template, thank you for pointing that out.

**Comment by code-asher** [comment] 2024-07-26 18:00
https://github.com/coder/coder/pull/14030

**Comment by schettn** [comment] 2024-08-05 09:16
@code-asher Do you know a way to open up the terminal the first time after the workspace is created?

**Comment by code-asher** [comment] 2024-08-06 17:34
I am not sure if you can do it only the first time, but it might work to use tasks.json, for example:

```
{
  "version": "2.0.0",
  "tasks": [{
    "label": "open terminal on folder open",
    "command": "${command:workbench.action.terminal.toggleTerminal}",
    "runOptions": {
      "runOn": "folderOpen"
    }
  }]
}
```

**Comment by code-asher** [comment] 2024-09-19 19:17
Closing for now but let me know if you come back to this and it reproduces in the latest version.

**Closed by code-asher** 2024-09-19 19:17 UTC
Labels: bug
