### ISSUE TITLE
PATH environment variable overwritten in version 4.0.1 using Docker image

### ISSUE THREAD

**Issue by avouacr** [coder/code-server#4699] opened 2022-01-07 11:49 UTC
## OS/Web Information

- Web Browser: Firefox 95.0.1
- Local OS: Ubuntu 20.04
- Remote OS:
- Remote Architecture:
- `code-server --version`: 4.0.1

## Steps to Reproduce

The problem can be reproduced by building the following minimal Docker image : 

```
FROM codercom/code-server:4.0.1
ENV PATH="/home/coder/local/bin/conda/bin:${PATH}"
RUN echo $PATH
```
and running it as a local server in the browser as explained in the [installation guide](https://github.com/coder/code-server/blob/main/docs/install.md#docker).

## Expected

When opening a terminal in VSCode, the value of `$PATH` should be the same as the one echoed at the end of the `docker build` step. The behavior is correct when building the image from `code-server:3.12.0`.

## Actual

When building from `code-server:4.0.1`, the `$PATH` variable gets overwritten with the following path `/usr/lib/code-server/vendor/modules/code-oss-dev/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games`. If I run an interactive shell in the docker image using `docker exec`, the `$PATH` is as expected. But when opening VSCode in the browser, it is incorrect. I don't see any command in the `entrypoint.sh` script which modifies this variable.

Thank's for this great software.

**Comment by jsjoeio** [comment] 2022-01-07 20:51
@code-asher any ideas what might have been introduced that would modify the `$PATH`? 🤔

**Comment by code-asher** [comment] 2022-01-10 17:12
I took a short look but nothing stood out in particular.  We will need
to dig in a bit more.

**Comment by rafipiccolo** [comment] 2022-02-22 23:24
i need PATH to work to make git hooks work from vscode menu.

i tried to set the PATH system wide
```
RUN echo PATH=xxx >> /etc/environment
```
checked it works with
```
docker exec -ti vscode env
```
its ok. it prints the desired version of the path

but i see no changes in vscode terminal.
even if i had added this to settings.json
```
    "terminal.integrated.inheritEnv": true,
```

and my git hooks still doent work :(

anybody has a workarround ?

**Comment by avouacr** [comment] 2022-02-24 10:14
@rafipiccolo 

our workaround for the time being :
```
ENV PATH=xxxx
RUN echo "export PATH=$PATH" >> /home/coder/.bashrc 
```

**Comment by code-asher** [comment] 2022-10-05 20:27
We started discussing the cause in a duplicate issue https://github.com/coder/code-server/issues/5621 so I am going to close this one as there is now more information in #5621.

**Closed by code-asher** 2022-10-05 20:27 UTC
Labels: needs-investigation
