### ISSUE TITLE
Unable to build release 4.13

### ISSUE THREAD

**Issue by drupol** [coder/code-server#6244] opened 2023-05-31 19:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser:
- Local OS: Linux
- Remote OS:
- Remote Architecture:
- `code-server --version`: 4.13

### Steps to Reproduce

I'm trying to update code-server in nix through this PR: https://github.com/NixOS/nixpkgs/pull/234289
Basically we are upgrading from 4.12 to 4.13, and it seems that it's not buildable.

### Expected

compilation works

### Actual

![image](https://github.com/coder/code-server/assets/252042/4d1beada-67d2-44e8-9fe8-4977d59a0cd5)

### Logs

https://gist.github.com/drupol/a2c05a189481ff57de6b3624874b960b

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by code-asher** [comment] 2023-06-13 17:42
Those definitions seem to come from the `typescript` npm module found in `lib/vscode`.  There is a different version installed in the root, I wonder if the types are somehow resolving up past `lib/vscode` and using the wrong version although I am not sure why that would happen.  Maybe we make it work by updating the version in the root to match what Code is using.

**Comment by drupol** [comment] 2023-06-13 18:22
Hi!

I have the same issue using commit f6db985712a6738d2d38d81855e089ac97142155 (latest of `master` branch)

![image](https://github.com/coder/code-server/assets/252042/d0e00cdc-8265-4812-bf80-4abc8cae783c)

**Comment by code-asher** [comment] 2023-06-13 18:53
Ah unfortunate.  That PR updates to v5 but I suppose one more thing we could try is updating to the exact version VS Code is using (`5.1.0-dev.20230424`).

I am not confident that will do anything but let me test a bit and see what happens.

By the way, looks like the derivation builds the cloud agent but we took down the cloud service and removed the accompanying flag to enable it a while back so all that could be removed.

**Comment by drupol** [comment] 2023-06-13 19:08
> By the way, looks like the derivation builds the cloud agent but we took down the cloud service and removed the accompanying flag to enable it a while back so all that could be removed.

Excellent, I just removed it.

Let me know how it goes!

**Comment by code-asher** [comment] 2023-06-13 22:50
I think the issue is that one of the postinstall scripts is not being ran, namely `./lib/vscode/extensions/postinstall.mjs`.  If I run that I get past the type errors, then there is `'commit' is missing from product.json` which perhaps implies that `git rev-parse HEAD` is not returning anything?  

https://github.com/coder/code-server/blob/ccb0d3a34f304825c260cd08be324c0325f56564/ci/build/build-vscode.sh#L51-L55

**Comment by code-asher** [comment] 2023-06-13 22:53
Oh I see `git rev-parse HEAD` is actually replaced with `$commit` so I suppose that variable is missing/blank.

**Comment by drupol** [comment] 2023-06-14 07:50
Glad you took the time to check it out, it's greatly appreciated.

I'm also glad you found out the root issue, I'm looking forward to the next version and packaging it in Nix.

If you'd like to help me into the maintenance of code-server in Nix, just let me know, I can add you as maintainer.

**Comment by code-asher** [comment] 2023-06-14 23:01
> If you'd like to help me into the maintenance of code-server in Nix, just let me know, I can add you as maintainer.

Sounds good to me!  I would be happy to help out.

**Comment by code-asher** [comment] 2023-06-15 21:53
We got this sorted out in https://github.com/NixOS/nixpkgs/pull/237986

**Closed by code-asher** 2023-06-15 21:53 UTC
Labels: bug, triage
