### ISSUE TITLE
[Bug]: When account is clicked it is stuck in a "loading" text.

### ISSUE THREAD

**Issue by Juice2007** [coder/code-server#5287] opened 2022-06-21 18:20 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 11
- Remote OS: Ubuntu Server 20.04
- Remote Architecture:  Arm64
- `code-server --version`: 4.4.0

### Steps to Reproduce

1. 
2.
3.

### Expected

When you click account it should either say "no account" or should have a different account signed into it. E.g. Microsft, GitHub.
![Screenshot 2022-06-21 191738](https://user-images.githubusercontent.com/89304431/174870380-56576da4-e5e9-4eb4-a1ed-bcc47d9a99dd.png) 
should look a bit like this. Not this.

### Actual

![Screenshot 2022-06-21 191844](https://user-images.githubusercontent.com/89304431/174870580-0f7fa77c-96c3-4127-953b-e7326e34f9ed.png)
It is stuck at loading screen.

### Does this issue happen in VS Code or GitHub Codespaces?

- [x] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by Juice2007** [comment] 2022-06-21 20:13
Hi, no I do not have GitHub Co-Pilot installed. I think it is just thee new update

**Comment by jsjoeio** [comment] 2022-06-22 19:51
Duplicate of https://github.com/coder/code-server/issues/3418

**Closed by jsjoeio** 2022-06-22 19:51 UTC
Labels: bug, triage
