### ISSUE TITLE
[Bug]: Source control UI is unresponsive starting from version 4.10+

### ISSUE THREAD

**Issue by maxorlovsky** [coder/code-server#6153] opened 2023-04-19 09:03 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows
- Remote OS: Debian
- Remote Architecture: amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. install code-server 4.11.0 using install shell script
2. run code-server
3. modify file
4. enter source control and try to add file as "git add" through the UI, it is unresponsive. It's not only git add, but also revert and the whole UI for pull/push except git commit

### Expected

git functionality as git add / git revert / git pull / git push should happen

### Actual

UI is clickable but unresponsive and there are no logs showing in git terminal

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

### Notes

This does not happen in 4.9.1 version of the code-server, it started with version 4.10

**Comment by code-asher** [comment] 2023-05-01 19:13
I expermented with the 4.11.0 and 4.12.0 Docker images but had no luck reproducing.  Does it only happen with a specific repository and if so is it something that can be shared?

**Comment by waschinski** [comment] 2023-05-09 09:26
Same error here, running code-server on a Synology NAS. I noticed every time I click on some Git action like revert or adding a change, "extensions are being activated" is displayed but nothing happens. I have found no errors in the logs.

Can also confirm reverting to 4.9.1 it's working again.

Maybe it has to do with the extension host?

**Comment by code-asher** [comment] 2023-05-09 17:52
Do git commands also hang if they are run through the command 
line?  Checking the git extension logs might also reveal 
something.

It could certainly be related to the extension host, the git 
backend itself is implemented as an extension.  Hard to say 
without logs or a reproduction though.

**Comment by code-asher** [comment] 2023-05-09 18:35
Oh interesting, looks like there is a log level setting for git specifically as well.

**Comment by code-asher** [comment] 2023-05-09 18:39
Wild guess, I wonder if it is trying to prompt for credentials but unable to show the popup for whatever reason.

**Comment by Anshuldubey0602** [comment] 2023-10-10 17:04
Same issue with  version 4.7.1

**Comment by bilogic** [comment] 2023-11-03 04:23
Is it only the `Source Control` affected? 

I was on `4.13.0` for a long time, all good, but recently upgraded to `4.17.1` and `4.18.0` and running into a similar issue where loading of `Source Control` and extensions do not complete.

The clocks stay there forever, `Source Control` loading is incomplete and will never complete + there is no `Activating extensions ...` at the status bar. The way I would describe it is `Extensions crashed without errors`

![vscode1](https://github.com/coder/code-server/assets/946010/8bc907c7-80c0-4c59-bbb7-fe34aa0290a8)
![vscode2](https://github.com/coder/code-server/assets/946010/44399214-cf9f-4cc6-8cea-7fdeabab08e7)
![vscode3](https://github.com/coder/code-server/assets/946010/36039b65-d2d0-4726-b318-a654ccc12c1a)

**Comment by code-asher** [comment] 2023-11-16 01:20
@bilogic I have seen a similar issue with https://github.com/coder/code-server/issues/3061 but I am not sure it is the same thing.

**Comment by bilogic** [comment] 2023-11-16 02:31
@code-asher thanks I think they are the same problem, and this thread has a more accurate description of the problem

**Comment by bilogic** [comment] 2023-11-20 05:10
More observations:

1. When facing this issue, `Source Control` becomes broken
2. However, saving a file etc remains functional

This leads me to think that perhaps something in the "Trust workspace" code is broken?

**Comment by bilogic** [comment] 2023-11-28 13:11
This appears to have been fixed by `4.19.1-rc.2`.

Ever since upgrading from `4.13.0`, I faced the issue about 50% of the time when I open another workspace.

I have been swapping workspaces > 20 times on  `4.19.1-rc.2` and not faced it once,

**Comment by code-asher** [comment] 2023-11-29 21:21
Thank you for confirming!  4.19.1 is now out.

**Closed by code-asher** 2023-11-29 21:21 UTC
Labels: bug, triage
