### ISSUE TITLE
Ability to load global-state from a file

### ISSUE THREAD

**Issue by davidfirst** [coder/code-server#7011] opened 2024-09-26 17:48 UTC
## What is your suggestion?
Changes like icons order in the activity-bar are saved into "global state". Locally, vscode saves them in a sqlite db at `~/Library/Application\ Support/Code/User/globalStorage/state.vscdb`. Code-server seems to save them in the browser `IndexedDb` into `vscode-web-state-db-global`. 
My suggestion it to have a file on the file-system as a starting-point to be able to load the state from there first. (it'd be great to have only this location and never use the browser, but not sure if this is feasible). 

## Why do you want this feature?
I'm providing my users with a pre-configured vscode instance in the docker container. I can customize the settings, but I can't customize the state. Meaning, I can't for example provide a code-server instance where the Search button is on top of the Explorer button in the activity-bar. 

## Are there any workarounds to get this functionality today?
I was trying many approaches, e.g. changing the state from an extension, but it seems to be impossible. vscode extension API doesn't provide access to the global-state. 

## Are you interested in submitting a PR for this?
I wish I could :)

**Comment by code-asher** [comment] 2024-09-26 19:44
Thanks for the input!  Yeah this would be really great.  I think this is a duplicate of https://github.com/coder/code-server/issues/4212 so I will close it, please follow the other issue for updates!  Although I think no one is working on it at the moment.

**Closed by code-asher** 2024-09-26 19:44 UTC
Labels: enhancement

**Comment by davidfirst** [comment] 2024-09-27 17:27
@code-asher , thanks for the reference, I understand now the issue better. 
So yeah, moving from browser storage to the filesystem is not easy, but this one is more about a one-time state load. Only the first time vscode is loaded. If you think about the "profiles" vscode feature, you can export a profile, which also includes the global-state. Then you can import it on another machine and keep the same state. so something similar to this import-profile, but have it done before vscode is fully loaded, so the state is respected.
From a quick test I have done, I exported a profile in one code-server instance, made sure the global-state is there. Then, imported to another instance. Sadly, the global-state wasn't imported. I guess this is due to the same issue, which is global-state is saved in the browser storage.

**Comment by code-asher** [comment] 2024-09-27 21:34
Ohh I actually did not know there was a profile import/export feature in VS Code.  Does it work in Codespaces?  Wondering if we can leverage that to report it upstream, because if they have an import feature and it is not including the state when it should, that sounds like a pretty clear bug.

**Comment by code-asher** [comment] 2024-09-27 21:43
But, if the ask is to implement a one-time load completely separate from the profiles feature, my instinct is that this is actually more work than #4212, so if the implementation described in that ticket is sufficient we should go with that.

**Comment by davidfirst** [comment] 2024-10-03 12:50
I tried again after upgrading code-server to the latest. The profiles feature works well. Same as codespaces. 
I can export the current profile from one browser, go to another browser, import the profile, apply it, and immediately it changed the icons order according to the original browser. It showed a message to reload to apply the changes, but seems like the state changes were applied immediately without the need to reload. 

So we know it's possible to load the global-state from a file. The missing part is how to instruct code-server to load from that file when it starts.

**Comment by micahyoung** [comment] 2024-11-18 00:36
Just stumbled on this and wanted to add (since it doesn't appear to have been mentioned) that both desktop and `vscode.dev` can currently support loading gist-exported Profiles via URL, Ex: 

Local links like:
`code-oss://profile/github/2360da218ced18e050aeda8c3107aa54`

`vscode.dev` links like:
http://vscode.dev/editor/profile/github/2360da218ced18e050aeda8c3107aa54

Empty, exported gist:
https://gist.github.com/micahyoung/2360da218ced18e050aeda8c3107aa54

Docs: https://code.visualstudio.com/docs/editor/profiles#_save-as-a-github-gist

I _**have not**_ been able to make this work work with code-server but feels like I might be close, so just want to document my efforts (and avoid retrying):

Direct, `vcode.dev`-like URLs don't work:
* `http://localhost:8080/editor/profile/github/2360da218ced18e050aeda8c3107aa54` (404)
* `http://localhost:8080/profile/github/2360da218ced18e050aeda8c3107aa54` (404)

URL `payload` params don't work:
* `http://localhost:8080/?payload=[["openFile","code-oss://profile/github/2360da218ced18e050aeda8c3107aa54"]]` (no effect)
* `http://localhost:8080/?payload=[["openFile","vscode-remote://profile/github/2360da218ced18e050aeda8c3107aa54"]]` (does open empty file)
* `http://localhost:8080/?payload=[["profile","code-oss://profile/github/2360da218ced18e050aeda8c3107aa54"]]` (UI fails, console suggests it wants relative path in user-settings-dir)
* `http://localhost:8080/?payload=[["profile","vscode-remote://profile/github/2360da218ced18e050aeda8c3107aa54"]]` (UI fails like above)
* http://localhost:8080/?payload=[["profile","https://gist.github.com/micahyoung/2360da218ced18e050aeda8c3107aa54"]] (UI fails like above)

URL params don't work 
* `http://localhost:8080/?profile=vscode-remote://profile/github/2360da218ced18e050aeda8c3107aa54` (no effect)

Looks like lots of this logic is defined here:
https://github.com/microsoft/vscode/blob/c3215a74273ad38bd54e59ffce113da5fa104e33/src/vs/workbench/services/userDataProfile/common/userDataProfile.ts#L73-L85

**Comment by mgerasimchuk** [comment] 2024-12-15 11:56
@micahyoung thank you, profiles really works and fortunately for all states like hidden panels and s.o., will try to implement the profile loading from file for the initial start of code-server

**Comment by liorshk** [comment] 2025-03-30 14:17
Any update or workaround known to solve this issue?
