### ISSUE TITLE
Keep Loading...

### ISSUE THREAD

**Issue by jefftuschool** [coder/code-server#6902] opened 2024-07-17 03:54 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS
- Remote OS: Linux
- Remote Architecture:
- `code-server --version`: 4.90.3 and 4.91.0

### Steps to Reproduce

1. Run 4.91.0
2. Create a HTML file
3. Hover to a link from HTML comments

### Expected

Should show a cmd + click

### Actual

show a Loading..., then CPU usage higher like 99%, and this did not happen in version 4.90.3

### Screenshot/Video

<img width="1253" alt="Screenshot 2024-07-16 at 8 40 36 PM" src="https://github.com/user-attachments/assets/f7bf4fb6-d45c-4d44-b7ff-24bbe119271e">

<img width="1253" alt="Screenshot 2024-07-16 at 8 42 24 PM" src="https://github.com/user-attachments/assets/7e413a23-5c02-4faf-898a-2408c31ad07c">

### Does this bug reproduce in native VS Code?

I did not test native VS Code

### Does this bug reproduce in GitHub Codespaces?

I did not test GitHub Codespaces

### Are you accessing code-server over a secure context?

- [X] I am using a secure context.

**Comment by code-asher** [comment] 2024-07-17 17:36
I tried to reproduce in 4.91.0 with a `test.html` file with just the contents:

```
<!-- https://web.jefftuschool.com/test.html -->
```

But the `Follow link` tooltip shows up immediately for me without any loading or CPU issues.  I tested Firefox and Chromium on Linux, so maybe it is only reproducible on macOS.  Do you have any settings that might affect this?  Maybe I have to enable something.

If you could load into https://vscode.dev or Codespaces and test it there, that would also be helpful since it seems likely to be an upstream issue with VS Code.

**Comment by nardis556** [comment] 2024-07-19 23:22
this seems to be due to websocket closing? my setup runs behind nginx with letsencrypt locally and has been running for days and now this issue
![image](https://github.com/user-attachments/assets/9f827882-906b-4b8b-affb-fce334f7dff2)

**Comment by jefftuschool** [comment] 2024-07-20 15:44
I've found that my repositories contain a different user, other than the current user. That's why causing the git server keep looking or searching... up the CPU. But this behavior was fine until version 4.90.3.

Thank you for the help!

<img width="1253" alt="Screenshot 2024-07-17 at 8 19 56 PM" src="https://github.com/user-attachments/assets/281ce289-8a5b-4f2f-88e4-f462805a3548">

**Comment by code-asher** [comment] 2024-07-22 19:51
Ah interesting!  We should try retesting Codespaces and see if we can reproduce.  Seems likely to be an issue with the built-in Git extension.

**Comment by code-asher** [comment] 2024-09-19 19:20
Closing for now but let me know if you come back to this and are able to reproduce with Codespaces.

**Closed by code-asher** 2024-09-19 19:20 UTC
Labels: bug
