### ISSUE TITLE
[Bug]: -r opens wrong file in wrong instance

### ISSUE THREAD

**Issue by danog** [coder/code-server#5709] opened 2022-10-26 08:53 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Firefox
- Local OS: Arch
- Remote OS: Arch
- Remote Architecture: x86_64
- `code-server --version`: 4.7.1 b562d4a880f21aace51b6bd1e7ac64330d023b3a with Code 1.71.2

### Steps to Reproduce

1. Open two code-server workspaces for folders `a` and `b` in two tabs
2. In folder `a`, run `code-server -r a.php`

### Expected

The first tab opens `a/a.php`

### Actual

The second tab opens `b/a.php`

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by tobycm** [comment] 2022-10-26 08:56
Probably the second tab is opened after the first tab so code-server favored it over the first one.

**Comment by danog** [comment] 2022-10-26 09:33
Yeah, I imagined this was the case, but vscode automatically opens the file in the correct instance.

**Comment by tobycm** [comment] 2022-10-26 10:24
I opened up 2 `a` and `b` folder in vscode, in different windows. Opening a file using the code cli leads me to the `b` window so I guess this is normal behaviour?

**Comment by jsjoeio** [comment] 2022-10-26 15:28
Thank you both for your insight! If the behavior is the same in vscode, then we could classify it as an upstream issue. Let me know if we should close this!

**Comment by felipecrs** [comment] 2022-10-26 19:36
Just to clarify, I believe @danog means that he's using the VS Code integrated terminal. When inside the integrated terminal, `code -r` ensures to open the file in the current window.

**Comment by danog** [comment] 2022-10-26 20:35
Actually no I opened the files in a separate terminal, and I could've sworn this worked/was recently fixed in vscode, will try again tomorrow

**Comment by sleexyz** [comment] 2023-04-30 20:49
If I understand correctly, the `vscode-ipc` file can only track the most recently registered vscode ipc socket. This means `-r` so far can only open files in the most recently registered client.

A possible solution:

Extend `vscode-ipc` to track multiple socket paths and their corresponding workspaces / folders (i.e. `vscode-ipc.json`):

```
[
  {
  "folder": <FOLDER>,
  "socketPath": <SOCKET_PATH>,
  }
]
```

Basically:
- Switch from using a single-entry `vscode-ipc` to using  a multi-entry `vscode-ipc.json`
- Modify the [`store_socket.diff`](https://github.com/coder/code-server/blob/main/patches/store-socket.diff) patch to have vscode append an entry to `vscode-ipc.json`
- Modify "open in existing instance" behavior to find the most relevant vscode ipc socket for a given file.

Happy to make a PR to get this to work :)

**Comment by code-asher** [comment] 2023-05-01 16:09
That sounds like a lovely solution and PRs are definitely welcome.

Just to check, we are talking about the behavior when running `code-server -r` from an external terminal, right?  There we use `vscode-ipc` but from inside the integrated terminal VS Code does its own thing so if the problem is presenting there we may want to reproduce in Codespaces and raise it upstream.

**Comment by sleexyz** [comment] 2023-05-02 01:30
> Just to check, we are talking about the behavior when running code-server -r from an external terminal, right? 
Correct.

**Closed** 2023-06-14 21:32 UTC
Labels: bug, needs-investigation
