### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by tujeff** [coder/code-server#5204] opened 2022-05-16 05:33 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: MacOS
- Remote OS: Debian Bullseye
- Remote Architecture: amd64
- `code-server --version`: 4.4.0

### Steps to Reproduce

1. Just a upgrade to 4.4.0
2. 
3.

### Expected

Should have Debug Console and Git working correctly after upgrade to 4.4.0

### Actual

After upgrading to 4.4.0, Git and Debug Console is missing.

### Screenshot/Video

<img width="1070" alt="Screen Shot 2022-05-15 at 10 18 51 PM" src="https://user-images.githubusercontent.com/67305851/168525577-13214143-7d91-4596-86b2-b30aad0692d8.png">

### Does this issue happen in VS Code?

- [X] I cannot reproduce this in VS Code.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by tujeff** [comment] 2022-05-16 05:34
After upgrading to 4.4.0, Git and Debug Console is missing.

**Comment by jsjoeio** [comment] 2022-05-19 21:46
Duplicate of https://github.com/coder/code-server/issues/5206

**Closed by jsjoeio** 2022-05-19 21:46 UTC
Labels: bug, triage
