### ISSUE TITLE
[Bug]: ChatGPT extension not show the chat window.

### ISSUE THREAD

**Issue by chaotec** [coder/code-server#6117] opened 2023-03-30 04:25 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### OS/Web Information

- Web Browser: Chrome
- Local OS: Windows 10
- Remote OS: Centos 7
- Remote Architecture: amd64
- `code-server --version`: 4.11.0

### Steps to Reproduce

1. Install the chatgpt extension.
2. Click the icon of chatgpt.

### Expected

Show the chat window like vscode.
![image](https://user-images.githubusercontent.com/49848887/228728911-3f28e420-5357-4fbd-95a6-a39ff5815c39.png)

### Actual

No any content.
![image](https://user-images.githubusercontent.com/49848887/228728999-0d690ecb-7ac3-49c9-8e43-2574c2efbdaa.png)

### Logs

[04:14:16] Getting Manifest... genieai.chatgpt-vscode
[04:14:18] Installing extension: genieai.chatgpt-vscode
[04:14:21] Extracted extension to /config/extensions/.0558bc05-7fb5-4232-92d6-3abbf47b342a: genieai.chatgpt-vscode
[04:14:21] Renamed to /config/extensions/genieai.chatgpt-vscode-0.0.4-universal
[04:14:21] Extracting extension completed. genieai.chatgpt-vscode
[04:14:21] Extension installed successfully: genieai.chatgpt-vscode

### Does this issue happen in VS Code or GitHub Codespaces?

- [X] I cannot reproduce this in VS Code.
- [X] I cannot reproduce this in GitHub Codespaces.

### Are you accessing code-server over HTTPS?

- [X] I am using HTTPS.

**Comment by duyanghao** [comment] 2023-04-03 05:47
Any process for this problem?

**Comment by code-asher** [comment] 2023-04-03 19:04
Are there any logs in the browser console?  I tried out the
extension but it works for me.

**Comment by chaotec** [comment] 2023-04-11 12:01
> Are there any logs in the browser console? I tried out the extension but it works for me.

I tried it in mircorsoft edge. It works. But for chrome it still not work.

The edge version is 112.0.1722.39 (64bit).
The chrome version is 112.0.5615.49 (64bit).

**Comment by code-asher** [comment] 2023-04-11 20:35
Weird!  I just tried code-server 4.11.0 on Chrome 112.0.5615.49 on 
Windows 10 and it is working there for me.  Did you see any logs?

**Comment by alicfeng** [comment] 2023-04-20 07:09
I have also encountered the same problem. May I ask if there is a solution to this problem？

**Comment by code-asher** [comment] 2023-04-21 18:01
If you post your browser console logs we can see if there is 
anything there that will help us debug the issue.

**Comment by alicfeng** [comment] 2023-04-26 08:11
基于 `code-server --cert=... --cert-key=...` 指定证书确实没有问题，但是在网关中指定 `TLS` 依然存在问题

**Comment by pigpag** [comment] 2023-04-27 20:39
Are you running HTTPS?

**Comment by binhex** [comment] 2023-05-25 10:47
I'm seeing the exact same issue running latest version of code-server and the latest stable release of Chrome, if I patiently wait then eventually i will see the following error appear, so it def looks like its HTTPS related:-
![image](https://github.com/coder/code-server/assets/1121837/be820b45-2f06-47b8-bbf4-79e9f2886e5b)

The error message looks similar to the error i used to get when going to the 'DETAILS' tab for any extension, I see this is now fixed (fantastic work btw!) so maybe this is related and you need to perform the same fix to the 'Primary Side Bar' to allow the ChatGPT Genie extension to display the controls.

FYI link to the extension is here:- https://marketplace.visualstudio.com/items?itemName=genieai.chatgpt-vscode

**Comment by code-asher** [comment] 2023-05-30 21:23
Ahh good find!  Service workers (and web views by extension) require valid TLS even if you click past the warning when first loading the site (at least in some browsers, I think Chrome does this but Firefox does not).

But interesting that you are not getting the error on the details tab though...that is also a web view.  I would expect both to be broken unless something changed in VS Code and some simpler web views no longer use service workers.

**Comment by code-asher** [comment] 2023-05-30 21:25
Ah yup found the commit, service workers disabled for extension details: https://github.com/microsoft/vscode/commit/a269f7d6a1880c3e90e4d1d05e4e6904279659ba

This will probably not work with the ChatGPT extension; most likely the service worker is needed there.

**Comment by code-asher** [comment] 2023-07-21 18:31
Closing as expected behavior; service workers need to be ran in a secure context and it appears the extension needs service workers.

**Closed by code-asher** 2023-07-21 18:31 UTC
Labels: bug, triage
